"""
build_civics_data.py
Builds the comprehensive, high-quality question dictionaries for:
- USA Tests (160)
- DMV Test (160)
- License Plate Quiz (130)
- General Knowledge (160)
Appends or updates data_civics_driving.py
"""

import os

def create_dmv_and_civics_file():
    target = os.path.abspath('scripts/generators/data_civics_driving.py')
    with open(target, 'r', encoding='utf-8') as f:
        existing = f.read()

    # Now let's append the remaining 4 categories to data_civics_driving.py
    additional_code = '''
def get_usa_tests_items():
    return {
        "US Civics": [
            ("What is the supreme law of the land in the United States?", "The United States Constitution", ["The Declaration of Independence", "The Articles of Confederation", "The Federalist Papers"], "The US Constitution establishes the national frame of government and fundamental laws of the nation."),
            ("What are the two major political parties in the modern United States?", "Democratic and Republican", ["Libertarian and Green", "Federalist and Anti-Federalist", "Whig and Democratic-Republican"], "The Democratic Party and Republican Party are the two dominant parties in the US political system."),
            ("How many voting members currently serve in the United States House of Representatives?", "435", ["100", "50", "438"], "The Permanent Apportionment Act of 1929 capped the House of Representatives at 435 voting members."),
            ("How many voting members serve in the United States Senate?", "100", ["435", "50", "538"], "Each of the 50 states elects exactly two senators, totaling 100 US senators."),
            ("For how many years is a United States Senator elected to serve in one term?", "6 years", ["2 years", "4 years", "8 years"], "Senators serve staggered six-year terms, with approximately one-third of seats up for election every two years."),
            ("For how many years is a member of the United States House of Representatives elected to serve in one term?", "2 years", ["4 years", "6 years", "1 year"], "House representatives are elected every two years directly by the citizens of their congressional districts."),
            ("What is the minimum age required by the Constitution to serve as President of the United States?", "35 years old", ["30 years old", "25 years old", "40 years old"], "Article II, Section 1 sets the qualifications: a natural-born citizen, at least 35 years old, and 14 years a resident within the US."),
            ("What is the minimum age required by the Constitution to serve as a United States Senator?", "30 years old", ["25 years old", "35 years old", "21 years old"], "Article I, Section 3 requires a senator to be at least 30 years old and a citizen of the US for at least 9 years."),
            ("What is the minimum age required by the Constitution to serve in the United States House of Representatives?", "25 years old", ["30 years old", "21 years old", "18 years old"], "Article I, Section 2 requires representatives to be at least 25 years old and a citizen of the US for at least 7 years."),
            ("In what month do United States citizens vote for President in national general elections?", "November", ["October", "January", "December"], "Federal general elections are held on the Tuesday following the first Monday in November."),
            ("Who becomes President of the United States if both the President and Vice President can no longer serve?", "The Speaker of the House of Representatives", ["The Senate President pro tempore", "The Secretary of State", "The Chief Justice of the Supreme Court"], "Under the Presidential Succession Act of 1947, the Speaker of the House is second in line of succession."),
            ("Who is the Commander in Chief of the United States Armed Forces?", "The President of the United States", ["The Secretary of Defense", "The Chairman of the Joint Chiefs of Staff", "The Speaker of the House"], "Article II, Section 2 of the Constitution designates the President as Commander in Chief of the Army and Navy."),
            ("Who signs bills passed by Congress to make them official federal laws?", "The President of the United States", ["The Chief Justice", "The Vice President", "The Attorney General"], "The President must sign an enrolled bill for it to become law, or it becomes law after 10 days without a presidential veto."),
            ("What fraction of votes in both the House and Senate is required to override a Presidential veto?", "Two-thirds majority (2/3)", ["Three-fourths majority (3/4)", "Simple majority (50% + 1)", "Three-fifths majority (3/5)"], "Article I, Section 7 requires a two-thirds supermajority in both chambers of Congress to enact a bill over a presidential veto."),
            ("What is the highest judicial court in the United States?", "The Supreme Court of the United States", ["The Court of Appeals for the Federal Circuit", "The Court of International Trade", "The District Court of Washington D.C."], "Article III establishes the Supreme Court as the highest court with final appellate jurisdiction over federal questions."),
            ("How many Justices currently serve on the Supreme Court of the United States?", "9", ["7", "11", "12"], "The Judiciary Act of 1869 set the number of Supreme Court Justices at nine (one Chief Justice and eight Associate Justices)."),
            ("Who appoints federal judges and Supreme Court Justices in the United States?", "The President, with the advice and consent of the Senate", ["The House of Representatives", "The Chief Justice", "Direct popular vote by citizens"], "Under the Appointments Clause of Article II, the President nominates judges subject to confirmation by a Senate majority."),
            ("How long do federal judges, including Supreme Court Justices, hold their office under Article III?", "Life tenure during good behavior", ["Ten-year terms", "Four-year renewable terms", "Until age 70"], "Article III judges serve for life during good behavior, insulating the judiciary from political pressures."),
            ("Who is the official President of the United States Senate, casting the tie-breaking vote when senators are equally divided?", "The Vice President of the United States", ["The Senate Majority Leader", "The Speaker of the House", "The Attorney General"], "Article I, Section 3 designates the Vice President as President of the Senate with no vote unless the chamber is tied 50-50."),
            ("What body officially elects the President and Vice President of the United States based on state popular votes?", "The Electoral College", ["The United States Senate", "The House of Representatives", "The National Governors Association"], "Citizens vote for electors representing their state; the candidate securing at least 270 of 538 electoral votes wins the presidency."),
            ("How many total electoral votes comprise the United States Electoral College?", "538", ["500", "435", "100"], "538 votes total: 435 for representatives, 100 for senators, and 3 for the District of Columbia under the 23rd Amendment."),
            ("How many electoral votes are needed for a presidential candidate to win a majority in the Electoral College?", "270", ["268", "300", "250"], "A candidate must achieve an absolute majority of 270 electoral votes out of 538 to win the election."),
            ("Which federal department is responsible for foreign affairs and diplomatic relations of the United States?", "The Department of State", ["The Department of Homeland Security", "The Department of Defense", "The Department of Commerce"], "Headed by the Secretary of State, the State Department advises the President on foreign policy and leads diplomacy."),
            ("Which executive department is responsible for federal law enforcement and legal affairs, headed by the Attorney General?", "The Department of Justice", ["The Department of the Interior", "The Department of Homeland Security", "The Department of the Treasury"], "The Department of Justice enforces federal laws, prosecutes federal criminal cases, and represents the US government in court."),
            ("What is the primary role of the President\'s Cabinet?", "To advise the President on matters relating to their respective executive departments", ["To pass federal legislation", "To interpret constitutional legality of laws", "To command combat troops directly"], "The Cabinet consists of the Vice President and heads of 15 executive departments, serving as the President\'s principal advisory advisory council."),
            ("Under the US Constitution, who possesses the exclusive power to declare war?", "The United States Congress", ["The President of the United States", "The Secretary of Defense", "The Joint Chiefs of Staff"], "Article I, Section 8, Clause 11 explicitly grants Congress the constitutional power to declare war."),
            ("Under the US Constitution, who has the sole power to impeach a federal official?", "The House of Representatives", ["The United States Senate", "The Supreme Court", "The Department of Justice"], "Article I, Section 2 grants the House the sole power of impeachment (bringing formal charges)."),
            ("Where is the impeachment trial of a federal official conducted after charges are brought by the House?", "In the United States Senate", ["In the Supreme Court", "In the Federal District Court", "In a military tribunal"], "Article I, Section 3 states that the Senate has the sole power to try all impeachments, requiring a two-thirds vote to convict."),
            ("Who presides over the Senate trial when the President of the United States is impeached?", "The Chief Justice of the Supreme Court", ["The Vice President", "The Senate Majority Leader", "The Speaker of the House"], "Article I, Section 3 requires the Chief Justice to preside over a presidential impeachment trial to avoid a conflict of interest with the Vice President."),
            ("What is the minimum voting age for United States citizens established by the Twenty-Sixth Amendment?", "18 years old", ["21 years old", "16 years old", "20 years old"], "Ratified in 1971 during the Vietnam War, the 26th Amendment lowered the voting age across the country to 18."),
            ("Which constitutional amendment guarantees the right of citizens to peaceably assemble and petition the government for a redress of grievances?", "The First Amendment", ["The Second Amendment", "The Fourth Amendment", "The Fifth Amendment"], "The First Amendment protects five fundamental freedoms: religion, speech, press, assembly, and petition."),
            ("Which constitutional amendment protects citizens against unreasonable searches and seizures of their persons, houses, papers, and effects?", "The Fourth Amendment", ["The Fifth Amendment", "The Sixth Amendment", "The Eighth Amendment"], "The Fourth Amendment requires warrants supported by probable cause describing the place to be searched and persons or things to be seized."),
            ("Which constitutional amendment guarantees protection against double jeopardy and self-incrimination, and ensures due process of law?", "The Fifth Amendment", ["The Fourth Amendment", "The Sixth Amendment", "The Seventh Amendment"], "The Fifth Amendment provides the right to grand jury indictment, prohibits double jeopardy, and guarantees due process."),
            ("Which constitutional amendment guarantees an accused person the right to a speedy and public trial by an impartial jury and the assistance of counsel?", "The Sixth Amendment", ["The Seventh Amendment", "The Fifth Amendment", "The Eighth Amendment"], "The Sixth Amendment secures fundamental criminal trial rights, including compulsory process and legal counsel."),
            ("Which constitutional amendment prohibits excessive bail, excessive fines, and cruel and unusual punishments?", "The Eighth Amendment", ["The Seventh Amendment", "The Ninth Amendment", "The Tenth Amendment"], "The Eighth Amendment safeguards individuals against disproportionate punishments and torture by the state."),
            ("Which constitutional amendment clarifies that the enumeration of certain rights in the Constitution shall not be construed to deny other retained rights?", "The Ninth Amendment", ["The Tenth Amendment", "The Seventh Amendment", "The Fourteenth Amendment"], "The Ninth Amendment confirms that individuals possess unenumerated fundamental natural rights not explicitly written in the text."),
            ("Which constitutional amendment states that powers not delegated to the federal government by the Constitution are reserved to the states or people?", "The Tenth Amendment", ["The Ninth Amendment", "The Eleventh Amendment", "The Twelfth Amendment"], "The Tenth Amendment embodies the core principle of federalism, preserving states\' police powers and residual authority."),
            ("How many total constitutional amendments have been ratified since the adoption of the United States Constitution?", "27 amendments", ["10 amendments", "21 amendments", "33 amendments"], "Starting with the Bill of Rights (1-10 in 1791), 27 total amendments have been ratified, most recently the 27th in 1992."),
            ("What process conducts a complete national count of the United States population every ten years as mandated by Article I?", "The United States Decennial Census", ["The Federal Voter Registry", "The Department of Labor Survey", "The National Housing Index"], "The US Census counts every resident to determine the apportionment of seats in the House of Representatives."),
            ("What is the primary responsibility of the executive branch of the United States government?", "To enforce and administer federal laws", ["To make and enact federal statutory laws", "To evaluate and interpret the constitutionality of laws", "To print and regulate monetary currency"], "Article II vests executive power in the President to ensure that laws enacted by Congress are faithfully executed.")
        ],
        "US Constitution": [
            ("Which Article of the United States Constitution establishes the structure, powers, and limits of the Legislative Branch (Congress)?", "Article I", ["Article II", "Article III", "Article IV"], "Article I establishes the bicameral Congress (Senate and House of Representatives) and lists legislative powers."),
            ("Which Article of the United States Constitution establishes the Executive Branch headed by the President?", "Article II", ["Article I", "Article III", "Article IV"], "Article II details executive authority, presidential qualifications, election procedures, and removal through impeachment."),
            ("Which Article of the United States Constitution establishes the Judicial Branch and the Supreme Court?", "Article III", ["Article II", "Article IV", "Article V"], "Article III creates the Supreme Court, grants federal judicial tenure during good behavior, and defines treason."),
            ("Which Article of the United States Constitution addresses relations among states and guarantees a republican form of government to every state?", "Article IV", ["Article III", "Article V", "Article VI"], "Article IV contains the Full Faith and Credit Clause, Privileges and Immunities Clause, and procedures for admitting new states."),
            ("Which Article of the United States Constitution specifies the two methods for proposing and ratifying constitutional amendments?", "Article V", ["Article IV", "Article VI", "Article VII"], "Article V stipulates that amendments may be proposed by a two-thirds vote of both houses of Congress and ratified by three-fourths of states."),
            ("Which clause in Article VI of the Constitution declares that the Constitution and federal treaties constitute the supreme law of the land?", "The Supremacy Clause", ["The Commerce Clause", "The Necessary and Proper Clause", "The Equal Protection Clause"], "The Supremacy Clause ensures that federal constitutional law takes precedence over conflicting state laws and state constitutions."),
            ("Which clause in Article I, Section 8 authorizes Congress to make all laws 'necessary and proper' for executing enumerated powers?", "The Elastic Clause (Necessary and Proper Clause)", ["The Commerce Clause", "The General Welfare Clause", "The Due Process Clause"], "The Elastic Clause grants Congress implied powers beyond its explicitly listed enumerated constitutional duties."),
            ("Which clause in Article I, Section 8 grants Congress the authority to regulate commerce with foreign nations and among the several states?", "The Commerce Clause", ["The Supremacy Clause", "The Contracts Clause", "The Takings Clause"], "The Commerce Clause has served as the constitutional foundation for federal regulation of the interstate national economy."),
            ("What constitutional clause in Article IV requires each state to recognize public acts, records, and judicial proceedings of every other state?", "The Full Faith and Credit Clause", ["The Privileges and Immunities Clause", "The Establishment Clause", "The Free Exercise Clause"], "This clause ensures legal reciprocity, such as state recognition of marriages, driver licenses, and civil court judgments."),
            ("What clause of the First Amendment prohibits the federal government from establishing an official state religion or favoring one faith?", "The Establishment Clause", ["The Free Exercise Clause", "The Equal Protection Clause", "The Supremacy Clause"], "The Establishment Clause erects a wall of separation between church and state, banning government-sponsored religion."),
            ("What clause of the First Amendment protects the fundamental right of individuals to practice their chosen religious beliefs freely?", "The Free Exercise Clause", ["The Establishment Clause", "The Privileges and Immunities Clause", "The Due Process Clause"], "The Free Exercise Clause prohibits government interference with the lawful exercise and practice of religious faith."),
            ("What legal doctrine derived from the Fourth Amendment bars the use of unconstitutionally seized evidence in a criminal trial?", "The Exclusionary Rule", ["The Plain View Doctrine", "The Good Faith Exception", "The Inevitable Discovery Rule"], "Established in Weeks v. US and applied to states in Mapp v. Ohio, this rule excludes illegally obtained evidence."),
            ("What constitutional safeguard ensures that an arrested person must be brought before a judge to determine whether their detention is lawful?", "Writ of Habeas Corpus", ["Ex Post Facto Law", "Bill of Attainder", "Letters of Marque"], "Article I, Section 9 protects the Privilege of the Writ of Habeas Corpus from suspension except in cases of rebellion or invasion."),
            ("What type of retroactive criminal law, strictly prohibited by Article I of the Constitution, punishes an act committed before the law was passed?", "Ex post facto law", ["Bill of attainder", "Writ of mandamus", "Substantive due process law"], "The Constitution bans both federal and state governments from passing ex post facto laws that retroactively increase criminal penalties."),
            ("What legislative act that declares a named person guilty of a crime and imposes punishment without a judicial trial is banned by the Constitution?", "Bill of attainder", ["Ex post facto law", "Writ of certiorari", "Quo warranto"], "Bills of attainder violate the separation of powers by allowing legislators to perform judicial sentencing."),
            ("Which constitutional amendment established the direct popular election of United States Senators by the voters of each state?", "The Seventeenth Amendment", ["The Sixteenth Amendment", "The Fifteenth Amendment", "The Nineteenth Amendment"], "Ratified in 1913, the 17th Amendment replaced senator selection by state legislatures with direct democratic elections."),
            ("Which constitutional amendment authorized the federal government to levy an income tax on individuals without state apportionment?", "The Sixteenth Amendment", ["The Fifteenth Amendment", "The Seventeenth Amendment", "The Fourteenth Amendment"], "Ratified in 1913, the 16th Amendment empowered Congress to collect taxes on incomes from whatever source derived."),
            ("Which constitutional amendment enacted national Prohibition, banning the manufacture, sale, and transportation of intoxicating liquors?", "The Eighteenth Amendment", ["The Sixteenth Amendment", "The Twenty-First Amendment", "The Twentieth Amendment"], "Ratified in 1919, the 18th Amendment outlawed alcohol, creating an era of bootlegging and speakeasies."),
            ("Which constitutional amendment repealed Prohibition in 1933, making it the only amendment ratified specifically to overturn an earlier amendment?", "The Twenty-First Amendment", ["The Twentieth Amendment", "The Twenty-Second Amendment", "The Nineteenth Amendment"], "The 21st Amendment repealed the 18th Amendment, returning alcohol regulation to the individual states."),
            ("Which constitutional amendment moved Presidential Inauguration Day from March 4 to January 20, reducing the 'lame duck' transition period?", "The Twentieth Amendment", ["The Twenty-Second Amendment", "The Twenty-Fifth Amendment", "The Twenty-Fourth Amendment"], "Ratified in 1933, the 20th Amendment shortened the post-election transition period for the President and Congress."),
            ("Which constitutional amendment limits an elected President of the United States to serving a maximum of two full terms in office?", "The Twenty-Second Amendment", ["The Twentieth Amendment", "The Twenty-Fourth Amendment", "The Twenty-Fifth Amendment"], "Ratified in 1951 following FDR\'s four presidential election victories, the 22nd Amendment limits presidents to two terms."),
            ("Which constitutional amendment granted the District of Columbia three electoral votes in presidential elections?", "The Twenty-Third Amendment", ["The Twenty-Fourth Amendment", "The Twenty-Second Amendment", "The Twenty-Sixth Amendment"], "Ratified in 1961, the 23rd Amendment gave D.C. residents representation in the Electoral College."),
            ("Which constitutional amendment prohibited poll taxes in federal elections, removing a major Jim Crow voting barrier for minority citizens?", "The Twenty-Fourth Amendment", ["The Fifteenth Amendment", "The Nineteenth Amendment", "The Twenty-Sixth Amendment"], "Ratified in 1964, the 24th Amendment outlawed payment of poll taxes as a condition for voting in federal elections."),
            ("Which constitutional amendment established clear procedures for presidential disability and filling vacancies in the office of Vice President?", "The Twenty-Fifth Amendment", ["The Twentieth Amendment", "The Twenty-Second Amendment", "The Twelfth Amendment"], "Ratified in 1967, the 25th Amendment provides mechanisms for transferring presidential power during incapacitation."),
            ("Which constitutional amendment requires that any congressional salary change take effect only after an intervening House election?", "The Twenty-Seventh Amendment", ["The Twenty-Sixth Amendment", "The Twenty-Fifth Amendment", "The Twenty-Third Amendment"], "Originally proposed by James Madison in 1789, the 27th Amendment was finally ratified 202 years later in 1992."),
            ("Which constitutional amendment reformed the Electoral College by requiring electors to cast separate, distinct ballots for President and Vice President?", "The Twelfth Amendment", ["The Eleventh Amendment", "The Tenth Amendment", "The Fourteenth Amendment"], "Ratified in 1804 after the tied election of 1800, the 12th Amendment ended the practice of runner-up becoming Vice President."),
            ("What constitutional clause in the Fifth Amendment guarantees that private property cannot be taken for public use without just compensation?", "The Takings Clause (Eminent Domain)", ["The Due Process Clause", "The Contracts Clause", "The Commerce Clause"], "The Takings Clause limits sovereign eminent domain by mandating fair market financial compensation for expropriated land."),
            ("What constitutional clause in the Fourteenth Amendment prohibits states from denying any person equal protection under the laws?", "The Equal Protection Clause", ["The Due Process Clause", "The Citizenship Clause", "The Privileges or Immunities Clause"], "The Equal Protection Clause serves as the primary constitutional vehicle for dismantling segregation and discriminatory laws."),
            ("What constitutional principle divides federal authority among three independent branches: legislative, executive, and judicial?", "Separation of Powers", ["Federalism", "Popular Sovereignty", "Judicial Restraint"], "Conceived by Montesquieu and embedded in Articles I, II, and III, separation of powers prevents autocratic consolidation of power."),
            ("What constitutional system gives each of the three branches of government the authority to check and balance the other two branches?", "Checks and Balances", ["Federalism", "Bicameralism", "Direct Democracy"], "Examples include presidential vetoes, Senate treaty ratification, and judicial review of legislative statutes."),
            ("What political system divides sovereign governing power between a central national government and individual regional state governments?", "Federalism", ["Unitary Government", "Confederation", "Direct Democracy"], "The US federal system delegates enumerated powers to the national government while reserving residual powers to states."),
            ("What constitutional standard requires a search warrant to be based on specific facts and circumstances establishing fair probability of a crime?", "Probable Cause", ["Reasonable Suspicion", "Preponderance of the Evidence", "Beyond a Reasonable Doubt"], "The Fourth Amendment requires sworn affidavits establishing probable cause before a neutral magistrate issues a search warrant."),
            ("What standard of evidence, lower than probable cause, is required for a police officer to conduct a brief investigatory stop and frisk under Terry v. Ohio?", "Reasonable Articulable Suspicion", ["Probable Cause", "Clear and Convincing Evidence", "Proof beyond a reasonable doubt"], "Officers must possess specific, articulable facts showing criminal activity may be afoot to perform an investigatory Terry stop."),
            ("What landmark 1803 Supreme Court case established the principle of Judicial Review, empowering federal courts to declare acts of Congress unconstitutional?", "Marbury v. Madison", ["McCulloch v. Maryland", "Gibbons v. Ogden", "Dred Scott v. Sandford"], "Chief Justice John Marshall declared that 'it is emphatically the province and duty of the judicial department to say what the law is.'"),
            ("What landmark 1819 Supreme Court case affirmed the constitutionality of the Bank of the United States and the supremacy of federal law over states?", "McCulloch v. Maryland", ["Marbury v. Madison", "Gibbons v. Ogden", "Barron v. Baltimore"], "The court held that Congress possesses implied powers under the Elastic Clause and that 'the power to tax involves the power to destroy.'"),
            ("What landmark 1824 Supreme Court decision established broad federal regulatory power over interstate commerce, including navigation?", "Gibbons v. Ogden", ["McCulloch v. Maryland", "Marbury v. Madison", "Cohens v. Virginia"], "The decision dismantled New York\'s steamboat navigation monopoly, asserting broad federal supremacy under the Commerce Clause."),
            ("What landmark 1966 Supreme Court ruling established that criminal suspects must be informed of their constitutional rights before custodial interrogation?", "Miranda v. Arizona", ["Gideon v. Wainwright", "Mapp v. Ohio", "Escobedo v. Illinois"], "Suspects must be advised of their right to remain silent, that statements can be used against them, and their right to an attorney."),
            ("What landmark 1963 Supreme Court ruling established that states must provide free legal counsel to indigent criminal defendants under the Sixth Amendment?", "Gideon v. Wainwright", ["Miranda v. Arizona", "Terry v. Ohio", "Mapp v. Ohio"], "The court held that the Sixth Amendment right to counsel is a fundamental right essential to a fair trial applied to states via the 14th Amendment."),
            ("What constitutional clause prohibits a person from being prosecuted twice for the exact same criminal offense after an acquittal or conviction?", "The Double Jeopardy Clause", ["The Due Process Clause", "The Self-Incrimination Clause", "The Cruel and Unusual Punishment Clause"], "Found in the Fifth Amendment, double jeopardy protects citizens from repeated state prosecutions for the same act."),
            ("How many states were required to ratify the United States Constitution under Article VII before it could take legal effect among ratifying states?", "9 out of 13 states", ["All 13 states", "7 out of 13 states", "10 out of 13 states"], "Article VII established that nine state ratifying conventions were required; New Hampshire became the crucial ninth state in June 1788.")
        ],
        "American Government": [
            ("What is the primary role of the legislative branch of the United States government?", "To write, debate, and pass federal laws", ["To enforce and execute statutory laws", "To interpret the constitutionality of laws", "To command active armed forces"], "Article I vests all federal legislative powers in the bicameral Congress of the United States."),
            ("What is the title of the presiding officer of the United States House of Representatives, chosen by a vote of its members?", "Speaker of the House", ["Majority Leader", "President pro tempore", "House Whip"], "The Speaker of the House presides over debates, sets the legislative agenda, and leads the majority party caucus."),
            ("Who presides over the United States Senate in the absence of the Vice President?", "The President pro tempore", ["The Speaker of the House", "The Senate Majority Whip", "The Secretary of the Senate"], "The President pro tempore is traditionally the longest-serving senator of the majority party."),
            ("What legislative procedure in the United States Senate allows a senator to prolong debate to delay or prevent a vote on a bill?", "A filibuster", ["A cloture motion", "A pocket veto", "A discharge petition"], "Filibusters allow prolonged debate; ending a filibuster traditionally requires invoking cloture with a three-fifths supermajority."),
            ("How many votes are required in the United States Senate to invoke Cloture and bring an end to a filibuster on general legislation?", "60 votes (three-fifths majority)", ["51 votes (simple majority)", "67 votes (two-thirds majority)", "75 votes (three-fourths majority)"], "Senate Rule XXII requires a three-fifths vote of all sworn senators (normally 60 votes) to invoke cloture."),
            ("What happens to a bill if the President does not sign or veto it within 10 days while Congress is adjourned?", "The bill dies by Pocket Veto", ["The bill automatically becomes law", "The bill returns to the Senate for reconsideration", "The bill is submitted to the Supreme Court"], "A pocket veto occurs when Congress adjourns before the 10-day signing period expires, preventing a presidential veto override."),
            ("What happens to a bill if the President does not sign or veto it within 10 days while Congress is in session?", "The bill automatically becomes law without presidential signature", ["The bill is automatically rejected", "The bill must be revoted in the House", "The bill is referred to a conference committee"], "Article I, Section 7 specifies that an unsigned bill becomes law after 10 days (excluding Sundays) if Congress remains in session."),
            ("What joint committee of Congress reconciles differences between House and Senate versions of the same legislative bill?", "A Conference Committee", ["A Standing Committee", "A Select Committee", "A Joint Economic Committee"], "Conference committees iron out differences, producing a compromise conference report that both chambers must pass unchanged."),
            ("Which permanent congressional committees have legislative jurisdiction to consider and report bills within their specialized policy areas?", "Standing Committees", ["Conference Committees", "Select Committees", "Ad Hoc Committees"], "Standing committees (e.g., House Judiciary, Senate Foreign Relations) handle the regular ongoing work of legislation."),
            ("Which powerful House committee determines the rules, terms, and amendments under which bills will be debated on the House floor?", "The House Rules Committee", ["The Ways and Means Committee", "The Appropriations Committee", "The Oversight Committee"], "Often called the 'traffic cop of the House', the Rules Committee controls which bills reach the floor and how they are amended."),
            ("Which House committee has constitutional jurisdiction over taxation, revenue-raising measures, customs, and entitlement programs?", "The House Ways and Means Committee", ["The Budget Committee", "The Financial Services Committee", "The Appropriations Committee"], "Article I mandates that all revenue-raising bills must originate in the House, under the jurisdiction of Ways and Means."),
            ("Which congressional committee in each chamber is responsible for drafting legislation that allocates federal funding to government agencies?", "The Appropriations Committee", ["The Budget Committee", "The Finance Committee", "The Ways and Means Committee"], "Appropriations committees write annual spending bills that fund discretionary operations of the federal government."),
            ("What is the formal role of the Federal Reserve System (the Fed) in the United States government?", "The independent central bank that conducts monetary policy and regulates financial institutions", ["The executive department that collects federal income taxes", "The agency that prints physical paper currency exclusively", "The congressional committee that oversees national debt ceilings"], "Created by the Federal Reserve Act of 1913, the Fed manages interest rates, money supply, and banking system stability."),
            ("How many geographic Federal Reserve Districts comprise the Federal Reserve System across the United States?", "12 districts", ["10 districts", "15 districts", "50 districts"], "The Federal Reserve System includes 12 regional Reserve Banks situated in major financial centers across the country."),
            ("Who nominates the Chair of the Federal Reserve Board of Governors for a four-year term?", "The President of the United States, confirmed by the Senate", ["The Secretary of the Treasury", "The President of the New York Fed", "Direct popular vote of commercial bank CEOs"], "The President appoints the Fed Chair from among the members of the Board of Governors, subject to Senate confirmation."),
            ("Which agency within the executive branch is responsible for collecting federal taxes and enforcing the Internal Revenue Code?", "Internal Revenue Service (IRS)", ["Federal Reserve", "Treasury Office of Thrift", "Consumer Financial Protection Bureau"], "The IRS is a bureau of the Department of the Treasury responsible for administering the federal tax collection system."),
            ("Which independent federal regulatory agency regulates interstate and international communications by radio, television, wire, satellite, and cable?", "Federal Communications Commission (FCC)", ["Federal Trade Commission (FTC)", "Securities and Exchange Commission (SEC)", "Consumer Product Safety Commission (CPSC)"], "The FCC oversees telecommunications, broadband access, spectrum allocation, and broadcast media compliance."),
            ("Which federal agency regulates the securities markets, enforces federal securities laws, and protects investors from fraudulent market practices?", "Securities and Exchange Commission (SEC)", ["Federal Reserve", "Commodity Futures Trading Commission", "Department of Commerce"], "Established during the New Deal in 1934, the SEC ensures transparency and fair dealing in corporate equities and securities."),
            ("Which federal agency enforces federal consumer protection laws and prevents anti-competitive deceptive business practices?", "Federal Trade Commission (FTC)", ["Department of Commerce", "Small Business Administration", "Consumer Financial Protection Bureau"], "Created in 1914, the FTC protects consumers from unfair practices and reviews corporate mergers for antitrust violations."),
            ("Which independent agency protects human health and the environment by writing and enforcing regulations based on laws passed by Congress?", "Environmental Protection Agency (EPA)", ["Department of the Interior", "Occupational Safety and Health Administration", "Food and Drug Administration"], "Established in 1970 under President Nixon, the EPA monitors air quality, water safety, and hazardous chemical emissions."),
            ("Which agency within the Department of Health and Human Services is responsible for ensuring the safety and efficacy of pharmaceuticals, foods, and medical devices?", "Food and Drug Administration (FDA)", ["Centers for Disease Control and Prevention (CDC)", "National Institutes of Health (NIH)", "Centers for Medicare & Medicaid Services (CMS)"], "The FDA regulates clinical drug approvals, food safety, vaccines, veterinary medicines, and medical devices in the US."),
            ("Which federal agency based in Atlanta, Georgia leads the national effort to prevent, detect, and respond to infectious disease outbreaks?", "Centers for Disease Control and Prevention (CDC)", ["Food and Drug Administration (FDA)", "World Health Organization (WHO)", "National Science Foundation (NSF)"], "The CDC conducts health research, issues public health advisories, and coordinates disease outbreak epidemiology."),
            ("Which civilian intelligence agency is responsible for gathering, processing, and analyzing national security intelligence from foreign sources?", "Central Intelligence Agency (CIA)", ["Federal Bureau of Investigation (FBI)", "National Security Agency (NSA)", "Defense Intelligence Agency (DIA)"], "Created by the National Security Act of 1947, the CIA operates under the Director of National Intelligence to conduct foreign intelligence."),
            ("Which federal law enforcement agency within the Department of Justice investigates domestic federal crimes, terrorism, and counterintelligence?", "Federal Bureau of Investigation (FBI)", ["Central Intelligence Agency (CIA)", "United States Secret Service", "Bureau of Alcohol, Tobacco, Firearms and Explosives"], "The FBI is the principal federal investigative agency with domestic jurisdiction over white-collar crime, organized crime, and espionage."),
            ("Which federal agency within the Department of Homeland Security is responsible for protecting the President, Vice President, and foreign heads of state?", "United States Secret Service", ["Federal Bureau of Investigation (FBI)", "United States Marshals Service", "Customs and Border Protection (CBP)"], "Originally formed in 1865 to suppress counterfeiting, the Secret Service added protective executive security in 1901."),
            ("Which federal law enforcement agency is the oldest in the United States, responsible for federal judicial security, fugitive apprehension, and witness protection?", "United States Marshals Service", ["Federal Bureau of Investigation", "Secret Service", "Postal Inspection Service"], "Created by the Judiciary Act of 1789, the US Marshals protect federal judges, transport prisoners, and execute court warrants."),
            ("What is the primary document that outlines the President\'s proposed federal spending priorities and tax policies for the upcoming fiscal year?", "The President\'s Executive Budget Request", ["The Congressional Budget Resolution", "The National Deficit Statement", "The Treasury Annual Balance Sheet"], "Submitted annually to Congress, the President\'s budget serves as the opening recommendation for congressional budget debates."),
            ("Which nonpartisan legislative agency provides Congress with independent economic forecasts, cost estimates, and budget analyses of proposed bills?", "Congressional Budget Office (CBO)", ["Government Accountability Office (GAO)", "Office of Management and Budget (OMB)", "Federal Reserve Board"], "Established in 1974, the CBO produces nonpartisan 'scores' estimating the budgetary impact of proposed legislation."),
            ("Which independent nonpartisan audit agency, known as the 'congressional watchdog', investigates how the federal government spends taxpayer money?", "Government Accountability Office (GAO)", ["Congressional Budget Office (CBO)", "Office of Management and Budget (OMB)", "Internal Revenue Service (IRS)"], "Headed by the Comptroller General, the GAO conducts performance audits and evaluates executive agency operations for Congress."),
            ("Which executive agency within the Executive Office of the President oversees the implementation of presidential policy and assists in drafting the federal budget?", "Office of Management and Budget (OMB)", ["Congressional Budget Office (CBO)", "Department of the Treasury", "Council of Economic Advisers"], "The OMB is the largest component of the Executive Office of the President, reviewing agency regulations and federal spending."),
            ("What term describes redrawing the boundaries of legislative districts to favor one political party or interest group over another?", "Gerrymandering", ["Reapportionment", "Redistricting", "Filibustering"], "Gerrymandering manipulates district boundaries ('cracking and packing') to give a party an unfair electoral advantage."),
            ("What process adjusts the number of seats each state receives in the House of Representatives based on the results of the decennial census?", "Reapportionment", ["Redistricting", "Gerrymandering", "Direct Election"], "States that gain population gain seats in the House, while states with slower growth or declining population lose seats."),
            ("What is the primary function of the United States Courts of Appeals (Circuit Courts)?", "To review decisions made by federal district courts for legal and procedural errors", ["To conduct original trials with witnesses and juries", "To issue advisory opinions to state legislatures", "To hear international military disputes exclusively"], "The 13 US Courts of Appeals intermediate between federal trial district courts and the Supreme Court."),
            ("How many regional judicial circuits comprise the United States Courts of Appeals system across the nation?", "12 regional circuits (plus the Federal Circuit)", ["10 circuits", "15 circuits", "50 circuits"], "There are 11 numbered regional circuits, the D.C. Circuit, and the nationwide Court of Appeals for the Federal Circuit."),
            ("What is the principal federal trial court where federal criminal and civil lawsuits are originally filed, heard, and decided?", "United States District Court", ["United States Court of Appeals", "Supreme Court of the United States", "United States Claims Court"], "There are 94 federal judicial district courts staffed by federal judges and juries hearing original evidence."),
            ("What order issued by the Supreme Court agrees to hear an appeal from a lower court, requiring the assent of at least four Justices?", "Writ of Certiorari", ["Writ of Mandamus", "Writ of Habeas Corpus", "Subpoena duces tecum"], "Under the 'Rule of Four', if four of the nine Justices vote to grant certiorari, the Supreme Court accepts the case for review."),
            ("What written brief submitted by a non-party with an interest in the outcome of a case is translated as 'friend of the court'?", "Amicus Curiae brief", ["Certiorari petition", "Habeas corpus motion", "Stare decisis memorandum"], "Amicus curiae briefs provide additional legal arguments, empirical data, and policy perspectives to help appellate judges decide cases."),
            ("What legal doctrine obligates courts to follow judicial precedents established by prior rulings on identical legal issues?", "Stare Decisis", ["Habeas Corpus", "Mandamus", "Ultra Vires"], "Stare decisis ('to stand by things decided') ensures legal stability, consistency, and predictability in common law jurisprudence."),
            ("What executive advisory body, chaired by the President, considers national security and foreign policy matters with senior military and cabinet advisors?", "The National Security Council (NSC)", ["The Joint Chiefs of Staff", "The Homeland Security Council", "The Foreign Intelligence Advisory Board"], "Created in 1947, the NSC includes the Vice President, Secretary of State, Secretary of Defense, and National Security Advisor."),
            ("What official register published daily by the federal government contains proposed administrative rules, executive orders, and federal agency notices?", "The Federal Register", ["The Congressional Record", "The United States Code", "The Code of Federal Regulations"], "The Federal Register provides public notice of executive orders, proposed agency rules, and opportunities for public comment.")
        ],
        "Rights & Symbols": [
            ("What historical document signed in 1776 declared the thirteen American colonies to be free and independent states from Great Britain?", "The Declaration of Independence", ["The United States Constitution", "The Articles of Confederation", "The Treaty of Paris"], "Adopted by the Second Continental Congress, the Declaration announced the birth of the sovereign United States."),
            ("What iconic phrase in the Declaration of Independence defines unalienable rights granted to all human beings?", "'Life, Liberty and the pursuit of Happiness'", ["'Life, Liberty and Property'", "'Peace, Order and Good Government'", "'Liberty, Equality and Fraternity'"], "Thomas Jefferson adapted John Locke\'s philosophical concepts to assert universal moral rights belonging to all people."),
            ("What national anthem of the United States was penned by Francis Scott Key during the British bombardment of Fort McHenry in 1814?", "The Star-Spangled Banner", ["America the Beautiful", "God Bless America", "My Country, \'Tis of Thee"], "Written during the War of 1812, Congress officially recognized the Star-Spangled Banner as the national anthem in 1931."),
            ("How many alternating red and white stripes are featured on the official flag of the United States, and what do they symbolize?", "13 stripes, symbolizing the original thirteen British colonies that declared independence", ["15 stripes, symbolizing initial federal territories", "50 stripes, symbolizing modern states", "10 stripes, symbolizing Bill of Rights amendments"], "The flag has 13 horizontal stripes (7 red and 6 white) representing the original 13 American colonies."),
            ("How many white stars are featured on the blue union field of the current flag of the United States, and what do they represent?", "50 stars, representing the fifty individual states of the Union", ["48 stars, representing continental states", "13 stars, representing founding colonies", "52 stars, including territories"], "Each star represents a state; the 50th star for Hawaii was added to the flag on July 4, 1960."),
            ("What monumental copper statue was gifted to the United States by the people of France in 1886 to commemorate the alliance and friendship?", "The Statue of Liberty (Liberty Enlightening the World)", ["The Washington Monument", "The Lincoln Memorial", "The Gateway Arch"], "Designed by Frederic-Auguste Bartholdi with a steel framework by Gustave Eiffel, the statue stands in New York Harbor."),
            ("What sonnet written by poet Emma Lazarus is inscribed on a bronze plaque mounted inside the pedestal of the Statue of Liberty?", "'The New Colossus'", ["'O Captain! My Captain!'", "'Paul Revere\'s Ride'", "'Song of Myself'"], "The poem contains the celebrated line: 'Give me your tired, your poor, your huddled masses yearning to breathe free.'"),
            ("What historic bronze bell in Philadelphia, Pennsylvania features an inscription from Leviticus: 'Proclaim LIBERTY Throughout all the Land'?", "The Liberty Bell", ["The Independence Bell", "The Freedom Chime", "The Centennial Bell"], "Rung to commemorate historic readings of the Declaration of Independence, the bell features its famous iconic crack."),
            ("What majestic bird of prey was chosen by the Continental Congress in 1782 as the national bird and national emblem of the United States?", "The Bald Eagle (Haliaeetus leucocephalus)", ["The Golden Eagle", "The Red-tailed Hawk", "The Wild Turkey"], "The bald eagle appears on the Great Seal of the United States holding an olive branch (peace) and thirteen arrows (defense)."),
            ("What Latin motto appearing on the Great Seal of the United States translates to 'Out of many, one'?", "'E Pluribus Unum'", ["'Novus Ordo Seclorum'", "'Annuit Coeptis'", "'In Deo Speramus'"], "Adopted in 1782, the motto reflects the creation of a single unified nation from thirteen disparate colonies."),
            ("What official motto of the United States was adopted by Congress in 1956 and appears on all United States currency?", "'In God We Trust'", ["'E Pluribus Unum'", "'Liberty and Justice for All'", "'One Nation Under God'"], "President Dwight D. Eisenhower signed legislation establishing 'In God We Trust' as the national motto."),
            ("What patriotic oath of allegiance to the United States flag was first published in 1892 by Francis Bellamy?", "The Pledge of Allegiance", ["The American\'s Creed", "The Oath of Citizenship", "The Constitution Day Salute"], "Schoolchildren recite the pledge: 'I pledge allegiance to the flag of the United States of America, and to the Republic for which it stands...'"),
            ("Which four United States presidents have their 60-foot likenesses carved into the granite face of Mount Rushmore in South Dakota?", "George Washington, Thomas Jefferson, Theodore Roosevelt, and Abraham Lincoln", ["George Washington, John Adams, Abraham Lincoln, and FDR", "Thomas Jefferson, James Madison, Abraham Lincoln, and Ulysses S. Grant", "George Washington, Benjamin Franklin, Abraham Lincoln, and Dwight Eisenhower"], "Sculpted by Gutzon Borglum between 1927 and 1941, the monument commemorates the birth, growth, development, and preservation of the nation."),
            ("Which federal holiday observed on the third Monday of January honors the civil rights leader who advocated nonviolent resistance to racial segregation?", "Martin Luther King Jr. Day", ["Juneteenth", "Civil Rights Day", "Presidential Remembrance Day"], "Signed into law by President Reagan in 1983, the holiday commemorates Dr. King\'s dedication to racial justice and peace."),
            ("Which federal holiday celebrated on June 19 commemorates the emancipation of enslaved African Americans in the United States?", "Juneteenth National Independence Day", ["Emancipation Proclamation Day", "Freedom Day", "Kwanzaa"], "Juneteenth marks June 19, 1865, when Union General Gordon Granger arrived in Galveston, Texas to announce that slavery had ended."),
            ("Which federal holiday observed on the last Monday of May honors members of the United States Armed Forces who died in military service?", "Memorial Day", ["Veterans Day", "Armed Forces Day", "Patriot Day"], "Originating after the Civil War as Decoration Day, Memorial Day honors all American service personnel killed in war."),
            ("Which federal holiday observed annually on November 11 honors all military veterans who have served in the United States Armed Forces?", "Veterans Day", ["Memorial Day", "Armed Forces Day", "Patriot Day"], "Originally celebrated as Armistice Day marking the end of World War I in 1918, it honors all living and deceased military veterans."),
            ("What federal holiday celebrated on the fourth Thursday of November commemorates a 1621 harvest feast shared by Pilgrims and Wampanoag people?", "Thanksgiving Day", ["Columbus Day", "Labor Day", "Presidents\' Day"], "President Abraham Lincoln proclaimed a national day of Thanksgiving in 1863 during the Civil War to foster national unity."),
            ("Which federal holiday observed on the first Monday in September recognizes the American labor movement and contributions of workers?", "Labor Day", ["Workers\' Memorial Day", "Memorial Day", "National Employment Day"], "Created during the late 19th century labor movement, Labor Day became a federal holiday under President Grover Cleveland in 1894."),
            ("Which federal holiday celebrated on the third Monday of February officially honors the birth of George Washington and all US presidents?", "Washington\'s Birthday (Presidents\' Day)", ["Founders\' Day", "Patriots\' Day", "Constitution Day"], "Established by Congress in 1879 to celebrate George Washington\'s birthday (February 22), it colloquially honors all American presidents."),
            ("What federal holiday celebrated on July 4 commemorates the adoption of the Declaration of Independence in 1776?", "Independence Day", ["Constitution Day", "Flag Day", "Liberty Day"], "Celebrated nationwide with parades, civic speeches, and fireworks, July 4 marks the birthday of the American republic."),
            ("What official holiday celebrated on June 14 commemorates the adoption of the Stars and Stripes as the official flag of the United States in 1777?", "Flag Day", ["Independence Day", "Patriot Day", "Civics Day"], "President Woodrow Wilson issued a proclamation establishing June 14 as Flag Day in 1916."),
            ("What holiday celebrated on September 17 commemorates the signing of the United States Constitution in Philadelphia in 1787?", "Constitution Day and Citizenship Day", ["Independence Day", "Bill of Rights Day", "Federalist Day"], "Congress designated September 17 to celebrate the drafting of the Constitution and recognize all naturalized citizens."),
            ("What day celebrated on December 15 commemorates the ratification of the first ten amendments to the United States Constitution in 1791?", "Bill of Rights Day", ["Constitution Day", "Liberty Day", "Civic Rights Day"], "President Franklin D. Roosevelt proclaimed December 15 as Bill of Rights Day in 1941 to celebrate constitutional liberties."),
            ("What is the name of the official presidential guest house located across Pennsylvania Avenue from the White House?", "Blair House", ["Camp David", "Decatur House", "Eisenhower Executive Office"], "Blair House has served as the official presidential guest quarters for foreign heads of state since 1942."),
            ("What is the secluded presidential country retreat located in Catoctin Mountain Park in Frederick County, Maryland?", "Camp David (Naval Support Facility Thurmont)", ["Mount Vernon", "Monticello", "The Hermitage"], "Established by FDR as Shangri-La, Camp David serves as a private presidential retreat and venue for historic diplomatic summits."),
            ("What iconic neoclassical government building with a cast-iron dome houses the United States Senate and House of Representatives in Washington D.C.?", "The United States Capitol", ["The White House", "The Library of Congress", "The Supreme Court Building"], "Situated on Capitol Hill, the Capitol is the meeting place of the legislative branch of the federal government."),
            ("What marble memorial in Washington D.C. features a 19-foot seated statue of Abraham Lincoln looking out over the Reflecting Pool?", "The Lincoln Memorial", ["The Jefferson Memorial", "The Washington Monument", "The FDR Memorial"], "Designed by Henry Bacon, the temple features the text of the Gettysburg Address and Lincoln\'s Second Inaugural Address."),
            ("What 555-foot marble obelisk on the National Mall in Washington D.C. was built to commemorate the first President of the United States?", "The Washington Monument", ["The Jefferson Memorial", "The Lincoln Memorial", "The World War II Memorial"], "Engineered by Robert Mills, it was the tallest structure in the world when completed in 1884."),
            ("What circular neoclassical memorial on the Tidal Basin in Washington D.C. features a bronze statue of the author of the Declaration of Independence?", "The Thomas Jefferson Memorial", ["The Lincoln Memorial", "The Washington Monument", "The Madison Memorial"], "Surrounded by famous Japanese cherry blossom trees, the memorial features engraved excerpts from Jefferson\'s political writings."),
            ("What national military cemetery in Virginia across the Potomac River from Washington D.C. contains the Tomb of the Unknown Soldier?", "Arlington National Cemetery", ["Gettysburg National Cemetery", "Colonial National Historical Cemetery", "Quantico National Cemetery"], "Established on the former plantation of Robert E. Lee during the Civil War, Arlington serves as the final resting place for over 400,000 veterans."),
            ("What memorial in Arlington National Cemetery is guarded 24 hours a day, 365 days a year by elite sentinels of the 3rd US Infantry Regiment (The Old Guard)?", "The Tomb of the Unknown Soldier", ["The Eternal Flame", "The Space Shuttle Challenger Memorial", "The USS Maine Memorial"], "Dedicated in 1921, the tomb honors unidentified American military personnel who made the ultimate sacrifice in wartime."),
            ("What historic gravesite in Arlington National Cemetery features an Eternal Flame lit by Jacqueline Kennedy in 1963?", "Gravesite of President John F. Kennedy", ["Gravesite of General George C. Marshall", "Gravesite of Robert F. Kennedy", "Gravesite of General John J. Pershing"], "The gravesite overlooks Washington D.C., visited by millions of citizens paying tribute to the 35th President."),
            ("What V-shaped black granite reflective memorial in Washington D.C., designed by Maya Lin, is etched with over 58,000 names of fallen service members?", "The Vietnam Veterans Memorial", ["The Korean War Veterans Memorial", "The World War I Memorial", "The National World War II Memorial"], "Unveiled in 1982, the reflective black wall lists names chronologically by date of casualty, creating an intensely moving emotional tribute."),
            ("What memorial on the National Mall consists of 19 stainless steel statues depicting an infantry squad advancing through rice paddies in ponchos?", "The Korean War Veterans Memorial", ["The Vietnam Veterans Memorial", "The World War II Memorial", "The Marine Corps War Memorial"], "The memorial honors service members who fought in the Korean War (1950-1953), bearing the inscription 'Freedom Is Not Free.'"),
            ("What iconic bronze monument in Arlington, Virginia depicts five Marines and a Navy corpsman raising the American flag on Mount Suribachi during WWII?", "The Marine Corps War Memorial (Iwo Jima Memorial)", ["The Navy Memorial", "The National D-Day Memorial", "The Air Force Memorial"], "Sculpted by Felix de Weldon based on Joe Rosenthal\'s Pulitzer Prize-winning photograph, it honors all Marines who gave their lives."),
            ("What is the formal constitutional duty required of every male United States citizen within 30 days of turning 18 years old?", "Register with the Selective Service System", ["Register with a political party", "Obtain a federal passport", "Pay federal property tax"], "Federal law requires virtually all male US citizens and male immigrants residing in the US to register with Selective Service upon turning 18."),
            ("What fundamental civic responsibility is expected of every United States citizen summoned to participate in the judicial trial process?", "Serving on a jury when summoned", ["Running for elected public office", "Writing letters to congressional representatives", "Donating to campaign finance committees"], "Jury service ensures that accused individuals are judged by an impartial community of their peers, upholding constitutional due process."),
            ("What civic obligation requires citizens who earn taxable income above statutory thresholds to file annual returns with the federal government?", "Filing and paying federal income taxes", ["Purchasing municipal bonds", "Volunteering for civil defense duties", "Voting in every state referendum"], "Tax revenue finances national defense, public infrastructure, education, Medicare, Social Security, and federal government services."),
            ("What voluntary civic act is the cornerstone of democratic self-governance in the United States?", "Voting in federal, state, and local elections", ["Serving in the armed forces", "Joining a labor union", "Attending municipal zoning board hearings"], "Voting empowers citizens to elect representatives, shape government policies, and hold political leaders accountable.")
        ]
    }

print("Loaded USA Tests items successfully.")
'''
    with open(target, 'a', encoding='utf-8') as f:
        f.write(additional_code)
    print("Appended USA Tests to data_civics_driving.py")

create_dmv_and_civics_file()
