"""
gen_stem_part2.py
Builds scripts/generators/data_stem_part2.py containing:
- Electronics (150)
- HVAC (150)
- Automotive (150)
"""

import os

content = '''"""
data_stem_part2.py
Contains comprehensive, distinct questions for:
- Electronics (150 questions: 38, 38, 37, 37)
- HVAC (150 questions: 38, 38, 37, 37)
- Automotive (150 questions: 38, 38, 37, 37)
"""

def get_electronics_items():
    return {
        "Semiconductors": [
            ("What is the primary difference between an intrinsic semiconductor and an extrinsic semiconductor?", "Intrinsic is pure undoped crystalline material; extrinsic is doped with donor or acceptor impurity atoms", ["Intrinsic conducts better than metals", "Extrinsic has no valence band", "Intrinsic contains only holes"], "Pure intrinsic silicon has few free charge carriers; doping creates extrinsic N-type or P-type semiconductors."),
            ("What is the energy bandgap of pure crystalline Silicon at room temperature (300 Kelvin)?", "Approximately 1.12 electron-volts (eV)", ["0.67 eV", "3.2 eV", "0.1 eV"], "Silicon's 1.12 eV bandgap provides stable thermal operation up to ~150 C compared to Germanium's 0.67 eV."),
            ("What type of semiconductor is created by doping pure silicon with pentavalent Group V donor atoms like phosphorus or arsenic?", "N-type semiconductor", ["P-type semiconductor", "Intrinsic semiconductor", "Compensated semiconductor"], "Pentavalent atoms donate a fifth loosely bound valence electron, creating abundant mobile conduction-band electrons."),
            ("What type of semiconductor is created by doping pure silicon with trivalent Group III acceptor atoms like boron or gallium?", "P-type semiconductor", ["N-type semiconductor", "Intrinsic semiconductor", "Degenerate semiconductor"], "Trivalent atoms accept electrons, creating mobile positive vacancies (holes) in the valence band."),
            ("What region forms at the metallurgical junction of P-type and N-type silicon where free electrons and holes diffuse and recombine?", "Depletion Region (Space Charge Region)", ["Conduction Channel", "Inversion Layer", "Ohmic Contact"], "Mobile carriers diffuse across the junction, leaving uncompensated ionized donor (+) and acceptor (-) dopant atoms that form an electric field."),
            ("What is the built-in barrier potential across the depletion region of a standard silicon P-N junction diode at room temperature?", "Approximately 0.6 to 0.7 Volts", ["0.2 to 0.3 Volts", "1.5 to 2.0 Volts", "0.0 Volts"], "Forward bias must overcome this internal 0.7V electrostatic barrier before significant diffusion current flows."),
            ("What bias condition is applied to a P-N junction diode when the positive terminal of a voltage source connects to the anode?", "Forward Bias", ["Reverse Bias", "Zero Bias", "Breakdown Bias"], "Forward bias opposes the internal built-in electric field, narrowing the depletion region and allowing exponential current."),
            ("What happens to the depletion region width when a P-N junction diode is subjected to reverse bias?", "The depletion region widens, creating a stronger electric field that blocks major current flow", ["The depletion region collapses to zero", "The depletion region turns into a conductor", "The depletion region emits light photons"], "Reverse bias pulls majority carriers away from the junction, leaving only a tiny nanoampere reverse saturation leakage current."),
            ("What reverse breakdown mechanism occurs in heavily doped P-N junctions at low reverse voltages under 5V via quantum mechanical tunneling?", "Zener Breakdown", ["Avalanche Breakdown", "Thermal Breakdown", "Dielectric Puncture"], "Narrow depletion barriers in heavily doped junctions allow valence electrons to tunnel directly into the conduction band under high electric fields."),
            ("What reverse breakdown mechanism occurs in lightly doped junctions at higher reverse voltages above 6V via carrier impact ionization?", "Avalanche Breakdown", ["Zener Breakdown", "Tunneling Breakdown", "Electroluminescent Breakdown"], "Thermally accelerated electrons gain kinetic energy in the depletion field, knocking valence electrons loose in a cascading avalanche."),
            ("What temperature coefficient characterizes Zener breakdown compared to Avalanche breakdown in voltage regulator diodes?", "Zener breakdown has a negative temperature coefficient while Avalanche has a positive temperature coefficient", ["Both have identical positive coefficients", "Both have zero temperature coefficients", "Zener is positive while Avalanche is negative"], "Diodes rated at ~5.6V combine both mechanisms with opposing temperature coefficients, achieving near-zero temperature drift."),
            ("What parameter defines the small DC current that flows through a reverse-biased diode prior to reaching breakdown?", "Reverse Saturation Current (Is)", ["Forward Knee Current", "Holding Current", "Peak Inverse Current"], "Reverse leakage current is governed by thermal generation of minority carriers in the depletion layer, doubling roughly every 10 C."),
            ("What does the Peak Inverse Voltage (PIV) rating of a semiconductor rectifier diode signify?", "The maximum instantaneous reverse voltage that the diode can withstand without breaking down", ["The forward threshold voltage", "The voltage at peak forward current", "The continuous RMS working voltage"], "Exceeding a diode's PIV rating causes uncontrolled reverse breakdown and catastrophic thermal destruction."),
            ("What wide-bandgap semiconductor material with a bandgap around 3.2 eV is replacing silicon in high-voltage electric vehicle inverters?", "Silicon Carbide (SiC)", ["Gallium Arsenide (GaAs)", "Germanium (Ge)", "Indium Phosphide (InP)"], "SiC offers 10x higher breakdown electric field strength and superior thermal conductivity, slashing switching losses in EV inverters."),
            ("What high-electron-mobility wide-bandgap semiconductor with a bandgap around 3.4 eV dominates high-frequency RF power amplifiers and compact fast chargers?", "Gallium Nitride (GaN)", ["Silicon Carbide", "Silicon", "Germanium"], "GaN transistors achieve high electron saturation velocity and low on-resistance, enabling compact, high-efficiency power converters."),
            ("What term describes the ratio of collector current to base current in a Bipolar Junction Transistor common-emitter configuration?", "DC Current Gain (Beta or hFE)", ["Alpha", "Transconductance (gm)", "Amplification Factor"], "Beta (hFE) typically ranges from 50 to 300 in small-signal BJTs, defining how much small base current controls collector output current."),
            ("What operational state of a BJT occurs when both the base-emitter and base-collector junctions are forward-biased?", "Saturation Region", ["Cutoff Region", "Active (Linear) Region", "Breakdown Region"], "In saturation, collector-emitter voltage drops to its minimum (VCE(sat) ~0.1 to 0.2V), conducting maximum collector load current."),
            ("What operational state of a BJT occurs when the base-emitter junction is reverse-biased, resulting in virtually zero collector current?", "Cutoff Region", ["Saturation Region", "Active Region", "Ohmic Region"], "In cutoff, collector current is virtually zero, acting like an open mechanical switch contact."),
            ("In what BJT operating region is the base-emitter junction forward-biased and the base-collector junction reverse-biased?", "Active (Linear) Region", ["Saturation Region", "Cutoff Region", "Inverted Region"], "In the active region, small changes in base current produce proportional linear changes in collector current."),
            ("What fundamental equation relates BJT collector current to base-emitter voltage?", "Ebers-Moll Equation", ["Ohm's Law", "Einstein Relation", "Poisson Equation"], "The exponential relationship demonstrates that a tiny increase in VBE produces a massive exponential surge in collector current."),
            ("What thermal hazard occurs in BJTs when rising temperature increases collector current, which in turn generates more destructive heat?", "Thermal Runaway", ["Second Breakdown", "Punch-Through", "Avalanche Multiplication"], "BJTs have a negative temperature coefficient of VBE; without emitter degeneration resistors, self-heating causes destructive current runaway."),
            ("What type of Field-Effect Transistor utilizes a reverse-biased P-N junction to modulate the width of a conducting channel?", "Junction Field-Effect Transistor (JFET)", ["MOSFET", "IGBT", "HEMT"], "JFETs are depletion-mode devices; applying reverse bias to the Gate narrows the channel, pinching off current at the pinch-off voltage."),
            ("What type of MOSFET is normally off at zero gate voltage and requires positive gate-to-source voltage to conduct?", "Enhancement-Mode MOSFET", ["Depletion-Mode MOSFET", "JFET", "MESFET"], "Enhancement-mode N-channel MOSFETs are the universal standard for modern digital logic (CMOS) and power switching."),
            ("What type of MOSFET possesses a doped conducting channel that conducts at zero gate voltage and requires negative voltage to turn off?", "Depletion-Mode MOSFET", ["Enhancement-Mode MOSFET", "BJT", "IGBT"], "Depletion-mode MOSFETs are normally on at VGS = 0, useful in current sources and startup circuits."),
            ("What crucial MOSFET parameter defines the minimum gate-to-source voltage required to create the conducting channel inversion layer?", "Gate Threshold Voltage (VGS(th))", ["Pinch-Off Voltage", "Breakdown Voltage", "Saturation Voltage"], "VGS must exceed threshold voltage (typically 1-3V for logic-level, 3-5V for standard power FETs) to turn the device on."),
            ("What parameter defines the internal electrical resistance between Drain and Source when a power MOSFET is fully turned on?", "Drain-Source On-Resistance (RDS(on))", ["Transconductance", "Gate Resistance", "Drain Leakage"], "Low RDS(on) (often single-digit milliohms) minimizes conduction heat losses in high-efficiency switching power supplies."),
            ("Why do power MOSFETs naturally share current equally when placed in parallel?", "As MOSFET junction temperature rises, RDS(on) increases, naturally balancing and sharing current equally", ["MOSFETs have built-in cooling fans", "Parallel MOSFETs fuse together", "MOSFETs switch to bipolar mode at high heat"], "Unlike BJTs, parallel MOSFETs self-stabilize: hotter devices develop higher resistance, shunting current to cooler parallel FETs."),
            ("What parasitic component exists inside every power MOSFET between Drain and Source due to its silicon substrate construction?", "Body Diode (Intrinsic Anti-Parallel Diode)", ["Parasitic BJT only", "Internal Zener Diode", "Schottky Barrier"], "The integral body diode conducts reverse freewheeling current in H-bridge inverters, but exhibits slow reverse recovery time."),
            ("What phenomenon in CMOS integrated circuits occurs when parasitic bipolar structures trigger an unintended low-impedance short circuit?", "CMOS Latch-Up", ["Thermal Runaway", "Electromigration", "Oxide Breakdown"], "Voltage spikes or radiation can trigger parasitic thyristor latch-up across VDD and GND, burning out the chip unless power is removed."),
            ("What progressive failure mechanism occurs in microchip metal traces when high current density physically displaces metal atoms?", "Electromigration", ["Latch-Up", "Dielectric Breakdown", "Hot Carrier Injection"], "Over years, electromigration creates microscopic voids or metal whiskers inside sub-micron silicon chips."),
            ("What degradation phenomenon in submicron MOSFETs occurs when electrons accelerated by electric fields become trapped in gate oxide?", "Hot Carrier Injection (HCI)", ["Dielectric Breakdown", "Electromigration", "Negative Bias Instability"], "Trapped energetic electrons permanently shift gate threshold voltage and degrade transconductance over the operational lifetime of the CPU."),
            ("What high-frequency effect describes the unwanted capacitive multiplication between the input and output terminals of an inverting amplifier?", "Miller Effect", ["Early Effect", "Barkhausen Criterion", "Skin Effect"], "The Miller effect multiplies feedback capacitance by amplifier voltage gain, restricting high-frequency bandwidth."),
            ("What logic circuit technology pairs N-channel and P-channel MOSFETs to achieve virtually zero static power consumption?", "CMOS (Complementary Metal-Oxide-Semiconductor)", ["TTL", "ECL", "NMOS Logic"], "In CMOS gates, one transistor is always off when the other is on, drawing current only dynamically during switching transitions."),
            ("What legacy bipolar digital logic family, introduced with the 7400 series, utilized multi-emitter input transistors and 5V DC?", "Transistor-Transistor Logic (TTL)", ["CMOS", "ECL", "RTL"], "Standard TTL defined logic low as 0 to 0.8V and logic high as 2.0 to 5.0V, dominating early digital computers."),
            ("What ultra-fast bipolar logic family operates transistors strictly in the active region to eliminate saturation storage delay?", "Emitter-Coupled Logic (ECL)", ["TTL", "CMOS", "I2L"], "ECL avoids saturation delays by using differential pairs, used in early supercomputers like Cray-1."),
            ("What semiconductor component consists of two antiparallel SCRs sharing a single gate to control AC power bidirectionally?", "TRIAC", ["DIAC", "IGBT", "Darlington Pair"], "TRIACs conduct across both positive and negative AC half-cycles, ubiquitous in domestic fan speed regulators and light dimmers."),
            ("What two-terminal semiconductor device triggers at a specific breakover voltage without a gate terminal, used to trigger TRIACs?", "DIAC", ["Zener Diode", "Tunnel Diode", "Varistor"], "DIACs conduct when voltage across them reaches ~30V in either polarity, delivering a sharp gate pulse to trigger a TRIAC."),
            ("What power device combines an isolated MOS gate with a bipolar output, standardly used in high-voltage industrial motor drives above 600V?", "Insulated Gate Bipolar Transistor (IGBT)", ["Power MOSFET", "Darlington Transistor", "JFET"], "IGBTs eliminate high gate drive current while avoiding the high on-resistance penalty that limits silicon power MOSFETs above 600V.")
        ],
        "Digital Logic": [
            ("What fundamental logic gate produces an output of binary 1 if and only if ALL of its inputs are binary 1?", "AND Gate", ["OR Gate", "XOR Gate", "NAND Gate"], "The AND gate performs logical conjunction: output Y = A * B. Output is 0 if any input is 0."),
            ("What logic gate produces an output of binary 1 if AT LEAST ONE of its inputs is binary 1?", "OR Gate", ["AND Gate", "NOR Gate", "XNOR Gate"], "The OR gate performs logical disjunction: output Y = A + B. Output is 0 only when all inputs are 0."),
            ("What single-input logic gate inverts a binary signal so that 1 becomes 0 and 0 becomes 1?", "NOT Gate (Inverter)", ["Buffer", "AND Gate", "XOR Gate"], "The inverter negates input logic: output Y = NOT A."),
            ("What logic gate produces an output of binary 0 only when ALL of its inputs are binary 1?", "NAND Gate", ["NOR Gate", "AND Gate", "XOR Gate"], "NAND performs negated conjunction: Y = NOT(A * B). It is a universal gate capable of creating all other logic functions."),
            ("What logic gate produces an output of binary 1 only when ALL of its inputs are binary 0?", "NOR Gate", ["NAND Gate", "OR Gate", "XNOR Gate"], "NOR performs negated disjunction: Y = NOT(A + B). Like NAND, NOR is a universal logic gate."),
            ("What logic gate produces an output of binary 1 when its inputs are DIFFERENT from each other, and 0 when they match?", "XOR Gate (Exclusive-OR)", ["XNOR Gate", "OR Gate", "AND Gate"], "XOR outputs 1 if either A or B is 1, but not both, essential for binary adders and parity checkers."),
            ("What logic gate produces an output of binary 1 when its inputs are IDENTICAL, acting as an equivalence detector?", "XNOR Gate (Exclusive-NOR)", ["XOR Gate", "NAND Gate", "NOR Gate"], "XNOR outputs 1 when inputs match (both 0 or both 1), functioning as a digital magnitude comparator."),
            ("Why are NAND and NOR gates classified as universal logic gates?", "Any Boolean logic function can be constructed using exclusively NAND or exclusively NOR gates", ["They operate on any voltage level", "They have infinite inputs", "They do not require power"], "Functional completeness proves that inverter, AND, and OR functions can be synthesized entirely from networked NAND or NOR gates."),
            ("What Boolean theorem states that the complement of a product equals the sum of the complements: NOT(A * B) = NOT A + NOT B?", "De Morgan's First Law", ["De Morgan's Second Law", "Shannon's Expansion Theorem", "Boole's Identity"], "De Morgan's laws allow engineers to convert between AND/OR gates by bubbling inputs and outputs."),
            ("What Boolean theorem states that the complement of a sum equals the product of the complements: NOT(A + B) = NOT A * NOT B?", "De Morgan's Second Law", ["De Morgan's First Law", "Consensus Theorem", "Absorption Law"], "De Morgan's second law enables engineers to replace NOR operations with active-low input AND gates."),
            ("What graphical method uses a 2D grid with Gray code coordinates to simplify Boolean algebraic expressions?", "Karnaugh Map (K-Map)", ["Truth Table", "State Diagram", "Venn Diagram"], "K-Maps group adjacent 1s into powers of two (1, 2, 4, 8, 16) to find minimal sum-of-products Boolean expressions."),
            ("What digital arithmetic circuit adds two single-bit binary inputs to produce a Sum bit and a Carry bit?", "Half Adder", ["Full Adder", "Binary Multiplier", "ALU"], "A half adder utilizes an XOR gate to generate Sum and an AND gate to generate Carry."),
            ("What digital circuit adds three single binary bits (two operand bits plus an incoming carry bit)?", "Full Adder", ["Half Adder", "Ripple Carry Adder", "Digital Comparator"], "A full adder consists of two half adders and an OR gate, generating Sum and Carry-out."),
            ("What type of multi-bit binary adder chains full adders in series where each stage's carry feeds into the next?", "Ripple Carry Adder", ["Carry-Lookahead Adder", "Carry-Save Adder", "Carry-Skip Adder"], "Ripple carry adders are simple but slow because carry propagation ripples through all stages from LSB to MSB."),
            ("What advanced binary adder computes all carry bits simultaneously in parallel using generate and propagate logic?", "Carry-Lookahead Adder (CLA)", ["Ripple Carry Adder", "Serial Adder", "Manchester Adder"], "CLA circuits compute carry bits in constant time using generate and propagate terms, eliminating ripple delay."),
            ("What combinational circuit selects binary data from one of multiple input channels and routes it to a single output line?", "Multiplexer (MUX)", ["Demultiplexer (DEMUX)", "Decoder", "Encoder"], "A 4-to-1 MUX utilizes two binary select lines to connect one of four input lines to the output."),
            ("What combinational circuit takes a single input data line and routes it to one of multiple output lines based on select lines?", "Demultiplexer (DEMUX)", ["Multiplexer", "Encoder", "Shift Register"], "A DEMUX distributes a single serial data line into selected parallel destination lines."),
            ("What digital circuit converts an n-bit binary input code into a maximum of 2^n unique active output lines?", "Binary Decoder", ["Encoder", "Multiplexer", "Comparator"], "Decoders activate one specific output line corresponding to the binary value applied to input address lines."),
            ("What specialized decoder converts a 4-bit Binary Coded Decimal number into signals for a 7-segment display?", "BCD to 7-Segment Decoder (e.g., 7447)", ["Priority Encoder", "Gray Code Converter", "Parity Generator"], "The 7447 decoder maps digits 0-9 to control display segments a through g."),
            ("What combinational circuit converts multiple input lines into an encoded binary output word?", "Binary Encoder", ["Decoder", "Multiplexer", "Flip-Flop"], "An 8-to-3 encoder outputs a 3-bit binary word representing whichever one of eight input lines is active."),
            ("What specialized encoder outputs the binary code of the highest-order active input, ignoring all lower active inputs?", "Priority Encoder", ["Standard Binary Encoder", "Decoder", "Transcoder"], "Priority encoders manage microprocessor hardware interrupt requests, servicing the highest-priority interrupt first."),
            ("What is the fundamental difference between combinational logic and sequential logic circuits?", "Combinational output depends only on current inputs, while sequential output depends on current inputs and past states (memory)", ["Combinational uses clock pulses while sequential does not", "Sequential logic has no feedback loops", "Combinational circuits contain flip-flops"], "Sequential circuits contain feedback loops and memory elements (latches, flip-flops) that store state information."),
            ("What is the simplest asynchronous bistable sequential memory element constructed from two cross-coupled NOR or NAND gates?", "SR Latch", ["D Flip-Flop", "Shift Register", "Binary Counter"], "An SR latch stores one binary bit; pulsing Set forces Q=1, pulsing Reset forces Q=0, while S=R=1 is invalid."),
            ("Why is the input condition S = 1 and R = 1 considered invalid in a basic NOR SR latch?", "It forces both Q and NOT-Q to 0 simultaneously and produces an unpredictable race condition upon release", ["It burns out the transistors", "It short-circuits the power supply", "It causes the clock to stop"], "Violating the complementary definition Q != NOT-Q leads to metastable racing when inputs transition to 0."),
            ("What sequential flip-flop eliminates invalid states by transferring its single Data input to Q on the active clock edge?", "D Flip-Flop", ["SR Flip-Flop", "T Flip-Flop", "JK Flip-Flop"], "D flip-flops sample input D on clock edges and hold it, forming the foundation of CPU registers."),
            ("What sequential flip-flop toggles its output state when both inputs are binary 1 on an active clock edge?", "JK Flip-Flop", ["D Flip-Flop", "SR Latch", "Schmitt Trigger"], "Named after Jack Kilby, a JK flip-flop toggles when J=K=1, functioning as a frequency divider."),
            ("What single-input sequential flip-flop toggles its output between 0 and 1 on every clock pulse when its input is HIGH?", "T Flip-Flop (Toggle Flip-Flop)", ["D Flip-Flop", "SR Latch", "Monostable Multivibrator"], "T flip-flops divide incoming clock frequency exactly in half, forming binary counters."),
            ("What timing parameter defines the minimum time that input data must remain stable BEFORE the active clock edge arrives?", "Setup Time (t_setup)", ["Hold Time (t_hold)", "Propagation Delay", "Clock Skew"], "Violating setup time prevents internal latch circuits from settling, triggering dangerous flip-flop metastability."),
            ("What timing parameter defines the minimum time that input data must remain stable AFTER the active clock edge arrives?", "Hold Time (t_hold)", ["Setup Time", "Fall Time", "Jitter"], "Data must be held steady for t_hold after the clock transition to ensure positive latching."),
            ("What dangerous condition occurs when setup or hold times are violated, causing a flip-flop output to hover between 0 and 1?", "Metastability", ["Thermal Runaway", "Clock Jitter", "Ground Bounce"], "A metastable flip-flop hovers in an intermediate voltage state before randomly collapsing, causing unpredictable system crashes."),
            ("What digital sequential circuit consists of cascading flip-flops used to move binary bits laterally with each clock pulse?", "Shift Register", ["Ripple Counter", "Multiplexer", "ALU"], "Shift registers operate in serial and parallel modes to buffer, delay, and convert data formats."),
            ("What shift register configuration accepts binary data serially and outputs all bits simultaneously in parallel?", "Serial-In Parallel-Out (SIPO)", ["Parallel-In Serial-Out (PISO)", "Serial-In Serial-Out (SISO)", "Parallel-In Parallel-Out (PIPO)"], "SIPO shift registers like the 74HC595 expand microcontroller I/O pins, driving displays and LED arrays efficiently."),
            ("What type of digital counter has all of its flip-flop clock inputs triggered simultaneously by a common clock?", "Synchronous Counter", ["Asynchronous (Ripple) Counter", "Johnson Counter", "Decade Counter"], "Synchronous counters eliminate ripple propagation delays because all state flip-flops trigger at the exact same instant."),
            ("What type of digital counter connects the output of each flip-flop to clock the succeeding flip-flop in cascade?", "Asynchronous Counter (Ripple Counter)", ["Synchronous Counter", "Ring Counter", "Parallel Counter"], "In ripple counters, clock pulses ripple down the chain, accumulating propagation delay."),
            ("What digital counter cycles through ten binary states from 0000 to 1001 before resetting back to zero on the tenth count?", "Decade Counter (BCD Counter)", ["Modulo-16 Counter", "Johnson Counter", "Gray Code Counter"], "Decade counters reset upon reaching 1010, widely utilized in digital clocks and frequency counters."),
            ("What binary unweighted encoding system changes only one single bit between successive counts, eliminating transitional errors?", "Gray Code", ["Standard Binary", "Binary Coded Decimal (BCD)", "Excess-3 Code"], "In optical rotary shaft encoders, Gray code prevents multi-bit misreadings when physical sensors cross adjacent sectors."),
            ("What digital circuit compares two n-bit binary numbers and indicates whether the first is greater than, less than, or equal to the second?", "Digital Magnitude Comparator", ["Binary Full Adder", "Parity Checker", "Priority Encoder"], "Comparators evaluate binary words bit-by-bit from MSB to LSB to determine magnitude relationship."),
            ("What circuit uses positive feedback to introduce electrical hysteresis, turning noisy analog signals into sharp digital square waves?", "Schmitt Trigger", ["Operational Amplifier", "Monostable Multivibrator", "Peak Detector"], "Schmitt triggers have separate high and low switching threshold voltages, eliminating false triggering caused by noise.")
        ],
        "Microcontrollers": [
            ("What is the primary architectural difference between Harvard architecture and Von Neumann architecture in microcontrollers?", "Harvard has separate memory buses for program instructions and data, while Von Neumann shares a single memory bus", ["Harvard has no RAM", "Von Neumann has separate instruction caches only", "Harvard cannot execute C code"], "Harvard architecture allows simultaneous fetching of instructions and data, doubling throughput in microcontrollers like PIC and AVR."),
            ("What type of memory in a modern microcontroller retains program code non-volatiles when power is removed and can be electrically erased in blocks?", "Flash Memory", ["SRAM", "DRAM", "Mask ROM"], "Flash memory stores the executable firmware, surviving power cycles and supporting in-system reprogramming."),
            ("What type of fast static memory in a microcontroller provides volatile storage for runtime variables and stack frames?", "Static RAM (SRAM)", ["Flash Memory", "EEPROM", "ROM"], "SRAM uses 6-transistor cross-coupled inverters per bit, requiring no refresh cycles and providing single-cycle read/write access."),
            ("What internal hardware timer in a microcontroller resets the system if software hangs or enters an infinite loop?", "Watchdog Timer (WDT)", ["Real-Time Clock (RTC)", "PWM Generator", "Baud Rate Generator"], "Firmware must periodically clear or 'kick' the watchdog timer; if software crashes, the WDT times out and triggers a hardware reset."),
            ("What hardware signal suspends the CPU's current execution thread to immediately service an urgent asynchronous hardware event?", "Interrupt Request (IRQ)", ["Polling Loop", "Direct Memory Access", "Trapdoor Call"], "When an interrupt occurs, the CPU saves its program counter and status register to the stack and jumps to an Interrupt Service Routine (ISR)."),
            ("What table in microcontroller program memory stores the memory addresses of all Interrupt Service Routines?", "Interrupt Vector Table (IVT)", ["Look-Up Table", "Stack Pointer Table", "Symbol Table"], "Hardware indexes into the IVT upon an interrupt, executing the handler code mapped to that specific hardware event."),
            ("What microcontroller peripheral converts continuous real-world analog sensor voltages into discrete digital numbers?", "Analog-to-Digital Converter (ADC)", ["Digital-to-Analog Converter (DAC)", "Comparator", "PWM Module"], "A 10-bit ADC translates an analog voltage (0-5V) into a digital integer from 0 to 1023 (2^10 steps)."),
            ("What common ADC architecture uses a binary search algorithm with an internal DAC to convert analog voltages quickly?", "Successive Approximation Register (SAR) ADC", ["Flash ADC", "Delta-Sigma ADC", "Dual-Slope ADC"], "SAR ADCs determine one bit per clock cycle from MSB to LSB, balancing high conversion speed, low cost, and good resolution."),
            ("What ultra-fast ADC architecture uses a bank of 2^n - 1 parallel comparators to complete a conversion in a single clock cycle?", "Flash ADC", ["SAR ADC", "Pipeline ADC", "Delta-Sigma ADC"], "Flash ADCs achieve gigasample-per-second speeds in digital oscilloscopes and radar, but consume substantial power."),
            ("What peripheral technique modulates the duty cycle of a fixed-frequency digital square wave to control DC motor speed or LED brightness?", "Pulse-Width Modulation (PWM)", ["Frequency Modulation", "Amplitude Modulation", "Phase Modulation"], "A 50% duty cycle delivers half the average DC voltage to the load, providing highly efficient power control with minimal heat dissipation."),
            ("What synchronous serial communication protocol utilizes four wires: MOSI, MISO, SCK, and SS (Chip Select)?", "SPI (Serial Peripheral Interface)", ["I2C", "UART", "CAN Bus"], "SPI supports full-duplex high-speed data transfers (tens of megahertz) between a master microcontroller and slave peripherals."),
            ("What two-wire synchronous serial communication bus uses open-drain lines (SDA and SCL) with external pull-up resistors?", "I2C (Inter-Integrated Circuit)", ["SPI", "UART", "RS-485"], "I2C addresses up to 127 devices on just two physical wires, standardly running at 100 kHz (standard) or 400 kHz (fast mode)."),
            ("What asynchronous serial communication interface transmits data without a shared clock line using start, data, parity, and stop bits?", "UART (Universal Asynchronous Receiver-Transmitter)", ["SPI", "I2C", "CAN"], "Both transmitting and receiving UARTs must agree in advance on a matching baud rate (e.g., 9600, 115200 bps)."),
            ("What differential serial bus protocol, developed by Bosch, provides robust fault-tolerant communication in automotive vehicle networks?", "CAN Bus (Controller Area Network)", ["LIN Bus", "Modbus", "SPI"], "CAN uses differential signaling (CAN_H and CAN_L) and non-destructive bitwise arbitration, resisting electromagnetic interference."),
            ("What hardware feature enables high-speed peripheral data transfer directly into microcontroller RAM without involving the CPU core?", "Direct Memory Access (DMA)", ["Interrupt Controller", "Watchdog Timer", "Bus Arbiter"], "DMA transfers data buffers (e.g., ADC readings, audio samples, SPI transfers) in the background while the CPU executes other code."),
            ("What low-power microcontroller operating mode stops the CPU core clock while keeping RAM, registers, and external interrupts active?", "Sleep / Standby Mode", ["Deep Power-Down Mode", "Reset Mode", "Brown-Out Mode"], "Microcontrollers enter sleep mode to reduce power consumption to microamps, waking rapidly when a sensor interrupt triggers."),
            ("What internal safety circuit forces a microcontroller into reset when the supply voltage drops below the minimum reliable operating threshold?", "Brown-Out Detector (BOD)", ["Watchdog Timer", "Power-On Reset (POR)", "Crystal Oscillator"], "Brown-out detection prevents the microcontroller from corrupting Flash/EEPROM or executing invalid opcodes under decaying battery voltage."),
            ("What type of memory pointer register in a microcontroller holds the return address and saved register states during function calls and interrupts?", "Stack Pointer (SP)", ["Program Counter (PC)", "Accumulator", "Status Register"], "The Stack Pointer points to the current top of the stack in SRAM, decrementing or incrementing with push and pop operations."),
            ("What CPU register holds the memory address of the next machine instruction to be fetched, decoded, and executed?", "Program Counter (PC)", ["Instruction Register (IR)", "Stack Pointer (SP)", "Memory Address Register"], "The Program Counter increments automatically after each instruction fetch, unless altered by branch, jump, or call instructions."),
            ("What RISC microcontroller core family, designed by ARM, dominates modern 32-bit embedded systems and automotive controllers?", "ARM Cortex-M (M0, M3, M4, M7)", ["ARM Cortex-A", "Intel x86", "MIPS32"], "Cortex-M cores offer deterministic low-latency interrupt handling, hardware division, and optional floating-point units (FPU)."),
            ("What open-source processor instruction set architecture (ISA), based on RISC principles, is rapidly gaining adoption in embedded microcontrollers?", "RISC-V", ["x86", "SPARC", "PowerPC"], "RISC-V is a royalty-free, open standard instruction set that allows developers to design custom silicon cores without licensing fees."),
            ("What register inside a GPIO peripheral controls whether a specific physical microcontroller pin functions as an input or an output?", "Data Direction Register (DDR or MODER)", ["Pin State Register", "Pull-Up Register", "Output Latch Register"], "Setting a bit in DDR to 1 configures the corresponding pin as an output, while setting it to 0 configures it as a high-impedance input."),
            ("What type of internal resistor can be programmatically connected to a microcontroller GPIO pin to prevent it from floating when unconnected?", "Internal Pull-Up (or Pull-Down) Resistor", ["Shunt Resistor", "Damping Resistor", "Bleeder Resistor"], "Pull-up resistors hold the input line at a solid logic HIGH (e.g., 3.3V) when an external mechanical pushbutton is open."),
            ("What microcontroller peripheral generates an interrupt or pulse width output based on counting external digital pulses or internal clock cycles?", "Hardware Timer/Counter", ["Comparator", "Baud Rate Generator", "DAC"], "Timers can run in input capture mode (measuring pulse width) or output compare mode (generating precise PWM waveforms)."),
            ("What internal hardware peripheral generates an analog voltage output from a digital binary word without requiring PWM filtering?", "Digital-to-Analog Converter (DAC)", ["ADC", "Comparator", "Charge Pump"], "A DAC outputs a true analog DC voltage, utilized for audio waveform synthesis and precise reference voltage generation."),
            ("What microcontroller debugging interface utilizes standard 4-wire or 5-wire boundary scan hardware to program and debug chips in-circuit?", "JTAG (IEEE 1149.1)", ["UART", "I2C", "SPI"], "JTAG provides hardware breakpoints, single-stepping, and register inspection directly inside the target silicon core."),
            ("What 2-wire debugging protocol, developed by ARM as an alternative to JTAG, uses only SWDIO and SWCLK lines?", "Serial Wire Debug (SWD)", ["JTAG", "ICSP", "BDM"], "SWD provides the full debugging capabilities of JTAG while saving pin count on small-pinout microcontrollers."),
            ("What is the primary function of a crystal oscillator circuit connected to a microcontroller's XTAL pins?", "To provide a precise, stable master clock reference signal for CPU timing and peripheral synchronization", ["To filter electrical noise from the power supply", "To generate high-voltage programming pulses", "To store configuration bits"], "Quartz crystal resonators vibrate at a fixed resonant frequency with high temperature stability (ppm precision)."),
            ("What register in a microcontroller CPU reflects the outcome of arithmetic operations (zero, carry, overflow, negative flags)?", "Status Register (Condition Code Register / Flags Register)", ["Accumulator", "Program Counter", "Stack Pointer"], "Branch instructions evaluate status flags (Z, C, V, N) to make decisions like branching if equal or branching if greater than."),
            ("What embedded programming technique avoids blocking delays by maintaining a state variable that updates inside an event loop?", "Finite State Machine (FSM)", ["Busy-Wait Loop", "Recursive Descent", "Polling Delay"], "FSMs allow cooperative multi-tasking without an operating system, ensuring the microcontroller remains responsive to sensor inputs."),
            ("What real-time software layer provides preemptive multitasking, task scheduling, and inter-task communication in embedded systems?", "Real-Time Operating System (RTOS, e.g., FreeRTOS)", ["Linux Kernel", "BIOS", "Compiler"], "An RTOS switches tasks based on priority, ensuring time-critical tasks meet strict deterministic execution deadlines."),
            ("What synchronization mechanism in an RTOS is used to protect a shared peripheral or resource from simultaneous concurrent access by multiple tasks?", "Mutex (Mutual Exclusion Semaphore)", ["Timer", "Queue", "Event Flag"], "A mutex grants exclusive ownership to one task at a time, preventing data corruption during shared memory access."),
            ("What dangerous scheduling anomaly occurs when a low-priority task holding a mutex blocks a high-priority task because a medium task pre-empts it?", "Priority Inversion", ["Deadlock", "Race Condition", "Starvation"], "Priority inheritance protocols temporarily elevate the low-priority task's priority so it quickly finishes and releases the shared resource."),
            ("What RTOS communication construct allows tasks to safely pass data packets or messages to one another in first-in, first-out order?", "Message Queue", ["Binary Semaphore", "Spinlock", "Interrupt Vector"], "Message queues provide thread-safe FIFO buffering between data producers (like ISRs) and consumer tasks."),
            ("What hardware timer in battery-powered microcontrollers continues counting seconds, minutes, hours, and calendar dates using a 32.768 kHz crystal?", "Real-Time Clock (RTC)", ["Watchdog Timer", "SysTick Timer", "PWM Timer"], "32.768 kHz equals 2^15 cycles per second, enabling a simple 15-stage binary counter to produce an exact 1-second pulse."),
            ("What system timer in ARM Cortex-M microcontrollers provides a dedicated 24-bit down-counter for generating RTOS periodic scheduling ticks?", "SysTick Timer", ["Watchdog Timer", "RTC", "General-Purpose Timer 1"], "SysTick is integrated directly into the Cortex-M core, ensuring code portability across different chip manufacturers."),
            ("What hardware peripheral on modern microcontrollers performs single-cycle hardware multiplication and division for DSP algorithms?", "Hardware Multiplier / MAC (Multiply-Accumulate Unit)", ["ALU Shift Register", "Barrel Shifter", "DMA Controller"], "MAC units execute operations like A = A + (B * C) in a single cycle, accelerating digital audio filters and motor vector control.")
        ],
        "Amplifiers & Filters": [
            ("What are the two golden rules for analyzing an ideal operational amplifier operating with negative feedback?", "The differential input voltage is zero (V+ = V-), and input terminals draw zero electrical current (infinite input impedance)", ["The output voltage is zero and gain is zero", "Both inputs are connected to ground directly", "Feedback is always positive and bandwidth is infinite"], "Because open-loop gain is infinite and input impedance is infinite, negative feedback forces the inputs to identical voltages without drawing current."),
            ("What is the theoretical voltage gain formula for an ideal inverting operational amplifier circuit?", "Gain = -Rf / Rin", ["Gain = 1 + (Rf / Rin)", "Gain = Rin / Rf", "Gain = -Rin / Rf"], "The input resistor Rin and feedback resistor Rf form an inverting amplifier where output voltage Vout = -(Rf / Rin) * Vin."),
            ("What is the theoretical voltage gain formula for an ideal non-inverting operational amplifier circuit?", "Gain = 1 + (Rf / Rin)", ["Gain = -Rf / Rin", "Gain = Rf / Rin", "Gain = 1 - (Rf / Rin)"], "The non-inverting amplifier applies input directly to the non-inverting terminal, producing in-phase gain that is always greater than or equal to 1."),
            ("What operational amplifier configuration connects the output directly to the inverting input, delivering unity gain (Gain = 1)?", "Voltage Follower (Buffer)", ["Inverting Amplifier", "Integrator", "Differentiator"], "A voltage follower provides unity voltage gain with very high input impedance and very low output impedance, preventing loading of sensitive sensors."),
            ("What op-amp circuit produces an output voltage that is proportional to the mathematical time integral of the input voltage?", "Op-Amp Integrator", ["Op-Amp Differentiator", "Summing Amplifier", "Logarithmic Amplifier"], "An integrator replaces the feedback resistor with a capacitor, yielding Vout = -(1 / RC) * integral(Vin dt)."),
            ("What op-amp circuit produces an output voltage proportional to the time derivative (rate of change) of the input voltage?", "Op-Amp Differentiator", ["Op-Amp Integrator", "Comparator", "Peak Detector"], "A differentiator places a capacitor at the input and a resistor in the feedback path, yielding Vout = -RC * (dVin / dt)."),
            ("What parameter defines the maximum rate of change of an operational amplifier's output voltage, measured in Volts per microsecond (V/us)?", "Slew Rate", ["Gain-Bandwidth Product", "Common-Mode Rejection Ratio", "Input Offset Voltage"], "If an input signal's frequency or amplitude demands a faster voltage rise than the op-amp's slew rate can provide, output distortion and triangular distortion occur."),
            ("What figure of merit quantifies an operational amplifier's ability to reject identical noise signals present on both input terminals simultaneously?", "Common-Mode Rejection Ratio (CMRR)", ["Power Supply Rejection Ratio (PSRR)", "Slew Rate", "Open-Loop Gain"], "CMRR is the ratio of differential gain to common-mode gain, expressed in decibels (typically 80 to 120 dB in quality op-amps)."),
            ("What small DC error voltage must be applied between op-amp inputs to force the output voltage exactly to zero?", "Input Offset Voltage (Vos)", ["Input Bias Current", "Thermal Drift", "Hysteresis Voltage"], "Imperfect matching between input differential pair transistors causes slight offset voltage, typically tens of microvolts to a few millivolts."),
            ("What op-amp parameter states that the product of open-loop voltage gain and operating frequency remains constant across its linear range?", "Gain-Bandwidth Product (GBWP)", ["Slew Rate", "Unity-Gain Crossover", "Transit Frequency"], "If an op-amp has a GBWP of 10 MHz, an amplifier configured for a gain of 10 will have a maximum bandwidth of 1 MHz (10 * 1 MHz = 10 MHz)."),
            ("What specialized three-op-amp circuit provides high differential gain, extremely high input impedance, and high CMRR for medical ECG amplifiers?", "Instrumentation Amplifier (In-Amp)", ["Summing Amplifier", "Logarithmic Amplifier", "Transimpedance Amplifier"], "Instrumentation amplifiers use two buffered inputs feeding a difference amplifier stage, standardly utilized for strain gauges and thermocouple bridges."),
            ("What op-amp circuit converts a small input current from a photodiode directly into a proportional output voltage?", "Transimpedance Amplifier (Current-to-Voltage Converter)", ["Instrumentation Amplifier", "Charge Amplifier", "Logarithmic Amplifier"], "A transimpedance amplifier uses a feedback resistor Rf across the op-amp, producing output Vout = -I_in * Rf."),
            ("What circuit converts an input voltage into a proportional output current, also known as a voltage-controlled current source?", "Transconductance Amplifier", ["Transimpedance Amplifier", "Voltage Follower", "Buffer Amplifier"], "Transconductance amplifiers deliver an output current proportional to input voltage (Iout = gm * Vin)."),
            ("What type of filter passes low-frequency signals below a specific cutoff frequency and attenuates high frequencies above that point?", "Low-Pass Filter (LPF)", ["High-Pass Filter (HPF)", "Band-Pass Filter (BPF)", "Notch Filter"], "Low-pass filters eliminate high-frequency noise and prevent aliasing before analog-to-digital conversion."),
            ("What formula calculates the -3 dB cutoff frequency of a simple single-pole passive RC low-pass filter?", "fc = 1 / (2 * pi * R * C)", ["fc = 2 * pi * R * C", "fc = R / (2 * pi * C)", "fc = 1 / (R * C)"], "At the cutoff frequency fc, signal power drops by half (-3 dB) and output phase shifts by -45 degrees."),
            ("What is the roll-off attenuation rate of a standard first-order (single-pole) analog filter in its stopband?", "20 dB per decade (or 6 dB per octave)", ["40 dB per decade", "60 dB per decade", "10 dB per decade"], "Each additional filter pole adds 20 dB/decade of attenuation; a second-order filter rolls off at 40 dB/decade, and a fourth-order rolls off at 80 dB/decade."),
            ("What active filter topology utilizes an op-amp with resistor-capacitor feedback networks to implement second-order filter sections?", "Sallen-Key Topology", ["Multiple Feedback (MFB) Topology", "State-Variable Topology", "Twin-T Topology"], "Sallen-Key circuits are widely used to construct second-order low-pass and high-pass filters with unity or low gain."),
            ("What analog filter response type is characterized by a maximally flat passband with zero gain ripple?", "Butterworth Filter", ["Chebyshev Filter", "Bessel Filter", "Elliptic (Cauer) Filter"], "Butterworth filters feature a smooth, monotonic frequency response in the passband, sacrificing steep roll-off for flatness."),
            ("What analog filter type features a steep transition roll-off at the expense of equal-amplitude ripple in the passband?", "Chebyshev Type I Filter", ["Butterworth Filter", "Bessel Filter", "Gaussian Filter"], "Chebyshev filters achieve sharper transition skirts than Butterworth filters of the same order, but introduce passband ripple."),
            ("What analog filter type optimizes linear phase response and constant group delay, preserving pulse waveforms without overshoot or ringing?", "Bessel Filter", ["Butterworth Filter", "Chebyshev Filter", "Elliptic Filter"], "Bessel filters are ideal for audio and pulse processing because all frequency components undergo equal time delay."),
            ("What analog filter type achieves the steepest possible transition between passband and stopband by allowing ripple in both regions?", "Elliptic (Cauer) Filter", ["Butterworth Filter", "Chebyshev Filter", "Bessel Filter"], "Elliptic filters provide maximum selectivity for a given order, but exhibit severe phase distortion and ripple in both passband and stopband."),
            ("What type of filter rejects a narrow band of frequencies while passing all frequencies above and below it?", "Band-Stop Filter (Notch Filter)", ["Band-Pass Filter", "Low-Pass Filter", "High-Pass Filter"], "A 60 Hz (or 50 Hz) notch filter eliminates mains hum from sensitive biological ECG or EEG signals."),
            ("What circuit topology uses two parallel T-shaped RC networks to create a deep notch filter without inductors?", "Twin-T Notch Filter", ["Sallen-Key Filter", "Wien Bridge", "Colpitts Circuit"], "Twin-T networks provide high Q rejection at a single frequency fc = 1 / (2 * pi * R * C)."),
            ("What operational amplifier parameter measures the change in input offset voltage resulting from power supply voltage fluctuations?", "Power Supply Rejection Ratio (PSRR)", ["Common-Mode Rejection Ratio", "Slew Rate", "Gain-Bandwidth Product"], "High PSRR ensures that ripple and noise on DC supply rails do not leak into the amplified audio or sensor output."),
            ("What type of transistor audio amplifier operates in Class A configuration?", "An amplifier where output transistors conduct current continuously through the entire 360 degrees of the input waveform cycle", ["An amplifier where transistors conduct for 180 degrees", "An amplifier using pulse-width modulation", "An amplifier that conducts for less than 90 degrees"], "Class A provides highest linearity and zero crossover distortion, but suffers from low thermal efficiency (maximum 25-50%)."),
            ("What amplifier class conducts for exactly 180 degrees of the input cycle using complementary push-pull transistors?", "Class B Amplifier", ["Class A Amplifier", "Class AB Amplifier", "Class D Amplifier"], "Class B uses an NPN transistor for the positive half-cycle and a PNP for the negative half-cycle, but suffers from crossover distortion near zero volts."),
            ("What amplifier class biases push-pull transistors with a small idle quiescent current to eliminate crossover distortion?", "Class AB Amplifier", ["Class A Amplifier", "Class B Amplifier", "Class D Amplifier"], "Class AB is the ubiquitous standard for high-fidelity linear audio, combining Class B efficiency with Class A distortion-free zero crossing."),
            ("What highly efficient amplifier class operates output transistors as fully on or fully off digital switches using PWM modulation?", "Class D Amplifier", ["Class A Amplifier", "Class B Amplifier", "Class C Amplifier"], "Class D achieves greater than 90% power efficiency by switching rapidly between rail voltages, minimizing heat dissipation."),
            ("What high-frequency amplifier class conducts for significantly less than 180 degrees into a resonant LC tank circuit, achieving high RF efficiency?", "Class C Amplifier", ["Class A Amplifier", "Class B Amplifier", "Class AB Amplifier"], "Class C amplifiers are used for constant-envelope RF transmitter power stages, relying on the tuned tank to reconstruct the sine wave."),
            ("What condition for sustained oscillation states that loop gain must equal 1 and total loop phase shift must be 0 or 360 degrees?", "Barkhausen Stability Criterion", ["Nyquist Stability Criterion", "Bode Criterion", "Routh-Hurwitz Criterion"], "Barkhausen's criteria dictate the exact conditions under which an amplifier circuit will maintain steady sinusoidal oscillations."),
            ("What audio oscillator circuit utilizes a balanced resistive-capacitive bridge network to generate low-distortion sine waves?", "Wien Bridge Oscillator", ["Colpitts Oscillator", "Hartley Oscillator", "Clapp Oscillator"], "The Wien bridge operates with a phase shift of zero degrees at resonant frequency fo = 1 / (2 * pi * R * C), stabilized by a tungsten bulb or JFET."),
            ("What LC resonant oscillator circuit uses a tapped capacitive voltage divider in its resonant tank to provide feedback?", "Colpitts Oscillator", ["Hartley Oscillator", "Wien Bridge Oscillator", "Pierce Oscillator"], "Colpitts oscillators use two capacitors and an inductor in the feedback tank, providing stable RF sine wave generation."),
            ("What LC resonant oscillator circuit uses a tapped inductor (autotransformer) in its resonant tank to provide feedback?", "Hartley Oscillator", ["Colpitts Oscillator", "Pierce Oscillator", "Wien Bridge Oscillator"], "Hartley oscillators use a center-tapped inductor paired with a capacitor, widely utilized in early superheterodyne radio local oscillators."),
            ("What crystal oscillator circuit, standard in microcontrollers, connects a quartz crystal across an inverting gate with two load capacitors?", "Pierce Oscillator", ["Colpitts Oscillator", "Hartley Oscillator", "Armstrong Oscillator"], "Pierce oscillators provide high frequency stability, low cost, and minimal component count for digital clock generation."),
            ("What circuit topology uses two matched transistors sharing a common emitter current source to amplify only the voltage difference between inputs?", "Differential Pair (Long-Tailed Pair)", ["Darlington Pair", "Cascode Amplifier", "Push-Pull Stage"], "The differential pair forms the input stage of virtually all operational amplifiers, rejecting common-mode noise while amplifying differential signals."),
            ("What two-transistor configuration connects the collector of a common-emitter stage to the emitter of a common-base stage to eliminate Miller effect?", "Cascode Configuration", ["Darlington Pair", "Sziklai Pair", "Push-Pull Stage"], "Cascode amplifiers provide very high output impedance, wide bandwidth, and high reverse isolation by suppressing Miller capacitance."),
            ("What two-transistor composite configuration connects two BJTs such that the emitter of the first drives the base of the second, multiplying current gain?", "Darlington Pair", ["Cascode Pair", "Differential Pair", "Totem Pole"], "A Darlington pair achieves composite current gain Beta_total = Beta1 * Beta2, delivering high input impedance and huge current gain.")
        ]
    }

print("Loaded Electronics questions successfully.")
'''

with open(os.path.abspath('scripts/generators/data_stem_part2.py'), 'w', encoding='utf-8') as f:
    f.write(content)
print("Created scripts/generators/data_stem_part2.py successfully.")
