"""
gen_culture_part3.py
Builds scripts/generators/data_culture_part3.py containing:
- Cartoon Characters (150: 38, 38, 37, 37)
- Relationships (130: 33, 33, 32, 32)
- Wisdom (130: 33, 33, 32, 32)
"""

import os

content = '''"""
data_culture_part3.py
Contains comprehensive, distinct questions for:
- Cartoon Characters (150 questions: 38, 38, 37, 37)
- Relationships (130 questions: 33, 33, 32, 32)
- Wisdom (130 questions: 33, 33, 32, 32)
"""

def get_cartoon_items():
    return {
        "Classic Cartoons": [
            ("What famous animated rabbit, created in 1940 at Warner Bros., is known for munching a carrot and asking 'What\\'s up, doc?'?", "Bugs Bunny", ["Daffy Duck", "Porky Pig", "Roger Rabbit"], "Voiced by Mel Blanc ('The Man of a Thousand Voices'), Bugs Bunny became the official mascot of Warner Bros. entertainment."),
            ("What short-tempered, lisping black duck was created by Tex Avery and Bob Clampett in 1937, proclaiming 'You\\'re despicable!'?", "Daffy Duck", ["Donald Duck", "Howard the Duck", "Darkwing Duck"], "Daffy Duck evolved from an uninhibited screwball character into a jealous, vain rival to Bugs Bunny's fame."),
            ("What stuttering Warner Bros. cartoon pig famously concludes Looney Tunes and Merrie Melodies shorts with 'Th-th-th-that\\'s all, folks!'?", "Porky Pig", ["Babe", "Miss Piggy", "Piglet"], "Porky Pig was Warner Bros.' first legitimate cartoon star, debuting in 1935's I Haven't Got a Hat."),
            ("What persistent Looney Tunes predator endlessly orders complex contraptions from the ACME Corporation to catch the Road Runner?", "Wile E. Coyote", ["Sylvester the Cat", "Elmer Fudd", "Yosemite Sam"], "Created by Chuck Jones and Michael Maltese, Wile E. Coyote\\'s elaborate physics-defying traps inevitably backfire on him."),
            ("What fast-running desert bird outsmarts Wile E. Coyote with bursts of supersonic speed and a signature 'Beep-beep!' sound?", "The Road Runner (Acceleratii incredibilis)", ["Woody Woodpecker", "Tweety Bird", "Foghorn Leghorn"], "The Road Runner never leaves the road and never harms the coyote directly, relying on the coyote's own ineptitude."),
            ("What bumbling, speech-impaired hunter is determined to hunt rabbits and ducks, warning 'Be vewy vewy quiet, I\\'m hunting wabbits'?", "Elmer Fudd", ["Yosemite Sam", "Foghorn Leghorn", "Taz"], "Elmer Fudd's rhotacism replaces 'r' and 'l' with 'w', frequently duped by Bugs Bunny's cross-dressing disguises."),
            ("What fiery-tempered, gun-toting cowboy prospector with a giant red mustache despises 'varmints' and Bugs Bunny?", "Yosemite Sam", ["Elmer Fudd", "Foghorn Leghorn", "Quick Draw McGraw"], "Created by Friz Freleng to provide Bugs with a more aggressive, genuinely dangerous adversary than Elmer Fudd."),
            ("What loud, blustery rooster, based on the radio character Senator Claghorn, endlessly pesters the barnyard Dog?", "Foghorn Leghorn", ["Rooster Cogburn", "Woody Woodpecker", "Chicken Little"], "Foghorn punctuates his booming Southern monologue with 'Look at me when I\\'m talkin\\' to ya, boy!' and 'That\\'s a joke, son!'"),
            ("What yellow canary constantly outwits Sylvester the Cat, remarking 'I tawt I taw a puddy tat'?", "Tweety Bird", ["Woody Woodpecker", "Road Runner", "Big Bird"], "Created by Bob Clampett and refined by Friz Freleng, Tweety lives safely in a birdcage under the protection of Granny."),
            ("What tuxedo cat with a red nose endlessly stalks Tweety Bird and Speedy Gonzales, sputtering 'Sufferin\\' succotash!'?", "Sylvester the Cat", ["Tom", "Garfield", "Felix the Cat"], "Sylvester's wet, lisping catchphrase and persistent failures to eat Tweety won three Academy Awards for Warner Bros."),
            ("What Mexican mouse, wearing an oversized yellow sombrero and white clothes, is celebrated as 'The Fastest Mouse in all Mexico'?", "Speedy Gonzales", ["Slowpoke Rodriguez", "Mighty Mouse", "Jerry"], "Speedy shouts '¡Ándale! ¡Ándale! ¡Arriba! ¡Arriba!' as he outruns Sylvester the Cat to deliver cheese to hungry mice."),
            ("What destructive marsupial from Down Under spins like a tornado, grunting and devouring everything in his path?", "The Tasmanian Devil (Taz)", ["Wile E. Coyote", "Crash Bandicoot", "Yosemite Sam"], "Introduced by Robert McKimson in 1954, Taz's ferocious appetite and wild spinning vortex made him an iconic Looney Tunes star."),
            ("What romantic French skunk, created by Chuck Jones in 1945, perpetually pursues black cats accidentally painted with a white stripe?", "Pepé Le Pew", ["Sylvester", "Tom", "Fifi La Fume"], "Pepé mistakes Penelope Pussycat for a fellow skunk, wooing her aggressively with florid French romantic endearments."),
            ("What silent slapstick cat-and-mouse rivalry, created by William Hanna and Joseph Barbera for MGM in 1940, won seven Academy Awards?", "Tom and Jerry", ["Sylvester and Tweety", "Itchy and Scratchy", "Pixie and Dixie"], "Thomas the house cat and Jerry the clever brown mouse engaged in chaotic, violent orchestral slapstick across 161 theatrical shorts."),
            ("What iconic sailor, created by E.C. Segar in 1929, gains superhuman strength whenever he consumes a can of spinach?", "Popeye the Sailor Man", ["Bluto", "Wimpy", "Sinbad"], "Popeye protects his girlfriend Olive Oyl from the hulking bully Bluto, singing 'I\\'m Popeye the Sailor Man, I\\'m strong to the finich, 'cause I eats me spinach!'"),
            ("What hamburger-obsessed friend of Popeye is famous for the catchphrase 'I\\'ll gladly pay you Tuesday for a hamburger today'?", "J. Wellington Wimpy", ["Popeye", "Bluto", "Poopdeck Pappy"], "Wimpy's relentless mooching and love of hamburgers inspired the name of the international Wimpy burger chain."),
            ("What anthropomorphic black cat, created in 1919 during the silent film era, is famous for his magical yellow bag of tricks?", "Felix the Cat", ["Sylvester", "Tom", "Fritz the Cat"], "Felix was the first animated character in cinematic history to achieve mass merchandise popularity and global recognition."),
            ("What laughing, red-crested woodpecker was created in 1940 by Walter Lantz and voiced with a signature cackling laugh by Mel Blanc?", "Woody Woodpecker", ["Foghorn Leghorn", "Road Runner", "Daffy Duck"], "Woody's maniacal staccato laugh ('Ha-ha-ha-HA-ha!') became one of the most recognized audio signatures in cartoon history."),
            ("What superhero mouse, created by Terrytoons in 1942 as a parody of Superman, sang in operatic recitative while flying into battle?", "Mighty Mouse", ["Danger Mouse", "Speedy Gonzales", "Super Mouse"], "Originally named Super Mouse, Mighty Mouse flew in to save mice from army cats, proclaiming 'Here I come to save the day!'"),
            ("What stone-age animated sitcom, created by Hanna-Barbera in 1960, followed Fred and Wilma in the prehistoric town of Bedrock?", "The Flintstones", ["The Jetsons", "Captain Caveman", "Dino Boy"], "The Flintstones was the first prime-time animated television series, famous for Fred's joyous shout: 'Yabba-Dabba-Doo!'"),
            ("What futuristic Hanna-Barbera animated family lived in Orbit City with flying aerocars, moving sidewalks, and robotic maid Rosie?", "The Jetsons", ["The Flintstones", "Futurama", "The Centurions"], "George, Jane, Judy, and Elroy Jetson envisioned a whimsical 21st-century technological future of push-button living."),
            ("What Great Dane dog and his teenage mystery-solving friends travel in the green Mystery Machine van unmasking fraudulent ghosts?", "Scooby-Doo (Scoobert Doo)", ["Muttley", "Astro", "Hong Kong Phooey"], "Fred, Daphne, Velma, Shaggy, and Scooby solve supernatural mysteries, coaxed into dangerous rooms with tasty 'Scooby Snacks.'"),
            ("What cowardly, constantly hungry beatnik companion of Scooby-Doo is known for his baggy green shirt and catchphrase 'Zoinks!'?", "Norville 'Shaggy' Rogers", ["Fred Jones", "Scrappy-Doo", "Daphne Blake"], "Voiced for decades by radio legend Casey Kasem, Shaggy and Scooby bonded over towering multi-layer sandwiches."),
            ("What picnic-basket-stealing brown bear in Jellystone Park proclaims he is 'smarter than the av-er-age bear' to his pal Boo-Boo?", "Yogi Bear", ["Smokey Bear", "Fozzie Bear", "Baloo"], "Created by Hanna-Barbera in 1958, Yogi constantly outwits Ranger Smith to swipe tourist 'pic-a-nic' baskets."),
            ("What lazy, lasagna-loving orange tabby cat, created by cartoonist Jim Davis in 1978, despises Mondays and tormenting Odie the dog?", "Garfield", ["Heathcliff", "Felix the Cat", "Sylvester"], "Garfield's deadpan sarcasm, love of naps, and exploitation of his bumbling owner Jon Arbuckle made it the world's most syndicated comic strip."),
            ("What energetic, yellow-furred beagle dog in Jim Davis\\'s Garfield comic strip is known for panting with his tongue hanging out?", "Odie", ["Snoopy", "Pluto", "Poochie"], "Odie is the lovable, brainless foil whom Garfield frequently kicks off the kitchen table."),
            ("What imaginative black-and-white beagle dog in Charles M. Schulz\\'s Peanuts comic strip fantasizes about being a World War I Flying Ace?", "Snoopy", ["Odie", "Goofy", "Brian Griffin"], "Perched on his doghouse roof, Snoopy battles the Red Baron, dances joyfully on his hind legs, and types novels on his typewriter."),
            ("What sweet-natured yellow bird is Snoopy\\'s loyal best friend and bird-mechanic in Charles M. Schulz\\'s Peanuts?", "Woodstock", ["Tweety", "Flit", "Big Bird"], "Named after the 1969 music festival, Woodstock communicates through exclamation marks that only Snoopy can decipher."),
            ("What insecure, round-headed boy in Peanuts wears a yellow zigzag polo shirt and endlessly attempts to kick Lucy\\'s football?", "Charlie Brown", ["Linus van Pelt", "Schroeder", "Franklin"], "Charlie Brown's resilient spirit in the face of kite-eating trees and baseball losses made him an American folk anti-hero."),
            ("What thumb-sucking, blanket-carrying philosopher in Peanuts delivers the true meaning of Christmas in A Charlie Brown Christmas?", "Linus van Pelt", ["Charlie Brown", "Schroeder", "Pig-Pen"], "Linus recites the Gospel of Luke on stage, comforting Charlie Brown's scrawny little pine tree."),
            ("What domineering, crabby girl in Peanuts dispenses psychiatric advice from a wooden lemonade stand for five cents?", "Lucy van Pelt", ["Peppermint Patty", "Marcie", "Sally Brown"], "Lucy routinely yanks the football away from Charlie Brown at the final millisecond, sending him flying on his back."),
            ("What musical prodigy in Peanuts plays classical Beethoven sonatas on a tiny toy piano while ignoring Lucy\\'s romantic advances?", "Schroeder", ["Linus", "Charlie Brown", "Franklin"], "Schroeder's intense dedication to Beethoven's birthday and his toy grand piano highlighted Schulz's love of classical music."),
            ("What spinach-loving baby orphan was delivered in a basket to Popeye\\'s house in 1933, crawling into constant industrial danger?", "Swee'Pea", ["Pip-Eye", "Baby Huey", "Junior"], "Popeye adopts the gentle crawling infant, who miraculously survives walking along skyscraper girders unharmed."),
            ("What giant, innocent baby duck wearing a diaper and bonnet was created by Famous Studios in 1950, causing accidental destruction?", "Baby Huey", ["Donald Duck", "Howard the Duck", "Daffy Duck"], "Baby Huey's super-strength and dim-witted gentleness frustrated his parents and the hungry Fox who tried to cook him."),
            ("What classic 1930s Fleischer Studios cartoon character was modeled after singer Helen Kane with a baby-doll face and the catchphrase 'Boop-oop-a-doop'?", "Betty Boop", ["Olive Oyl", "Jessica Rabbit", "Brenda Starr"], "Betty Boop's flapper dress, garter, and jazz-age surrealism made her an enduring animation sex symbol."),
            ("What 1988 live-action/animated neo-noir comedy, directed by Robert Zemeckis, featured Bob Hoskins investigating murder in Toontown?", "Who Framed Roger Rabbit", ["Space Jam", "Cool World", "Looney Tunes: Back in Action"], "Roger Rabbit united Disney and Warner Bros. cartoon stars on screen for the first time, featuring the glamorous Jessica Rabbit."),
            ("What glamorous femme fatale cartoon character in Who Framed Roger Rabbit famously purred: 'I\\'m not bad. I\\'m just drawn that way'?", "Jessica Rabbit", ["Betty Boop", "Holli Would", "Lola Bunny"], "Voiced by Kathleen Turner with singing by Amy Irving, Jessica remained fiercely loyal to her comedy-loving husband Roger."),
            ("What sinister Toontown judge, played by Christopher Lloyd in Who Framed Roger Rabbit, executed toons using a toxic vat of 'Dip'?", "Judge Doom", ["Eddie Valiant", "Marvin Acme", "R.K. Maroon"], "Doom reveals himself as a red-eyed, high-pitched toon in disguise who murdered Eddie Valiant's brother with a falling piano.")
        ],
        "Disney & Pixar": [
            ("What legendary cartoon mouse, created by Walt Disney and Ub Iwerks in 1928, debuted in the synchronized sound cartoon Steamboat Willie?", "Mickey Mouse", ["Mighty Mouse", "Jerry", "Mortimer Mouse"], "Steamboat Willie debuted at the Colony Theater in New York, launching the Walt Disney global entertainment empire."),
            ("What sweet-natured cartoon mouse and eternal sweetheart of Mickey Mouse debuted alongside him in Steamboat Willie and Plane Crazy?", "Minnie Mouse (Minerva Mouse)", ["Daisy Duck", "Clarabelle Cow", "Katy Caboose"], "Minnie's polka-dot dress, oversized bow, and yellow heels made her one of the most recognized female animated figures on Earth."),
            ("What short-tempered, white sailor-suit-wearing duck with barely intelligible speech debuted in Disney\\'s The Wise Little Hen in 1934?", "Donald Duck (Donald Fauntleroy Duck)", ["Daffy Duck", "Scrooge McDuck", "Ludwig Von Drake"], "Voiced for 50 years by Clarence 'Ducky' Nash, Donald's explosive tantrums made him one of Disney's most popular characters."),
            ("What tall, clumsy, anthropomorphic dog wearing a rumpled fedora and vest is famous for his signature 'A-hyuck!' laugh and holler?", "Goofy (Goofus D. Dawg / Dippy Dawg)", ["Pluto", "Droopy", "Huckleberry Hound"], "Goofy starred in popular 1940s 'How to' instructional sports parody shorts, known for the falling 'Wilhelm-like' Goofy holler."),
            ("What non-speaking, yellow-orange pet dog of Mickey Mouse behaves like a real dog, communicating through barks and expressive pantomime?", "Pluto the Pup", ["Goofy", "Bolt", "Nana"], "Pluto was designed as an authentic canine character without human clothes, showcasing groundbreaking animator squash-and-stretch anatomy."),
            ("What miserly Scottish billionaire duck, who swims in a giant money bin of gold coins, is the great-uncle of Huey, Dewey, and Louie?", "Scrooge McDuck", ["Donald Duck", "Flintheart Glomgold", "Launchpad McQuack"], "Created by comic artist Carl Barks in 1947, Scrooge headlined the hit 1987 animated television series DuckTales."),
            ("What wooden puppet, carved by woodcarver Geppetto, dreams of becoming a real boy if he can prove himself brave, truthful, and unselfish?", "Pinocchio", ["Gideon", "Stromboli", "Lampwick"], "When Pinocchio tells lies, his wooden nose grows longer, guided by his official conscience Jiminy Cricket."),
            ("What dapper green cricket serves as Pinocchio\\'s conscience, singing Disney\\'s corporate anthem 'When You Wish Upon a Star'?", "Jiminy Cricket", ["Timothy Q. Mouse", "Sebastian", "Pascal"], "Voiced by Cliff Edwards, Jiminy Cricket became an iconic Disney ambassador of conscience, optimism, and moral guidance."),
            ("What gentle baby circus elephant, ridiculed for his enormous ears, discovers he can use them to fly with a 'magic feather'?", "Dumbo (Jumbo Jr.)", ["Bambi", "Timothy", "Goliath"], "Guided by Timothy Q. Mouse, Dumbo's soaring flight over the circus big top turned him from an outcast into an international hero."),
            ("What gentle white-tailed deer fawn grows up to become the 'Great Prince of the Forest' following the tragic loss of his mother?", "Bambi", ["Thumper", "Flower", "Faline"], "Bambi navigates forest life with energetic rabbit Thumper and bashful skunk Flower in Disney's naturalistic 1942 classic."),
            ("What energetic young rabbit in Disney\\'s Bambi is famous for thumping his hind foot and sharing 'If you can\\'t say something nice, don\\'t say nothing at all'?", "Thumper", ["Bambi", "Flower", "Peter Cottontail"], "Thumper's mother's golden rule of politeness became one of the most quoted moral guidelines in animation history."),
            ("What tiny, feisty blonde fairy wearing a green leaf dress leaves trails of glowing pixie dust in Disney\\'s 1953 Peter Pan?", "Tinker Bell", ["Silvermist", "Fawn", "Iridessa"], "Tinker Bell became Disney's primary symbol of magic, flying over Cinderella Castle during fireworks displays."),
            ("What red-haired mermaid princess trades her voice to sea witch Ursula for human legs in Disney\\'s 1989 musical The Little Mermaid?", "Ariel", ["Belle", "Jasmine", "Aurora"], "Jodi Benson voiced Ariel, whose soaring 'Part of Your World' launched the golden 1990s Disney Renaissance era."),
            ("What high-strung Jamaican red crab serves as King Triton\\'s court composer and sings 'Under the Sea' and 'Kiss the Girl'?", "Sebastian (Horatio Thelonious Ignatius Crustaceous Sebastian)", ["Flounder", "Scuttle", "Tamatoa"], "Sebastian tries to keep Ariel from human shores, winning the Academy Award for Best Original Song for 'Under the Sea.'"),
            ("What bookish, independent French village girl falls in love with a cursed beast in his enchanted castle to save her father?", "Belle", ["Ariel", "Cinderella", "Snow White"], "Voiced by Paige O'Hara, Belle's love of reading and inner beauty broke traditional passive Disney princess archetypes."),
            ("What street-smart Arabian orphan discovers a magic oil lamp in the Cave of Wonders and wishes to become Prince Ali to win Princess Jasmine?", "Aladdin", ["Ali Baba", "Sinbad", "Jafar"], "Aladdin uses his wits and three wishes, helped by his pet monkey Abu and magic flying carpet in the Sultan's city of Agrabah."),
            ("What cosmic, fast-talking blue magical spirit in Aladdin granted three wishes, voiced with lightning improvisational genius by Robin Williams?", "The Genie", ["Jafar", "Iago", "The Sultan"], "Williams recorded dozens of hours of unscripted celebrity impressions and jokes, revolutionizing celebrity voice casting in modern animation."),
            ("What lion cub prince must overcome guilt over his father Mufasa\\'s death to reclaim Pride Rock from his villainous uncle Scar?", "Simba", ["Mufasa", "Scar", "Kovu"], "Simba learns to embrace his royal heritage and the Circle of Life alongside wise mandrill shaman Rafiki."),
            ("What meerkat and warthog duo teach young Simba the stress-free philosophy 'Hakuna Matata' (no worries for the rest of your days)?", "Timon and Pumbaa", ["JaQ and Gus", "Meeko and Flit", "Baloo and Mowgli"], "Voiced by Nathan Lane and Ernie Sabella, the comedic duo survive on crunchy grubs and loyal friendship in the jungle."),
            ("What brave Chinese maiden disguises herself as male soldier 'Ping' to take her elderly father\\'s place in the Imperial Army against the Huns?", "Fa Mulan", ["Pocahontas", "Raya", "Cinderella"], "Ming-Na Wen provided speaking and Lea Salonga provided singing for Mulan, who saved China from Shan Yu beneath the fireworks."),
            ("What tiny, disgraced red dragon guardian, voiced by Eddie Murphy, acts as Mulan\\'s comedic self-appointed protector and hype-man?", "Mushu", ["Cri-Kee", "Khan", "Olaf"], "Mushu rings the gong for the ancestors before declaring: 'Dishonor on you! Dishonor on your cow!'"),
            ("What pull-string cowboy doll, voiced by Tom Hanks in Pixar\\'s Toy Story, serves as Andy\\'s favorite toy and leader of the bedroom?", "Sheriff Woody Pride", ["Buzz Lightyear", "Rex", "Slinky Dog"], "Woody overcomes jealousy toward new space toy Buzz Lightyear, learning that true leadership means selfless friendship."),
            ("What electronic space ranger action figure, voiced by Tim Allen, believes he is a real Galactic Alliance officer fighting Emperor Zurg?", "Buzz Lightyear", ["Woody", "Zurg", "Major Matt Mason"], "Buzz's heroic motto 'To infinity and beyond!' became an iconic catchphrase, discovering his real purpose as Andy's beloved toy."),
            ("What neurotic, nervous plastic green Tyrannosaurus rex toy in Toy Story fears confrontation and being replaced by a scarier dinosaur?", "Rex", ["Reptar", "Spike", "Yoshi"], "Voiced by Wallace Shawn, Rex's endearing lack of confidence and tiny arms contrast with his ferocious dinosaur appearance."),
            ("What blue-furred, horned monster champion scarer at Monsters, Inc. forms a protective paternal bond with a human toddler named Boo?", "James P. 'Sulley' Sullivan", ["Mike Wazowski", "Randall Boggs", "George Sanderson"], "Voiced by John Goodman, Sulley discovers that child laughter generates ten times more electrical energy than screams."),
            ("What round, green, one-eyed monster in Monsters, Inc. is Sulley\\'s comedic best friend, coach, and roommate?", "Mike Wazowski", ["Sulley", "Randall", "Roz"], "Voiced by Billy Crystal, Mike is proud of his girlfriend Celia and ecstatic even when his face is covered by barcodes on magazine covers."),
            ("What neurotic orange clownfish father crosses the entire Pacific Ocean to Sydney Harbour to rescue his captured son in Finding Nemo?", "Marlin", ["Nemo", "Dory", "Crush"], "Albert Brooks voiced Marlin, who learns to conquer his parental overprotectiveness and trust his son's capabilities."),
            ("What optimistic, short-term memory loss blue tang fish travels alongside Marlin, dispensing the life motto 'Just keep swimming'?", "Dory", ["Nemo", "Destiny", "Peach"], "Voiced by Ellen DeGeneres, Dory's ability to read human English and 'speak whale' helps Marlin navigate shark meetings and jellyfishes."),
            ("What superhero family patriarch, known as Mr. Incredible, works a depressing insurance job before returning to heroics on Syndrome\\'s island?", "Bob Parr (Mr. Incredible)", ["Frozone", "Dash Parr", "Syndrome"], "Mr. Incredible possesses immense superhuman physical strength, balancing suburban dad midlife crises with saving Metroville."),
            ("What eccentric, diminutive German-Japanese superhero fashion designer in The Incredibles insists on one cardinal design rule: 'NO CAPES!'?", "Edna 'E' Mode", ["Mirage", "Elastigirl", "Violet"], "Voiced by director Brad Bird, Edna designs high-tech supersuits tailored to each hero's powers, citing gruesome cape accidents."),
            ("What culinary genius sewer rat in Paris aspires to become a master French chef, controlling bumbling garbage boy Linguini like a marionette?", "Remy (Little Chef)", ["Emile", "Django", "Ratso"], "Voiced by Patton Oswalt, Remy proves late chef Auguste Gusteau's culinary motto that 'anyone can cook.'"),
            ("What solitary waste-collector robot compacts trash cubes on an abandoned, garbage-choked Earth for 700 years before following EVE into space?", "WALL-E (Waste Allocation Load Lifter - Earth-Class)", ["EVE", "M-O", "AUTO"], "Sound-designed by Ben Burtt with minimal dialogue, WALL-E's expressive binocular eyes and love for Hello, Dolly! make him deeply human."),
            ("What 78-year-old retired balloon salesman attaches thousands of helium balloons to his house to fly to Paradise Falls in Pixar\\'s Up?", "Carl Fredricksen", ["Russell", "Charles Muntz", "Dug"], "Voiced by Ed Asner, Carl fulfills a lifelong promise to his late wife Ellie, accompanied by over-eager Wilderness Explorer Russell."),
            ("What talking golden retriever in Pixar\\'s Up wears a translator collar that translates his canine thoughts, famously yelling 'SQUIRREL!'?", "Dug", ["Alpha", "Beta", "Gamma"], "Dug immediately adores Carl, declaring: 'I have just met you, and I love you!'"),
            ("What arrogant red Piston Cup rookie race car gets stranded in neglected Radiator Springs on Route 66, learning humility from Doc Hudson?", "Lightning McQueen (Number 95)", ["Tow Mater", "Doc Hudson", "Chick Hicks"], "Voiced by Owen Wilson with his catchphrase 'Ka-chow!', McQueen learns that winning trophies is empty without true friends."),
            ("What rusty, buck-toothed tow truck in Radiator Springs becomes Lightning McQueen\\'s best friend, proud of his backward driving skills?", "Tow Mater (Sir Tow Mater)", ["Lightning McQueen", "Doc Hudson", "Luigi"], "Voiced by Larry the Cable Guy, Mater teaches McQueen tractor tipping and that dents are valuable memories of friendship."),
            ("What glowing, effervescent yellow emotion inside 11-year-old Riley\\'s mind strives to keep her happy in Pixar\\'s Inside Out?", "Joy", ["Sadness", "Anger", "Disgust"], "Voiced by Amy Poehler, Joy learns that Sadness is essential to human empathy, grief processing, and emotional connection."),
            ("What animated snowman created by Elsa\\'s magical ice powers loves warm hugs and dreams of experiencing summer without melting?", "Olaf", ["Sven", "Kristoff", "Marshmallow"], "Voiced by Josh Gad in Frozen, Olaf provides innocent comedic warmth, singing 'In Summer' and teaching that 'some people are worth melting for.'")
        ],
        "Modern Animation": [
            ("What yellow sea sponge works as a fry cook at the Krusty Krab and lives in a pineapple under the sea in Bikini Bottom?", "SpongeBob SquarePants", ["Patrick Star", "Squidward Tentacles", "Mr. Krabs"], "Created by marine science educator Stephen Hillenburg, SpongeBob became Nickelodeon's flagship global media franchise."),
            ("What dim-witted, coral-pink starfish lives under a rock and is SpongeBob SquarePants\\'s loyal, waffle-loving best friend?", "Patrick Star", ["Squidward", "Sandy Cheeks", "Plankton"], "Voiced by Bill Fagerbakke, Patrick's absurd philosophical non-sequiturs and loyalty make him the ultimate cartoon sidekick."),
            ("What arrogant, clarinet-playing turquoise octopus neighbor despises his Krusty Krab cashier job and neighbors SpongeBob and Patrick?", "Squidward Tentacles", ["Mr. Krabs", "Plankton", "Barnacle Boy"], "Squidward's artistic pretensions and existential misery provide relatable adult workplace satire in Bikini Bottom."),
            ("What money-obsessed red crab and former navy sailor owns the Krusty Krab and guards the secret Krabby Patty formula in a safe?", "Eugene H. Krabs (Mr. Krabs)", ["Sheldon J. Plankton", "Squidward", "Larry the Lobster"], "Voiced by Clancy Brown, Mr. Krabs loves money above all else, bantering in pirate slang: 'Ahoy, SpongeBob, me boy!'"),
            ("What tiny, green copepod restaurant owner of the Chum Bucket endlessly schemes to steal the secret Krabby Patty formula?", "Sheldon J. Plankton", ["Mr. Krabs", "Karen", "Squidward"], "Assisted by his sarcastic computer wife Karen, Plankton's megalomaniacal world-domination plans are perpetually foiled by SpongeBob."),
            ("What Texas-born cowgirl scientist squirrel lives underwater in an air-pressurized tree dome and practices karate with SpongeBob?", "Sandy Cheeks", ["Pearl Krabs", "Mrs. Puff", "Karen Plankton"], "Wearing an atmospheric diving suit and oxygen helmet, Sandy is a brilliant inventor, rodeo champion, and martial artist."),
            ("What mad scientist grandfather travels across alternate dimensions in a flying saucer with his anxious 14-year-old grandson Morty?", "Rick Sanchez (Rick and Morty)", ["Morty Smith", "Summer Smith", "Jerry Smith"], "Created by Justin Roiland and Dan Harmon on Adult Swim, Rick is an alcoholic nihilistic genius wielding a green portal gun."),
            ("What blue anthropomorphic scrub jay and brown raccoon duo work as groundskeepers at a local park, turning daily chores into cosmic disasters?", "Mordecai and Rigby (Regular Show)", ["Finn and Jake", "Gumball and Darwin", "Phineas and Ferb"], "Created by J.G. Quintel for Cartoon Network, their simple slacking leads to battling galactic demons with gumball machine boss Benson."),
            ("What human boy with a magical sword and his shape-shifting magical yellow dog brother protect the post-apocalyptic Land of Ooo?", "Finn the Human and Jake the Dog (Adventure Time)", ["Mordecai and Rigby", "Steven and Greg", "Dipper and Mabel"], "Created by Pendleton Ward, Adventure Time's whimsical fantasy concealed rich post-apocalyptic lore following the ancient Mushroom War."),
            ("What lonely, tragic wizard in Adventure Time wears a crown of ice and kidnaps princesses, formerly known as archaeologist Simon Petrikov?", "The Ice King (Simon Petrikov)", ["The Lich", "Marceline", "Princess Bubblegum"], "Voiced by Tom Kenny, the crown's magical madness erased Simon's memories of his human fiancée Betty and his adopted vampire daughter Marceline."),
            ("What rock-playing, bass-strumming 1,000-year-old half-demon vampire queen in Adventure Time drinks the color red rather than blood?", "Marceline the Vampire Queen", ["Princess Bubblegum", "Flame Princess", "Fionna"], "Voiced by Olivia Olson, Marceline's musical relationship with candy kingdom ruler Princess Bubblegum formed a landmark queer animation arc."),
            ("What 12-year-old twin siblings spend their summer vacation working at their Great Uncle Stan\\'s Mystery Shack in Gravity Falls, Oregon?", "Dipper and Mabel Pines", ["Phineas and Candace", "Billy and Mandy", "Tommy and Dil"], "Created by Alex Hirsch, Dipper investigates paranormal anomalies using an authorless journal while Mabel embraces colorful sweaters and pet pig Waddles."),
            ("What two inventive stepbrothers make the most of their 104 days of summer vacation by building rollercoasters while their pet platypus fights evil?", "Phineas Flynn and Ferb Fletcher", ["Dipper and Mabel", "Timmy and Cosmo", "Dexter and Dee Dee"], "While older sister Candace attempts to bust them to their mother, pet Perry the Platypus operates as Secret Agent P against Dr. Doofenshmirtz."),
            ("What pharmacist supervillain in Phineas and Ferb builds elaborate evil machines ending in '-inator' to conquer the Tri-State Area?", "Dr. Heinz Doofenshmirtz", ["Perry the Platypus", "Major Monogram", "Norm"], "Plagued by tragic childhood backstories involving lawn gnomes and neglected birthdays, his devices always feature a self-destruct button."),
            ("What 10-year-old boy in The Fairly OddParents has two green-haired and pink-haired fairy godparents who grant his every wish?", "Timmy Turner (with Cosmo and Wanda)", ["Danny Phantom", "Jimmy Neutron", "Dexter"], "Cosmo's dim-witted goofiness and Wanda's sensible nagging help Timmy navigate babysitter Vicky and fairy rules in 'Da Rules' book."),
            ("What boy genius with a giant head and robotic dog Goddard creates wild inventions in his subterranean clubhouse lab in Retroville?", "Jimmy Neutron (James Isaac Neutron)", ["Dexter", "Phineas Flynn", "Timmy Turner"], "Jimmy solves sci-fi town crises using his 'Brain Blast' thinking breakthroughs, bantering with friends Carl Wheezer and Sheen Estevez."),
            ("What red-headed boy genius in a secret bedroom laboratory endlessly fights to keep his hyperactive ballerina sister Dee Dee out?", "Dexter (Dexter's Laboratory)", ["Jimmy Neutron", "Mandark", "Johnny Test"], "Created by Genndy Tartakovsky for Cartoon Network, Dexter speaks in an exaggerated European accent while fighting rival Mandark."),
            ("What three superhero kindergarten girls, created with sugar, spice, everything nice, and Chemical X, protect the City of Townsville?", "The Powerpuff Girls (Blossom, Bubbles, and Buttercup)", ["The Totally Spies", "The Crystal Gems", "The Hex Girls"], "Created by Craig McCracken, Blossom is the commander, Bubbles is the joy, and Buttercup is the toughest fighter battling Mojo Jojo."),
            ("What hyper-intelligent chimpanzee supervillain in The Powerpuff Girls wears a brain-helmet dome and speaks in redundant, repetitive monologues?", "Mojo Jojo", ["Gorilla Grodd", "Fuzzy Lumpkins", "Him"], "A former lab assistant to Professor Utonium mutated by Chemical X, Mojo seeks revenge: 'I, Mojo Jojo, will destroy the Powerpuff Girls!'"),
            ("What cowardly, pink, timid dog lives in the middle of Nowhere, Kansas, protecting his elderly owners Muriel and Eustace Bagge from monsters?", "Courage the Cowardly Dog", ["Scooby-Doo", "Droopy", "Ren"], "Created by John R. Dilworth, Courage screaming in terror before using his computer to solve bizarre supernatural threats became a cult horror classic."),
            ("What time-traveling, silent samurai prince, trained across the ancient world, battles the shape-shifting demon overlord Aku to return to the past?", "Samurai Jack", ["Afro Samurai", "Kenshin", "Scavenger"], "Created by Genndy Tartakovsky, Samurai Jack earned Emmy Awards for cinematic visual pacing, widescreen framing, and artistic sword combat."),
            ("What human boy, the last airbender, must master all four elements (Water, Earth, Fire, Air) to defeat Fire Lord Ozai and restore balance to the world?", "Avatar Aang (Avatar: The Last Airbender)", ["Prince Zuko", "Sokka", "Uncle Iroh"], "Frozen in an iceberg for 100 years, Aang awakens with pet flying bison Appa, leading friends Katara and Sokka in an epic fantasy journey."),
            ("What exiled Fire Nation prince with a facial burn scar tracks Avatar Aang across the world to restore his honor, guided by Uncle Iroh?", "Prince Zuko", ["Fire Lord Ozai", "Princess Azula", "General Zhao"], "Zuko's emotional transformation from vengeful antagonist to Aang's firebending teacher is widely hailed as one of the greatest redemption arcs in television."),
            ("What wise, tea-loving retired Fire Nation general in Avatar: The Last Airbender counsels his troubled nephew Zuko with compassionate wisdom?", "Uncle Iroh (The Dragon of the West)", ["King Bumi", "Monk Gyatso", "Jeong Jeong"], "Voiced by Mako and Greg Baldwin, Iroh's tearful performance of 'Leaves from the Vine' in memory of his deceased son Lu Ten is deeply beloved."),
            ("What blind, 12-year-old earthbending prodigy invented metalbending and fights as 'The Blind Bandit' in underground earth rumble arenas?", "Toph Beifong", ["Katara", "Suki", "Azula"], "Toph uses seismic sense vibrations through her bare feet to 'see' the world, joining Team Avatar with sarcastic, fierce independence."),
            ("What Water Tribe warrior and older brother of Katara lacks bending abilities, relying on tactical planning, sarcasm, and his trust boomerang?", "Sokka", ["Aang", "Zuko", "Jet"], "Sokka provides comedic grounding and strategic engineering leadership, designing the hot air balloon and eclipse invasion plan."),
            ("What passionate, next-generation Avatar from the Southern Water Tribe masters physical bending easily but struggles with spiritual patience?", "Avatar Korra (The Legend of Korra)", ["Avatar Aang", "Avatar Kyoshi", "Avatar Roku"], "Korra navigates industrialized 1920s-style Republic City, battling Equalist revolution leader Amon and anarchist Zaheer."),
            ("What half-human, half-alien boy with a magical pink gemstone in his navel lives with the magical Crystal Gems in Beach City?", "Steven Universe", ["Finn", "Gumball", "Star Butterfly"], "Created by Rebecca Sugar, Steven Universe earned acclaim for progressive themes of empathy, mental health, and LGBTQ+ representation."),
            ("What blue twelve-year-old cat and his adopted orange goldfish brother Darwin navigate bizarre surreal adventures in the town of Elmore?", "Gumball Watterson (The Amazing World of Gumball)", ["Darwin Watterson", "Richard Watterson", "Anais Watterson"], "The series merged 2D cel animation, 3D CGI, stop-motion, and live-action photography in a groundbreaking visual pastiche."),
            ("What anthropomorphic horse, former 1990s sitcom star of Horsin\\' Around, battles depression, addiction, and self-destruction in Hollywood?", "BoJack Horseman", ["Mr. Peanutbutter", "Todd Chavez", "Princess Carolyn"], "Voiced by Will Arnett on Netflix, BoJack Horseman received critical acclaim as one of the most honest depictions of mental illness in television."),
            ("What pink-haired, energetic Mexican wrestling super-fan and his friends protect the city of Miracle City with magical masks?", "El Tigre (Manny Rivera)", ["Mucha Lucha", "Rikochet", "Speedy Gonzales"], "Manny must choose between using his tiger-claw powers for good like his superhero father or villainy like his supervillain grandfather."),
            ("What teenage half-ghost superhero, created by Butch Hartman, balances high school drama with fighting ectoplasmic villains from the Ghost Zone?", "Danny Phantom (Danny Fenton)", ["Ben 10", "Jake Long", "Timmy Turner"], "Accidentally exposed to his ghost-hunter parents' laboratory portal, Danny goes ghost with green energy blasts and intangibility."),
            ("What 10-year-old boy discovers the alien Omnitrix watch that allows him to transform into ten distinct extraterrestrial superheroes?", "Ben Tennyson (Ben 10)", ["Danny Phantom", "Generator Rex", "Max Tennyson"], "Accompanied by cousin Gwen and Grandpa Max, Ben battles Vilgax across multiple animated television spin-offs."),
            ("What high school cheerleader and secret agent saves the world from villains like Dr. Drakken with her naked mole rat and Ron Stoppable?", "Kim Possible", ["Shego", "Penny Proud", "Totally Spies"], "Voiced by Christy Carlson Romano, Kim balances cheer practice with global spy missions under the motto 'I can do anything.'"),
            ("What clumsy, taco-loving sidekick of Kim Possible carries a pink naked mole rat named Rufus in his pocket?", "Ron Stoppable", ["Wade", "Dr. Drakken", "Jim Possible"], "Ron's accidental martial arts mastery ('Mystical Monkey Power') often saves Kim from supervillains at the final moment."),
            ("What 14-year-old African-American girl navigates suburban family drama, friendships, and middle school in Disney\\'s The Proud Family?", "Penny Proud", ["Dijonay", "LaCienega", "Suga Mama"], "Penny deals with her overprotective snack-manufacturer father Oscar Proud and feisty, wrestling-loving grandmother Suga Mama."),
            ("What teenage skateboarding boy in Manhattan discovers he is the magical American Dragon, charged with protecting magical creatures in New York?", "Jake Long (American Dragon: Jake Long)", ["Danny Phantom", "Ben 10", "Kim Possible"], "Trained by his grandfather Luong Lao Shi, Jake transforms into a fire-breathing dragon while crushing on magical huntsgirl Rose.")
        ],
        "Superhero Cartoons": [
            ("What groundbreaking 1992 animated masterpiece, developed by Bruce Timm and Paul Dini, defined Batman for a generation with dark art-deco style?", "Batman: The Animated Series (BTAS)", ["Batman Beyond", "The Batman", "Justice League"], "Airing on Fox Kids, BTAS featured dark noir storytelling, Shirley Walker's orchestral score, and drew onto black paper backgrounds."),
            ("What legendary voice actor provided the definitive, authoritative animated voice of Batman / Bruce Wayne across three decades starting with BTAS in 1992?", "Kevin Conroy", ["Mark Hamill", "Troy Baker", "Bruce Greenwood"], "Conroy's distinct vocal duality between genial billionaire Bruce Wayne and gritty vigilante Batman made him the quintessential Batman voice."),
            ("What Star Wars actor earned universal acclaim for his terrifying, theatrical, laughing voice performance as the Joker in Batman: The Animated Series?", "Mark Hamill", ["Kevin Conroy", "Richard Epcar", "John DiMaggio"], "Hamill developed a multi-tonal, operatic laugh that ranged from jovial giggles to homicidal screams, winning animation awards."),
            ("What iconic DC supervillainess, originally created by Paul Dini as a one-time walk-on henchwoman in BTAS in 1992, became a global pop superstar?", "Harley Quinn (Dr. Harleen Quinzel)", ["Poison Ivy", "Catwoman", "Livewire"], "Voiced originally by Arleen Sorkin in a jester suit, the former Arkham psychiatrist's twisted romance with the Joker crossed into mainstream DC comics."),
            ("What tragic BTAS episode, written by Paul Dini, redefined Mr. Freeze from a cheesy gimmick villain into a tragic scientist mourning his frozen wife Nora?", "'Heart of Ice'", ["'Mad as a Hatter'", "'Almost Got 'Im'", "'Two-Face'"], "Winning a Daytime Emmy Award, 'Heart of Ice' showed Dr. Victor Fries crying behind his dome, seeking revenge against the corporate boss who killed his wife."),
            ("What futuristic Batman animated spin-off introduced teenager Terry McGinnis fighting crime in Neo-Gotham under the guidance of an elderly Bruce Wayne?", "Batman Beyond", ["Batman: The Brave and the Bold", "The Batman", "Gotham Girls"], "Featuring cyberpunk aesthetics and an electric industrial rock soundtrack, Terry wore a high-tech winged black nanosuit."),
            ("What 1990s Fox Kids animated superhero series featured an iconic rock guitar synthesizer theme song and faithful comic adaptations of the Dark Phoenix Saga?", "X-Men: The Animated Series", ["Spider-Man: The Animated Series", "Iron Man", "Fantastic Four"], "Composed by Ron Wasserman, the pounding theme song and serialization introduced millions of 1990s kids to Wolverine, Cyclops, and Magneto."),
            ("What 1994 Fox Kids animated superhero series followed Peter Parker balancing college life with Kingpin, Venom, and Green Goblin in Manhattan?", "Spider-Man: The Animated Series", ["X-Men", "The Spectacular Spider-Man", "Batman: TAS"], "Christopher Daniel Barnes voiced Spider-Man, featuring multi-episode story arcs, internal monologues, and Marvel superhero crossovers."),
            ("What critically acclaimed 2008 animated series by Greg Weisman is widely considered the most faithful, character-rich adaptation of teenage Peter Parker?", "The Spectacular Spider-Man", ["Ultimate Spider-Man", "Spider-Man: TAS", "Marvel's Spider-Man"], "Balancing web-slinging action with high school relationship drama, it praised Steve Ditko and John Romita Sr.'s classic comic foundations."),
            ("What DC animated series united Superman, Batman, Wonder Woman, Flash, Green Lantern, Martian Manhunter, and Hawkgirl to defend the globe?", "Justice League (and Justice League Unlimited)", ["Young Justice", "Teen Titans", "Legion of Super Heroes"], "Executive produced by Bruce Timm, Justice League set the gold standard for widescreen ensemble superhero storytelling across the DC Animated Universe."),
            ("What animated superhero series followed teenage sidekicks Robin, Starfire, Cyborg, Raven, and Beast Boy living in a giant T-shaped tower?", "Teen Titans", ["Young Justice", "Teen Titans Go!", "Legion of Superheroes"], "Blending American action superheroics with expressive Japanese anime visual comedy, it featured Puffy AmiYumi's theme song."),
            ("What half-demon sorceress member of the Teen Titans is known for her telekinetic shadow magic and the incantation 'Azarath Metrion Zinthos'?", "Raven", ["Starfire", "Terra", "Jinx"], "Voiced by Tara Strong, Raven suppresses her dark emotions to prevent her demonic conqueror father Trigon from destroying Earth."),
            ("What tamaranian alien princess on the Teen Titans shoots bright green starbolts from her hands and struggles with English slang?", "Starfire (Koriand'r)", ["Raven", "Terra", "Blackfire"], "Voiced by Hynden Walch, Starfire's innocent optimism and affection for team leader Robin contrasted with her fierce warrior power."),
            ("What green-skinned shapeshifter on the Teen Titans can instantly morph into any animal on Earth or alien worlds while maintaining his humor?", "Beast Boy (Garfield Logan)", ["Cyborg", "Robin", "Chameleon"], "Voiced by Greg Cipes, Beast Boy's vegetarian jokes and playful relationship with dark, broody Raven anchored team comedy."),
            ("What cybernetic half-human, half-machine member of the Teen Titans is a master mechanical engineer who shouts his victory catchphrase 'Booyah!'?", "Cyborg (Victor Stone)", ["Robin", "Beast Boy", "Steel"], "Voiced by Khary Payton, Cyborg balances his cybernetic enhancements and sonic cannon arm with a love for fixing his T-Car."),
            ("What critically acclaimed DC animated series followed teenage proteges Robin, Aqualad, Kid Flash, Superboy, and Miss Martian running covert black ops missions?", "Young Justice", ["Teen Titans", "Justice League", "Avengers: Earth's Mightiest Heroes"], "Developed by Brandon Vietti and Greg Weisman, Young Justice was celebrated for mature serialized storytelling, time jumps, and strategic espionage."),
            ("What clone of Superman and Lex Luthor in Young Justice struggles with anger and finding his own identity, wearing a black-and-red 'S' t-shirt?", "Superboy (Conner Kent / Project Kr)", ["Bizarro", "Superman", "Steel"], "Rescued from Cadmus Laboratories by Robin, Aqualad, and Kid Flash, Superboy forms a deep romance with telepathic Miss Martian."),
            ("What Green Lantern in Justice League (DCAU), voiced by Phil LaMarr, served as a former US Marine alongside Hawkgirl?", "John Stewart", ["Hal Jordan", "Guy Gardner", "Kyle Rayner"], "John Stewart was chosen over Hal Jordan to provide representation, celebrated for his rigid military discipline and romance with Shayera Hol."),
            ("What Thanagarian warrior in Justice League wields an Nth metal mace capable of disrupting magical energy and dispersing electromagnetic fields?", "Hawkgirl (Shayera Hol)", ["Wonder Woman", "Vixen", "Black Canary"], "Voiced by Maria Canals-Barrera, Hawkgirl's fierce loyalty was tested during the Thanagarian invasion finale, leading to heroic redemption."),
            ("What Marvel animated series, airing in 2010 on Disney XD, faithfully adapted foundational comic storylines from the Skrull invasion to Kang the Conqueror?", "The Avengers: Earth's Mightiest Heroes", ["Avengers Assemble", "Iron Man: Armored Adventures", "Ultimate Spider-Man"], "Featuring an ensemble cast with Captain America, Thor, Iron Man, Hulk, Ant-Man, and Wasp, it captured classic Stan Lee and Jack Kirby comic books."),
            ("What mutant hero with retractable adamantium claws and healing factor was voiced with iconic guttural fury by Cal Dodd in X-Men: The Animated Series?", "Wolverine (Logan)", ["Sabretooth", "Colossus", "Beast"], "Wolverine's slicing of Sentinel robots and love triangle with Jean Grey and Cyclops made him the breakout superstar of 1990s animated television."),
            ("What telekinetic and telepathic mutant hero in X-Men: The Animated Series possessed the universe-shattering cosmic power of the Phoenix?", "Jean Grey", ["Storm", "Rogue", "Emma Frost"], "The multi-episode Dark Phoenix Saga remains one of the most faithful animated adaptations of classic comic book tragedy."),
            ("What southern belle mutant in X-Men: The Animated Series can absorb the memories, powers, and life energy of anyone she touches skin-to-skin?", "Rogue", ["Storm", "Jubilee", "Psylocke"], "Voiced by Lenore Zann with a thick southern drawl, Rogue flew with superhuman strength absorbed from Ms. Marvel, calling everyone 'Sugar.'"),
            ("What mutant master of magnetism and Holocaust survivor serves as the complex, philosophical foil to Professor Xavier in X-Men?", "Magneto (Erik Lehnsherr)", ["Apocalypse", "Mister Sinister", "Juggernaut"], "Voiced by David Hemblen, Magneto fights fiercely for mutant survival, arguing that peaceful coexistence with fearful humanity is an impossible dream."),
            ("What 1990s animated Superman series, created by Bruce Timm and Alan Burnett, introduced Tim Daly as the Man of Steel in Metropolis?", "Superman: The Animated Series", ["The New Batman/Superman Adventures", "Legion of Super Heroes", "Justice League"], "Featuring art-deco 'Oceanic' architecture, it balanced Clark Kent's Kansas roots at the Daily Planet with cosmic threats from Darkseid."),
            ("What tyrannical alien despot of Apokolips, voiced with chilling bass authority by Michael Ironside, was the supreme villain of the DCAU?", "Darkseid", ["Brainiac", "Mongul", "Doomsday"], "Darkseid seeks the Anti-Life Equation to extinguish all free will across the universe, breaking Superman's spirit in the finale 'Legacy.'"),
            ("What cold, calculating alien artificial intelligence in Superman: The Animated Series shrinks and absorbs planetary knowledge before destroying them?", "Brainiac", ["Darkseid", "Metallo", "Parasite"], "Reimagined as a Kryptonian planetary supercomputer who kept Krypton's destruction secret to preserve its own data, voiced by Corey Burton."),
            ("What billionaire industrialist and archenemy of Superman, voiced by Clancy Brown in the DCAU, views Superman as an existential threat to humanity?", "Lex Luthor", ["Brainiac", "Metallo", "Bizarro"], "Bald, wealthy, and brilliant, Luthor uses legal loopholes and Warsuit armor to wage corporate and technological war against the Man of Steel."),
            ("What 1994 animated Disney superhero series, created by Greg Weisman, followed ancient winged stone warriors awakening in modern Manhattan?", "Gargoyles", ["Darkwing Duck", "X-Men", "Mighty Ducks"], "Goliath and his clan turned to stone by day and protected New York City by night, featuring mature Shakespearean themes and Jonathan Frakes."),
            ("What leader of the Manhattan Clan of Gargoyles, voiced by Keith David, embodies honor, nobility, and fierce protection of his clan?", "Goliath", ["Brooklyn", "Broadway", "Lexington"], "Named after the biblical giant, Goliath formed an alliance with NYPD detective Elisa Maza against billionaire David Xanatos."),
            ("What purple-caped, mallard superhero in St. Canard fights crime with a gas gun, proclaiming 'I am the terror that flaps in the night'?", "Darkwing Duck (Drake Mallard)", ["DuckTales", "Gizmoduck", "Howard the Duck"], "Voiced by Jim Cummings, Darkwing balanced bumbling theatrical ego with genuine heroics, assisted by sidekick Launchpad McQuack."),
            ("What robotic superhero alter ego of accountant Fenton Crackshell in DuckTales and Darkwing Duck is activated by the phrase 'Blathering Blatherskite!'?", "Gizmoduck", ["Darkwing Duck", "Mega Duck", "Iron Duck"], "Gizmoduck balances on a single high-speed wheel, wielding an arsenal of gadgets built into his white cybernetic armor suit."),
            ("What 2018 Oscar-winning animated superhero film featured Afro-Latino teenager Miles Morales learning to become Spider-Man alongside Peter B. Parker?", "Spider-Man: Into the Spider-Verse", ["Spider-Man: Across the Spider-Verse", "Big Hero 6", "The Incredibles 2"], "Shameik Moore voiced Miles Morales, who learns to take a 'leap of faith' to defeat Kingpin, set to Post Malone's hit 'Sunflower.'"),
            ("What punk-rock, guitar-playing alternate-universe Spider-Man in Across the Spider-Verse is animated with chaotic cutout collage textures?", "Hobart 'Hobie' Brown (Spider-Punk)", ["Spider-Man 2099", "Spider-Man Noir", "Pavitr Prabhakar"], "Voiced by Daniel Kaluuya with an electric London punk accent, Spider-Punk actively resists fascist authority and corporate copyright."),
            ("What futuristic, serious leader of the Spider-Society, Miguel O\\'Hara, fights to preserve canon events across the multiverse in Across the Spider-Verse?", "Spider-Man 2099", ["Miles Morales", "Peter B. Parker", "Ben Reilly"], "Voiced by Oscar Isaac, Miguel operates out of futuristic Nueva York with red laser webs and vampire fangs, clashing with Miles over destiny."),
            ("What animated superhero comedy parody series on Cartoon Network features chibi-style Robin, Beast Boy, and Starfire engaging in absurd, fourth-wall antics?", "Teen Titans Go!", ["Teen Titans", "Young Justice", "Justice League Action"], "Airing over 400 episodes, Teen Titans Go! mocks comic book fan purity with catchy songs like 'The Night Begins to Shine.'"),
            ("What 2024 Marvel Studios animated revival continued the iconic 1990s mutant storyline with modern animation and high-stakes drama?", "X-Men '97", ["X-Men: Evolution", "Wolverine and the X-Men", "Marvel Zombies"], "Directly continuing the 1997 series finale, X-Men '97 won massive acclaim for mature themes, tragedy at Genosha, and Magneto leading the team.")
        ]
    }

print("Loaded Cartoon Characters questions successfully.")
'''

target_path = os.path.abspath('scripts/generators/data_culture_part3.py')
with open(target_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Created scripts/generators/data_culture_part3.py with Cartoon Characters.")
