"""
gen_culture_part1.py
Builds scripts/generators/data_culture_part1.py containing:
- Entertainment (150: 38, 38, 37, 37)
- Movies (150: 38, 38, 37, 37)
- TV Shows (150: 38, 38, 37, 37)
"""

import os

content = '''"""
data_culture_part1.py
Contains comprehensive, distinct questions for:
- Entertainment (150 questions: 38, 38, 37, 37)
- Movies (150 questions: 38, 38, 37, 37)
- TV Shows (150 questions: 38, 38, 37, 37)
"""

def get_entertainment_items():
    return {
        "Pop Culture": [
            ("What famous toy doll was officially introduced to the American public at the American International Toy Fair in 1959?", "Barbie (Barbara Millicent Roberts)", ["Raggedy Ann", "Bratz", "Cabbage Patch Kids"], "Created by Ruth Handler and manufactured by Mattel, Barbie debuted in her iconic black-and-white zebra-striped swimsuit in March 1959."),
            ("What iconic video game character, created by Shigeru Miyamoto, first debuted under the name 'Jumpman' in 1981?", "Mario", ["Luigi", "Donkey Kong", "Link"], "Mario first appeared as Jumpman in the arcade classic Donkey Kong before headlining Super Mario Bros."),
            ("What bestselling fantasy book series by J.K. Rowling debuted in 1997 with 'The Philosopher\\'s Stone'?", "Harry Potter", ["The Chronicles of Narnia", "Percy Jackson", "His Dark Materials"], "The Harry Potter series grew into a global phenomenon, spawning blockbuster film adaptations and theme parks."),
            ("What collectible stuffed toy sensation, manufactured by Ty Warner in the 1990s, featured heart-shaped tags and plastic pellets?", "Beanie Babies", ["Furby", "Tamagotchi", "Tickle Me Elmo"], "Beanie Babies ignited an intense speculative collecting craze in the late 1990s before the bubble burst."),
            ("What Japanese handheld digital pet toy, created by Akihiro Yokoi and Aki Maita, became a global craze in 1996?", "Tamagotchi", ["Pokemon Pikachu", "Giga Pet", "Furby"], "Users fed, cleaned, and cared for the egg-shaped virtual creature to keep it healthy and alive."),
            ("What multi-colored 3D combination puzzle was invented by Hungarian architect Ernő Rubik in 1974?", "The Rubik's Cube", ["The Pyraminx", "Tangram", "The 15 Puzzle"], "Originally named the Magic Cube, the 3x3 Rubik's Cube became the world's bestselling puzzle toy with over 450 million sold."),
            ("What television reality competition, premiering on CBS in 2000, marooned strangers on an island to 'Outwit, Outplay, Outlast'?", "Survivor", ["Big Brother", "The Amazing Race", "Fear Factor"], "Hosted by Jeff Probst, Survivor pioneered modern American reality television competition."),
            ("What annual music and arts festival, held at the Empire Polo Club in Indio, California, is famous for indie and pop headliners?", "Coachella Valley Music and Arts Festival", ["Lollapalooza", "Bonnaroo", "Glastonbury"], "Founded in 1999, Coachella became a premiere cultural and fashion event in modern pop music."),
            ("What Korean pop song by Psy became the first YouTube video to reach one billion views in December 2012?", "Gangnam Style", ["Dynamite", "Baby Shark", "Despacito"], "Psy's horse-riding dance viral video swept worldwide charts, introducing K-pop into mainstream global consciousness."),
            ("What video-sharing social media platform, launched internationally by ByteDance in 2017, popularized short-form vertical videos?", "TikTok", ["Vine", "Instagram Reels", "Musical.ly"], "TikTok revolutionized global youth culture and music discovery through viral dance challenges and algorithm-driven feeds."),
            ("What wildly popular battle royale video game, released by Epic Games in 2017, featured 100-player matches and building mechanics?", "Fortnite", ["PlayerUnknown's Battlegrounds", "Apex Legends", "Call of Duty: Warzone"], "Fortnite became a cultural titan, hosting live in-game virtual concerts by Travis Scott and Marshmello."),
            ("What animated franchise featuring pocket monsters was created by Satoshi Tajiri and Ken Sugimori for the Nintendo Game Boy in 1996?", "Pokemon", ["Digimon", "Yu-Gi-Oh!", "Monster Rancher"], "Pokemon grew into the highest-grossing media franchise of all time across games, trading cards, anime, and merchandise."),
            ("What collectible card game, created by Richard Garfield and published by Wizards of the Coast in 1993, pioneered the trading card game genre?", "Magic: The Gathering", ["Yu-Gi-Oh!", "Pokemon TCG", "Hearthstone"], "Magic: The Gathering introduced mana systems and collectible card rarity, establishing competitive tabletop TCG tournaments."),
            ("What popular Hasbro tabletop board game simulates a person\\'s travels through life from college to retirement with plastic peg families?", "The Game of Life", ["Monopoly", "Clue", "Scrabble"], "Originally created by Milton Bradley in 1860 as The Checkered Game of Life, the modern version was updated in 1960."),
            ("What mystery board game challenges players to deduce the murderer, weapon, and room in Tudor Mansion?", "Clue (Cluedo)", ["Guess Who?", "Stratego", "Battleship"], "Players deduce suspects like Colonel Mustard and Professor Plum using weapons like the candlestick in the library."),
            ("What building-block construction toy company, founded by Ole Kirk Christiansen in Denmark, translates to 'play well' in Danish?", "LEGO (Leg Godt)", ["Mega Bloks", "K'NEX", "Playmobil"], "Patented with its interlocking clutch tube design in 1958, LEGO became the world's most powerful toy brand."),
            ("What comic book publisher, founded as Timely Publications in 1939 by Martin Goodman, created Spider-Man and Iron Man?", "Marvel Comics", ["DC Comics", "Image Comics", "Dark Horse Comics"], "Stan Lee, Jack Kirby, and Steve Ditko revolutionized superhero comics in the 1960s with flawed, relatable characters."),
            ("What comic book publisher introduced the archetype superhero Superman in Action Comics #1 in June 1938?", "DC Comics (Detective Comics)", ["Marvel Comics", "Fawcett Comics", "Archie Comics"], "DC Comics established the comic book superhero genre with Superman, Batman, and Wonder Woman."),
            ("What annual pop culture convention, founded in 1970 by Shel Dorf, draws over 130,000 attendees to San Diego each July?", "San Diego Comic-Con (SDCC)", ["New York Comic Con", "Dragon Con", "WonderCon"], "SDCC expanded from a comic swap meet into the primary promotional hub for Hollywood superhero blockbusters."),
            ("What video game console, released by Sony in 1994, popularized CD-ROMs for home gaming and sold over 100 million units?", "PlayStation (PS1)", ["Nintendo 64", "Sega Saturn", "Panasonic 3DO"], "Ken Kutaragi's PlayStation broke Nintendo's console monopoly and established Sony as an interactive gaming powerhouse."),
            ("What Microsoft video game console, released in 2001, introduced the popular first-person shooter franchise Halo?", "Xbox", ["Xbox 360", "Xbox One", "Dreamcast"], "The original Xbox featured a built-in hard drive, broadband Ethernet port, and popularized Xbox Live online gaming."),
            ("What motion-controlled video game console, released by Nintendo in 2006, attracted casual players of all ages with Wii Sports?", "Nintendo Wii", ["Nintendo GameCube", "Wii U", "Nintendo Switch"], "The Wii's wireless motion-sensing Wiimote controller made gaming accessible to seniors, kids, and non-gamers alike."),
            ("What sandbox video game, created by Markus 'Notch' Persson and released in 2011, became the bestselling video game in history?", "Minecraft", ["Roblox", "Terraria", "Grand Theft Auto V"], "Minecraft's open-ended voxel block construction and survival mechanics sold over 300 million copies worldwide."),
            ("What open-world action-adventure game, released by Rockstar Games in 2013, grossed $1 billion in its first three days of release?", "Grand Theft Auto V", ["Red Dead Redemption 2", "The Witcher 3", "Cyberpunk 2077"], "Set in fictional San Andreas, GTA V became one of the most profitable entertainment products in human history."),
            ("What electronic robotic pet, released by Tiger Electronics in 1998, spoke its own language 'Furbish' and learned English words?", "Furby", ["AIBO", "Poo-Chi", "Plek"], "Furby's realistic blinking eyes and sensor-based reactive speech sparked massive holiday shopping shortages in 1998."),
            ("What live-action dance craze song by the Spanish pop duo Los Del Río spent 14 weeks atop the Billboard Hot 100 in 1996?", "Macarena (Bayside Boys Mix)", ["The Twist", "Y.M.C.A.", "Cha Cha Slide"], "The Macarena wedding line dance swept the globe, performed at the 1996 Democratic National Convention and the Olympics."),
            ("What animated pop-punk band, created in 1998 by musician Damon Albarn and artist Jamie Hewlett, consists of 2-D, Murdoc, Noodle, and Russel?", "Gorillaz", ["The Archies", "Alvin and the Chipmunks", "Dethklok"], "Gorillaz achieved worldwide multi-platinum success with tracks like 'Clint Eastwood' and 'Feel Good Inc.' using virtual personas."),
            ("What reality television franchise, created by RuPaul Charles in 2009, searches for 'America\\'s Next Drag Superstar'?", "RuPaul's Drag Race", ["Queer Eye", "Project Runway", "America's Next Top Model"], "RuPaul's Drag Race brought drag ballroom performance into mainstream global television, winning multiple Emmy Awards."),
            ("What popular American reality singing competition, based on the British Pop Idol format, debuted on Fox in 2002?", "American Idol", ["The Voice", "The X Factor", "Star Search"], "Hosted by Ryan Seacrest with judges Simon Cowell, Paula Abdul, and Randy Jackson, it launched Kelly Clarkson and Carrie Underwood."),
            ("What British television competition, created by Simon Cowell in 2004, launched One Direction and Leona Lewis?", "The X Factor", ["Britain's Got Talent", "Pop Idol", "Fame Academy"], "The X Factor's category mentoring system dominated British Saturday night television ratings throughout the 2000s."),
            ("What televised dance competition, premiering on ABC in 2005, pairs celebrities with professional ballroom dancers?", "Dancing with the Stars", ["Strictly Come Dancing", "So You Think You Can Dance", "World of Dance"], "Adapted from the BBC's Strictly Come Dancing, it awards winners the coveted Mirrorball Trophy."),
            ("What viral social media challenge in summer 2014 raised over $115 million for Amyotrophic Lateral Sclerosis (ALS) research?", "The ALS Ice Bucket Challenge", ["The Mannequin Challenge", "The Cinnamon Challenge", "The Harlem Shake"], "Millions dumped buckets of ice water over their heads on video and challenged friends, dramatically funding ALS genetic breakthroughs."),
            ("What video trend in late 2016 featured groups of people freezing mid-action while Rae Sremmurd\\'s song 'Black Beatles' played?", "The Mannequin Challenge", ["The Harlem Shake", "The Planking Trend", "The In My Feelings Challenge"], "From sports teams to the White House, viral groups posed completely motionless in elaborate frozen tableaux."),
            ("What internet meme sensation in early 2013 involved people dancing wildly after a bass drop to a dance track by Baauer?", "The Harlem Shake", ["Gangnam Style", "Dab Dance", "Floss Dance"], "Short 30-second clips featuring one masked dancer followed by a chaotic costumed room explosion went viral globally."),
            ("What video game dance move, created by Russell Horning ('Backpack Kid') on Saturday Night Live in 2017, swept elementary schools worldwide?", "The Floss (Flossing)", ["The Dab", "The Orange Justice", "The Carlton"], "Swinging arms back and forth around the hips in alternating motion became a ubiquitous celebration emote in Fortnite."),
            ("What mobile augmented reality game, developed by Niantic in 2016, sent millions of players outside catching virtual monsters?", "Pokemon GO", ["Ingress", "Pikmin Bloom", "Harry Potter: Wizards Unite"], "Pokemon GO achieved historic mobile launch numbers, turning parks and landmarks into bustling real-world PokeStops."),
            ("What word guessing game, created by Josh Wardle in 2021, gave players six tries to guess a daily five-letter word?", "Wordle", ["Heads Up!", "Scrabble GO", "Words with Friends"], "Wordle's clean design and spoiler-free green/yellow shareable emoji grids led to its acquisition by The New York Times."),
            ("What mobile puzzle game, developed by King in 2012, hooked hundreds of millions of players matching colorful sweets in rows?", "Candy Crush Saga", ["Bejeweled Blitz", "Angry Birds", "Fruit Ninja"], "Candy Crush popularized the free-to-play mobile monetization model with consumable lives and booster microtransactions.")
        ],
        "Franchises & Fandoms": [
            ("What sci-fi franchise created by George Lucas in 1977 chronicles the conflict between the Jedi Knights and the Sith Lords?", "Star Wars", ["Star Trek", "Battlestar Galactica", "Dune"], "Star Wars revolutionized modern movie merchandising and film sound design, launching an enduring multimedia saga."),
            ("What utopian sci-fi television and film franchise, created by Gene Roddenberry in 1966, features the starship USS Enterprise?", "Star Trek", ["Star Wars", "Babylon 5", "Stargate"], "Star Trek explored progressive social themes, alien diplomacy, and scientific optimism across multiple television spin-offs."),
            ("What high-fantasy literary epic by J.R.R. Tolkien centers on the quest to destroy the One Ring in the fires of Mount Doom?", "The Lord of the Rings", ["The Wheel of Time", "A Song of Ice and Fire", "The Witcher"], "Peter Jackson's film adaptations won 17 Academy Awards, solidifying Tolkien's Middle-earth as the gold standard of high fantasy."),
            ("What shared superhero media universe, launched in 2008 with the film 'Iron Man', is produced by Kevin Feige?", "The Marvel Cinematic Universe (MCU)", ["The DC Extended Universe", "The Sony Spider-Man Universe", "The MonsterVerse"], "The MCU interconnected dozens of blockbuster films, culminating in the historic box office triumph of Avengers: Endgame."),
            ("What British secret agent franchise, created by novelist Ian Fleming in 1953, features Agent 007 with a license to kill?", "James Bond", ["Mission: Impossible", "Jason Bourne", "Kingsman"], "Eon Productions produced 25 official films starring Sean Connery, Roger Moore, Pierce Brosnan, and Daniel Craig as James Bond."),
            ("What dark fantasy book series by George R.R. Martin was adapted into the global television phenomenon 'Game of Thrones'?", "A Song of Ice and Fire", ["The Kingkiller Chronicle", "The Malazan Book of the Fallen", "The Stormlight Archive"], "The saga of Westeros, featuring the Stark, Lannister, and Targaryen families, captivated audiences with ruthless political intrigue."),
            ("What Japanese media franchise, created by Eiji Tsuburaya and Toho in 1954, features the atomic giant lizard 'King of the Monsters'?", "Godzilla", ["Gamera", "Ultraman", "King Kong"], "Godzilla served as an allegory for nuclear devastation before evolving into a pop culture protector of Earth against alien kaiju."),
            ("What robot toy and media franchise, produced by Hasbro and Takara Tomy since 1984, features Autobots battling Decepticons?", "Transformers", ["G.I. Joe", "Gundam", "Voltron"], "Optimus Prime leads heroic transforming vehicle robots against Megatron in animated shows, comic books, and live-action films."),
            ("What martial arts reptile superhero team, created by Kevin Eastman and Peter Laird in 1984, loves pizza and fights Shredder?", "Teenage Mutant Ninja Turtles (TMNT)", ["Biker Mice from Mars", "Street Sharks", "Battletoads"], "Leonardo, Raphael, Donatello, and Michelangelo became a merchandising juggernaut across 1980s cartoon shows and toys."),
            ("What sci-fi action franchise, created by James Cameron in 1984, features cybernetic assassin androids sent back in time by Skynet?", "The Terminator", ["RoboCop", "The Matrix", "Predator"], "Arnold Schwarzenegger's portrayal of the T-800 delivered iconic catchphrases like 'I\\'ll be back' and 'Hasta la vista, baby.'"),
            ("What sci-fi horror franchise, launched by Ridley Scott in 1979, features Ellen Ripley battling lethal Xenomorph creatures?", "Alien", ["Predator", "The Thing", "Pitch Black"], "H.R. Giger's biomechanical creature design and Sigourney Weaver's heroic performance defined cinematic sci-fi horror."),
            ("What extraterrestrial trophy-hunting warrior franchise began in 1987 with Arnold Schwarzenegger in the Central American jungle?", "Predator", ["Alien", "Independence Day", "Total Recall"], "The dreadlocked, mandibles-bearing Yautja alien uses active camouflage and plasmacasters to hunt worthy prey across galaxies."),
            ("What dystopian young-adult franchise by Suzanne Collins centers on Katniss Everdeen fighting in televised survival games in Panem?", "The Hunger Games", ["Divergent", "The Maze Runner", "The Giver"], "Jennifer Lawrence portrayed the Girl on Fire, sparking a massive boom in dystopian young-adult book and film adaptations."),
            ("What vampire romance franchise by Stephenie Meyer follows Bella Swan and vampire Edward Cullen in the town of Forks, Washington?", "The Twilight Saga", ["The Vampire Diaries", "True Blood", "Shadowhunters"], "Twilight sparked a passionate fan rivalry between 'Team Edward' and 'Team Jacob,' grossing over $3.3 billion at the box office."),
            ("What action film franchise starring Keanu Reeves follows a legendary retired hitman seeking vengeance for the death of his puppy?", "John Wick", ["The Equalizer", "Taken", "Nobody"], "Directed by Chad Stahelski, John Wick revolutionized modern Hollywood action cinema with stylized 'gun-fu' stunt choreography."),
            ("What car-racing turned international heist action franchise stars Vin Diesel as Dominic Toretto, emphasizing 'family'?", "The Fast and the Furious", ["Need for Speed", "Gone in 60 Seconds", "Transporter"], "Evolving from underground street racing in Los Angeles to globe-trotting spy missions, the franchise grossed over $7 billion."),
            ("What dinosaur sci-fi adventure franchise, based on Michael Crichton\\'s 1990 novel, was adapted into a 1993 film by Steven Spielberg?", "Jurassic Park (Jurassic World)", ["The Land Before Time", "King Kong", "Dinotopia"], "Groundbreaking CGI and animatronics brought genetically cloned dinosaurs to life on Isla Nublar with John Williams' soaring score."),
            ("What spy action franchise, starring Tom Cruise as IMF agent Ethan Hunt, is famous for Cruise performing his own death-defying stunts?", "Mission: Impossible", ["Bourne", "Jack Ryan", "007"], "From scaling the Burj Khalifa to hanging off an Airbus A400M in flight, Cruise elevated practical stunt work across seven films."),
            ("What action-adventure franchise, created by George Lucas and Steven Spielberg, stars Harrison Ford as a whip-cracking archaeologist?", "Indiana Jones", ["Tomb Raider", "Uncharted", "National Treasure"], "Dr. Henry 'Indiana' Jones Jr. searched for biblical antiquities like the Ark of the Covenant in Raiders of the Lost Ark."),
            ("What space opera video game franchise, developed by Bungie and 343 Industries, stars the super-soldier Master Chief Petty Officer John-117?", "Halo", ["Gears of War", "Destiny", "Mass Effect"], "Halo revolutionized console first-person shooters on Xbox with regenerating shields, two-weapon limits, and multiplayer LAN parties."),
            ("What sci-fi role-playing game trilogy, developed by BioWare, follows Commander Shepard assembling a crew to stop the Reapers?", "Mass Effect", ["Dragon Age", "Knights of the Old Republic", "Fallout"], "Mass Effect earned acclaim for deep narrative choices, branching companion romances, and rich galactic alien world-building."),
            ("What post-apocalyptic retro-futuristic video game franchise features Vault-Tec shelters, Pip-Boys, and atomic 'Nuka-Cola'?", "Fallout", ["Wasteland", "S.T.A.L.K.E.R.", "Metro 2033"], "Fallout contrasts 1950s atomic age optimism with radiation-mutated ghouls, super mutants, and power armor across the wasteland."),
            ("What fantasy open-world action RPG franchise, developed by CD Projekt Red based on Andrzej Sapkowski\\'s books, stars Geralt of Rivia?", "The Witcher", ["The Elder Scrolls", "Dark Souls", "Dragon's Dogma"], "The Witcher 3: Wild Hunt won Game of the Year honors for mature storytelling and gritty monster-hunting contracts in the Continent."),
            ("What fantasy action-adventure video game series, created by Shigeru Miyamoto and Takashi Tezuka, features Link rescuing Princess Zelda in Hyrule?", "The Legend of Zelda", ["Metroid", "Final Fantasy", "Castlevania"], "From the 1986 NES original to Ocarina of Time and Breath of the Wild, Zelda continually innovated interactive adventure game design."),
            ("What dark action RPG video game series, created by Hidetaka Miyazaki and FromSoftware, is renowned for brutal difficulty and 'bonfires'?", "Dark Souls", ["Bloodborne", "Sekiro", "Elden Ring"], "Dark Souls birthed the 'Soulslike' genre, rewarding patience, pattern memorization, and stamina management against epic bosses."),
            ("What superhero franchise features Batman operating out of the Batcave in Gotham City alongside his butler Alfred Pennyworth?", "Batman (DC Comics)", ["Spider-Man", "Iron Man", "Daredevil"], "Created by Bob Kane and Bill Finger in 1939, Bruce Wayne fights crime using intellect and martial arts after his parents' murder."),
            ("What friendly neighborhood Marvel superhero was bitten by a radioactive spider and lives by the motto 'With great power comes great responsibility'?", "Spider-Man (Peter Parker)", ["Ant-Man", "Wolverine", "Deadpool"], "Created by Stan Lee and Steve Ditko in 1962, Spider-Man became Marvel's flagship global superhero icon."),
            ("What Marvel superhero team of mutants, led by Professor Charles Xavier, fights for peaceful coexistence between mutants and humans?", "The X-Men", ["The Fantastic Four", "The Avengers", "The Defenders"], "Cyclops, Wolverine, Storm, and Jean Grey fight Magneto's Brotherhood, using mutant discrimination as an allegory for civil rights."),
            ("What Marvel superhero team, dubbed 'Earth\\'s Mightiest Heroes', consists of Captain America, Iron Man, Thor, and the Hulk?", "The Avengers", ["The Justice League", "The Guardians of the Galaxy", "The Illuminati"], "First assembled in 1963 by Stan Lee and Jack Kirby, the Avengers unite to face threats no single superhero can withstand."),
            ("What DC superhero team, consisting of Superman, Batman, Wonder Woman, the Flash, and Aquaman, protects Earth from cosmic perils?", "The Justice League", ["The Avengers", "The Teen Titans", "The Suicide Squad"], "Debuting in The Brave and the Bold #28 in 1960, the Justice League is the foundational superhero ensemble team."),
            ("What Japanese manga and anime franchise by Eiichiro Oda follows Monkey D. Luffy and the Straw Hat Pirates searching for the ultimate treasure?", "One Piece", ["Naruto", "Bleach", "Dragon Ball"], "Debuting in 1997, One Piece became the bestselling manga in history with over 500 million copies sold worldwide."),
            ("What martial arts anime and manga franchise, created by Akira Toriyama, follows the Saiyan warrior Goku gathering mystical orbs?", "Dragon Ball (Dragon Ball Z)", ["One Piece", "Naruto", "Yu Yu Hakusho"], "Dragon Ball popularized energy blasts like the Kamehameha and Super Saiyan transformations across international youth culture."),
            ("What ninja anime and manga franchise, created by Masashi Kishimoto, follows an orphaned ninja who dreams of becoming the village Hokage?", "Naruto", ["Bleach", "Hunter x Hunter", "Demon Slayer"], "Naruto Uzumaki's ninja adventures, signature Nine-Tailed Fox spirit, and ninja hand signs achieved massive worldwide fandom."),
            ("What dark fantasy manga and anime franchise by Hajime Isayama features Eren Yeager fighting colossal human-eating giants behind defensive walls?", "Attack on Titan (Shingeki no Kyojin)", ["Tokyo Ghoul", "Fullmetal Alchemist", "Death Note"], "Attack on Titan achieved global pop culture impact through shocking plot twists, political themes, and kinetic ODM-gear animation."),
            ("What British sci-fi television series, premiering on the BBC in 1963, follows an eccentric Time Lord traveling time and space in the TARDIS?", "Doctor Who", ["Torchwood", "Red Dwarf", "Blake's 7"], "The Doctor regenerates into new bodies upon death, allowing over a dozen actors to lead the longest-running sci-fi TV series in history."),
            ("What iconic horror film franchise, created by John Carpenter in 1978, features the masked silent killer Michael Myers stalking babysitters?", "Halloween", ["Friday the 13th", "A Nightmare on Elm Street", "Scream"], "Halloween established the formula for the modern slasher subgenre, accompanied by Carpenter's chilling synthesizer piano theme."),
            ("What horror slasher franchise, created by Wes Craven in 1984, features the razor-gloved dream stalker Freddy Krueger?", "A Nightmare on Elm Street", ["Halloween", "Friday the 13th", "Hellraiser"], "Robert Englund played the burned dream-demon who murdered teenagers in their sleep on Elm Street."),
            ("What horror slasher franchise features the hockey-mask-wearing supernatural killer Jason Voorhees at Camp Crystal Lake?", "Friday the 13th", ["Halloween", "The Texas Chain Saw Massacre", "Child's Play"], "Starting in 1980, Jason Voorhees became an immortal pop culture horror icon across 12 feature films.")
        ],
        "Streaming Hits": [
            ("What Netflix sci-fi horror series, created by the Duffer Brothers in 2016, centers on kids in 1980s Hawkins, Indiana and the 'Upside Down'?", "Stranger Things", ["Dark", "The OA", "Locke & Key"], "Starring Millie Bobby Brown as Eleven, Stranger Things ignited massive 1980s retro-nostalgia and Kate Bush music revivals."),
            ("What South Korean survival drama series, created by Hwang Dong-hyuk and released in 2021, became Netflix\\'s most-watched series of all time?", "Squid Game", ["All of Us Are Dead", "Sweet Home", "Kingdom"], "Squid Game captivated global audiences as debt-ridden contestants competed in deadly children's games for 45.6 billion won."),
            ("What period drama series created by Peter Morgan dramatizes the reign of Queen Elizabeth II from her 1947 wedding into the 21st century?", "The Crown", ["Downton Abbey", "Victoria", "Bridgerton"], "The Crown won dozens of Emmy Awards, recasting its royal ensemble every two seasons with Claire Foy, Olivia Colman, and Imelda Staunton."),
            ("What Netflix historical romance series, produced by Shonda Rhimes, follows the high-society matchmaking season of Regency-era London?", "Bridgerton", ["The Crown", "Outlander", "The Gilded Age"], "Narrated by the mysterious gossip columnist Lady Whistledown, Bridgerton set massive streaming records with diverse, colorful casting."),
            ("What chess coming-of-age miniseries starring Anya Taylor-Joy as orphan prodigy Beth Harmon drove record-breaking global chess board sales in 2020?", "The Queen's Gambit", ["Pawn Sacrifice", "Searching for Bobby Fischer", "Magnus"], "Beth Harmon's rise through international chess tournaments while battling addiction captivated over 62 million households in its first month."),
            ("What Spanish heist crime drama series, created by Álex Pina, follows a criminal mastermind known as 'The Professor' robbing the Royal Mint of Spain?", "Money Heist (La Casa de Papel)", ["Elite", "Narcos", "Lupin"], "Sporting red jumpsuits and Salvador Dalí masks, the crew's Italian anti-fascist anthem 'Bella Ciao' became a global protest and pop symbol."),
            ("What crime drama series chronicles the rise and fall of Colombian drug kingpin Pablo Escobar and the Medellín Cartel?", "Narcos", ["Breaking Bad", "Ozark", "El Chapo"], "Starring Wagner Moura as Pablo Escobar and Pedro Pascal as DEA agent Javier Peña, Narcos achieved critical acclaim for gritty realism."),
            ("What dark financial crime drama series stars Jason Bateman and Laura Linney laundering drug cartel money through the Missouri Ozarks?", "Ozark", ["Bloodline", "Better Call Saul", "Succession"], "Ozark earned widespread acclaim and multiple Emmy Awards, particularly for Julia Garner's powerhouse performance as Ruth Langmore."),
            ("What live-action Star Wars series on Disney+, created by Jon Favreau in 2019, introduced Din Djarin and 'Baby Yoda' (Grogu)?", "The Mandalorian", ["Andor", "The Book of Boba Fett", "Obi-Wan Kenobi"], "Pedro Pascal's armored bounty hunter guarding Grogu spawned the catchphrase 'This is the Way' and anchored Disney+'s streaming launch."),
            ("What critically acclaimed Star Wars spy thriller series on Disney+, created by Tony Gilroy, serves as a grounded prequel to Rogue One?", "Andor", ["The Mandalorian", "Ahsoka", "Obi-Wan Kenobi"], "Diego Luna reprised his role as Cassian Andor, earning universal praise for mature political drama and tension without lightsabers."),
            ("What Marvel Studios miniseries on Disney+ featured Wanda Maximoff trapping an entire New Jersey town inside classic sitcom eras?", "WandaVision", ["Loki", "The Falcon and the Winter Soldier", "Hawkeye"], "Elizabeth Olsen and Paul Bettany starred in a mind-bending mystery exploring grief through homages to The Dick Van Dyke Show and Bewitched."),
            ("What Marvel Disney+ series follows Tom Hiddleston\\'s God of Mischief navigating the bureaucratic Time Variance Authority (TVA)?", "Loki", ["WandaVision", "Moon Knight", "Secret Invasion"], "Loki introduced the Multiverse concept and Kang the Conqueror, culminating in an acclaimed emotional arc across two seasons."),
            ("What satirical superhero black comedy series on Amazon Prime Video, based on Garth Ennis\\'s comic, features the corrupt superhero team 'The Seven'?", "The Boys", ["Invincible", "Peacemaker", "Watchmen"], "Karl Urban's Billy Butcher battles Antony Starr's psychopathic corporate-sponsored superhero Homelander with violent dark humor."),
            ("What adult animated superhero series on Amazon Prime Video, created by Robert Kirkman, follows Mark Grayson discovering his father\\'s dark alien secrets?", "Invincible", ["The Boys", "Harley Quinn", "Castlevania"], "Starring Steven Yeun and J.K. Simmons as Omni-Man, Invincible earned acclaim for shocking subversion of superhero tropes."),
            ("What romantic comedy-drama series on Apple TV+ stars Jason Sudeikis as an optimistic American college football coach managing a British soccer team?", "Ted Lasso", ["Shrinking", "The Morning Show", "Mythic Quest"], "Ted Lasso's yellow 'BELIEVE' sign and heartwarming optimism won consecutive Primetime Emmy Awards for Outstanding Comedy Series."),
            ("What workplace psychological thriller series on Apple TV+, directed by Ben Stiller, stars Adam Scott with surgically split work and personal memories?", "Severance", ["Black Mirror", "Homecoming", "Silou"], "Employees at Lumon Industries undergo the severance procedure, exploring corporate dystopian horror with dark satirical precision."),
            ("What Apple TV+ sci-fi series stars Lee Pace in an epic multi-century space saga loosely adapted from Isaac Asimov\\'s classic novels?", "Foundation", ["For All Mankind", "Invasion", "Silo"], "Foundation chronicles the algorithmic math predictions of Hari Seldon attempting to shorten the dark age following galactic empire collapse."),
            ("What post-apocalyptic drama series on HBO, adapted by Craig Mazin and Neil Druckmann from the Naughty Dog video game, stars Pedro Pascal and Bella Ramsey?", "The Last of Us", ["The Walking Dead", "Station Eleven", "Sweet Tooth"], "Joel escorts immune teenager Ellie across a fungal cordyceps-ravaged America, earning massive critical acclaim and 24 Emmy nominations."),
            ("What fantasy prequel series to Game of Thrones, based on George R.R. Martin\\'s 'Fire & Blood', chronicles the Targaryen civil war 'The Dance of the Dragons'?", "House of the Dragon", ["The Lord of the Rings: The Rings of Power", "The Witcher", "Wheel of Time"], "Starring Emma D'Arcy and Matt Smith, House of the Dragon broke HBO premiere streaming records with vicious family political betrayal."),
            ("What Amazon Prime Video high-fantasy series, set in the Second Age of Middle-earth, depicts the forging of the Rings of Power and the rise of Sauron?", "The Lord of the Rings: The Rings of Power", ["House of the Dragon", "The Wheel of Time", "Shadow and Bone"], "Produced with an unprecedented $1 billion commitment, it depicts the golden realm of Númenor and elf commander Galadriel."),
            ("What fantasy series on Amazon Prime Video, adapted from Robert Jordan\\'s bestsellers, stars Rosamund Pike as the Aes Sedai Moiraine?", "The Wheel of Time", ["The Rings of Power", "The Witcher", "His Dark Materials"], "Moiraine searches for the reincarnation of the Dragon Reborn destined to either save or break the world."),
            ("What dark comedy-drama series on HBO, created by Jesse Armstrong, chronicles the vicious power struggles among the billionaire Roy siblings?", "Succession", ["Billions", "Yellowstone", "Industry"], "Logan Roy pits his adult children (Kendall, Shiv, Roman, Connor) against each other for control of global media conglomerate Waystar Royco."),
            ("What psychological satire anthology series on HBO, created by Mike White, examines the dark dysfunctions of wealthy guests at luxury tropical resorts?", "The White Lotus", ["Succession", "Nine Perfect Strangers", "The Resort"], "Each season takes place in a different exotic location (Hawaii, Sicily), earning Jennifer Coolidge consecutive Emmy Awards as Tanya McQuoid."),
            ("What Netflix sci-fi anthology series, created by Charlie Brooker, explores the dark, unintended consequences of near-future technologies?", "Black Mirror", ["Love, Death & Robots", "The Twilight Zone", "Altered Carbon"], "From social credit scores ('Nosedive') to robotic guard dogs ('Metalhead'), Black Mirror examined human dependency on digital screens."),
            ("What adult animated anthology series on Netflix, produced by Tim Miller and David Fincher, features standalone animated sci-fi and horror stories?", "Love, Death & Robots", ["Arcane", "Castlevania", "Blue Eye Samurai"], "Showcasing world-class international animation studios, it earned multiple Emmy Awards for cutting-edge photorealistic CGI shorts."),
            ("What critically acclaimed animated action-fantasy series on Netflix, based on Riot Games\\' League of Legends, explores the conflict between Piltover and Zaun?", "Arcane", ["Castlevania", "DOTA: Dragon's Blood", "Cyberpunk: Edgerunners"], "Produced by French animation studio Fortiche, Arcane earned universal acclaim for painterly visual aesthetics and the tragic sisterhood of Vi and Jinx."),
            ("What high-octane anime series on Netflix, produced by Studio Trigger and CD Projekt Red, is set in the dystopian future of Night City?", "Cyberpunk: Edgerunners", ["Ghost in the Shell", "Akira", "Psycho-Pass"], "David Martinez becomes an outlaw mercenary after personal tragedy, earning Anime of the Year honors and reviving Cyberpunk 2077 player numbers."),
            ("What coming-of-age supernatural mystery series on Netflix stars Jenna Ortega as the deadpan Addams Family daughter at Nevermore Academy?", "Wednesday", ["Chilling Adventures of Sabrina", "Locke & Key", "Riverdale"], "Directed in part by Tim Burton, Wednesday became one of Netflix's most-watched English series, fueled by Ortega's viral gothic dance."),
            ("What post-apocalyptic TV series on Amazon Prime Video, created by Jonathan Nolan and Lisa Joy, adapts the retro-futuristic nuclear wasteland video games?", "Fallout", ["The Last of Us", "Twisted Metal", "Halo"], "Ella Purnell stars as optimistic Vault Dweller Lucy emerging into the radioactive California wasteland alongside Walton Goggins' mutant Ghoul."),
            ("What Netflix period mystery series stars Henry Cavill as Sherlock Holmes and Millie Bobby Brown as his spirited detective younger sister?", "Enola Holmes", ["The Alienist", "Sherlock", "Lupin"], "Enola breaks the fourth wall while outwitting her famous brother across Victorian London conspiracy mysteries."),
            ("What fast-paced restaurant drama series on FX/Hulu stars Jeremy Allen White as an elite fine-dining chef returning to run his family\\'s Chicago beef sandwich joint?", "The Bear", ["Boiling Point", "Sweetbitter", "Chef's Table"], "The Bear earned widespread acclaim for its intense kitchen panic, single-take episodes, and shouting of 'Yes, Chef!'"),
            ("What hit modern Western drama series, created by Taylor Sheridan and starring Kevin Costner as patriarch John Dutton, airs on Paramount Network?", "Yellowstone", ["1883", "1923", "Longmire"], "Yellowstone became the highest-rated scripted drama on American television, spawning prequel spinoffs across the Dutton ranch empire."),
            ("What true-crime comedy mystery series on Hulu stars Steve Martin, Martin Short, and Selena Gomez investigating murders in their Manhattan apartment building?", "Only Murders in the Building", ["Dead to Me", "Search Party", "The Flight Attendant"], "The unlikely trio records a true-crime podcast while solving bizarre homicides inside the storied Arconia building."),
            ("What Apple TV+ psychological drama series stars Jennifer Aniston and Reese Witherspoon navigating the cutthroat corporate politics of a morning news show?", "The Morning Show", ["The Newsroom", "Broadcast News", "Succession"], "Inspired by Brian Stelter's book, the series explored the #MeToo movement and network executive maneuvering."),
            ("What Netflix teen drama comedy series, created by Laurie Nunn, follows socially awkward teenager Otis Milburn running an underground clinic at school?", "Sex Education", ["Skins", "Heartstopper", "Euphoria"], "Asa Butterfield and Gillian Anderson star in an acclaimed progressive exploration of adolescent relationships and identity."),
            ("What Netflix live-action adaptation of Eiichiro Oda\\'s pirate manga stars Iñaki Godoy as the stretchy rubber pirate Monkey D. Luffy?", "One Piece (Live Action)", ["Cowboy Bebop", "Death Note", "Avatar: The Last Airbender"], "Overcoming the curse of bad anime adaptations, One Piece earned critical and fan praise with direct involvement from creator Eiichiro Oda."),
            ("What gripping HBO/Sky miniseries dramatized the catastrophic 1986 nuclear power plant explosion in Soviet Ukraine with haunting scientific realism?", "Chernobyl", ["The Plot Against America", "Dopesick", "Five Days at Memorial"], "Created by Craig Mazin and starring Jared Harris and Stellan Skarsgård, Chernobyl won 10 Emmy Awards, asking 'What is the cost of lies?'")
        ],
        "Trivia Milestones": [
            ("What is the all-time highest-grossing film at the global worldwide box office (not adjusted for inflation), grossing over $2.9 billion?", "Avatar (2009)", ["Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"], "Directed by James Cameron, Avatar's 3D cinematic spectacle reclaimed the all-time global box office crown with international re-releases."),
            ("Who was the first person in entertainment history to achieve EGOT status by winning an Emmy, Grammy, Oscar, and Tony Award?", "Richard Rodgers", ["Rita Moreno", "Mel Brooks", "Audrey Hepburn"], "Legendary composer Richard Rodgers achieved the milestone in 1962, followed by Rita Moreno who became the first Latina and second person in 1977."),
            ("Who holds the record for winning the most Academy Awards in history, earning 22 competitive Oscars from 59 nominations?", "Walt Disney", ["Alfred Hitchcock", "Steven Spielberg", "John Williams"], "Walt Disney dominated animation and documentary short categories, winning four Oscars in a single evening in 1954."),
            ("What film music composer holds the record for the most Academy Award nominations of any living person, with over 54 nominations?", "John Williams", ["Hans Zimmer", "Ennio Morricone", "Alan Menken"], "Williams composed the legendary scores for Star Wars, Jaws, Indiana Jones, Jurassic Park, E.T., and Harry Potter."),
            ("What music artist holds the all-time record for winning the most Grammy Awards in history, with 32 career wins?", "Beyoncé", ["Georg Solti", "Quincy Jones", "Alison Krauss"], "Beyoncé surpassed Hungarian-British conductor Sir Georg Solti in 2023, cementing her place in recording academy history."),
            ("What American singer-songwriter made Grammy history in 2024 by becoming the first artist ever to win Album of the Year four times?", "Taylor Swift", ["Frank Sinatra", "Stevie Wonder", "Paul Simon"], "Swift won for Fearless (2009), 1989 (2015), Folklore (2020), and Midnights (2024)."),
            ("What pop album by Michael Jackson, released in November 1982 by Epic Records, remains the bestselling music album in world history?", "Thriller", ["Bad", "Back in Black", "The Dark Side of the Moon"], "Produced by Quincy Jones, Thriller produced seven Top 10 singles and sold an estimated 70+ million copies worldwide."),
            ("What Broadway musical by Lin-Manuel Miranda set an all-time record by earning 16 Tony Award nominations in 2016?", "Hamilton", ["The Producers", "The Lion King", "Wicked"], "Hamilton blended hip-hop, R&B, and traditional show tunes, winning 11 Tonys, a Grammy, and the Pulitzer Prize for Drama."),
            ("What Broadway musical, created by Mel Brooks in 2001, holds the record for winning the most Tony Awards in a single night with 12 wins?", "The Producers", ["Hamilton", "Cabaret", "Billy Elliot"], "Starring Nathan Lane and Matthew Broderick, The Producers swept every category it was nominated for, breaking Hello, Dolly!'s 37-year record."),
            ("What television sitcom series finale, broadcast on February 28, 1983, remains the most-watched scripted television broadcast in American history?", "M*A*S*H ('Goodbye, Farewell and Amen')", ["Cheers", "Seinfeld", "Friends"], "Over 105 million viewers (a 60.2 rating and 77 share) tuned in to watch the final episode of the 4077th Mobile Army Surgical Hospital."),
            ("What long-running game show, created by Merv Griffin in 1964, features contestants phrasing their answers in the form of a question?", "Jeopardy!", ["Wheel of Fortune", "The Price is Right", "Family Feud"], "Hosted by Alex Trebek for 36 years, Jeopardy! won a record 43 Daytime Emmy Awards."),
            ("What legendary Jeopardy! contestant won 74 consecutive regular-season games in 2004, taking home over $2.5 million before becoming the show\\'s host?", "Ken Jennings", ["James Holzhauer", "Brad Rutter", "Amy Schneider"], "Jennings' historic 74-game streak captivated America and redefined modern trivia mastery."),
            ("What daytime game show, premiering on CBS in 1972 with host Bob Barker, is the longest-running game show in American television history?", "The Price is Right", ["Let's Make a Deal", "Wheel of Fortune", "Jeopardy!"], "Contestants 'Come on down!' to Bidder's Row, play Plinko, and spin the giant Showcase Showdown Wheel."),
            ("Who was the creator and original host of Soul Train, the historic syndicated music and dance television program debuting in 1971?", "Don Cornelius", ["Dick Clark", "Ed Sullivan", "Casey Kasem"], "Don Cornelius concluded every energetic episode of African-American musical talent with 'Love, peace, and soul!'"),
            ("What legendary television host interviewed prominent guests at the desk of NBC\\'s The Tonight Show for 30 years from 1962 to 1992?", "Johnny Carson", ["Jay Leno", "David Letterman", "Jack Paar"], "Announced by Ed McMahon with 'Heeeeere's Johnny!', Carson defined late-night American television comedy."),
            ("What syndicated evening game show, hosted by Pat Sajak and Vanna White for over four decades, challenges contestants to solve word puzzles?", "Wheel of Fortune", ["Jeopardy!", "Scrabble", "Password"], "Spinning the giant carnival wheel to buy vowels and guess consonants made it a staple of American evening syndication."),
            ("What British reality game show, hosted by Chris Tarrant and later Regis Philbin in America, debuted the dramatic lifelines format in 1998?", "Who Wants to Be a Millionaire?", ["The Weakest Link", "Deal or No Deal", "Golden Balls"], "Contestants used 50:50, Phone-a-Friend, and Ask the Audience while climbing a 15-question ladder to $1,000,000."),
            ("What animated sitcom, created by Matt Groening and debuting in December 1989, is the longest-running American scripted primetime TV series?", "The Simpsons", ["South Park", "Family Guy", "Bob's Burgers"], "Chronicling the adventures of Homer, Marge, Bart, Lisa, and Maggie in Springfield, it has aired over 750 episodes."),
            ("What stop-motion paper-cutout animated comedy, created by Trey Parker and Matt Stone in 1997, satirizes current events with rapid production cycles?", "South Park", ["The Simpsons", "Family Guy", "King of the Hill"], "Stan, Kyle, Cartman, and Kenny navigate Colorado satire, written and animated in just six days per episode."),
            ("What sketch comedy institution, created by Lorne Michaels, has broadcast live from Studio 8H in Rockefeller Center since October 11, 1975?", "Saturday Night Live (SNL)", ["The Carol Burnett Show", "Mad TV", "In Living Color"], "Opening with 'Live from New York, it's Saturday Night!', SNL launched generations of comedy stars from Eddie Murphy to Will Ferrell."),
            ("What animated film, directed by Hayao Miyazaki and released by Studio Ghibli in 2001, won the Academy Award for Best Animated Feature?", "Spirited Away", ["Princess Mononoke", "My Neighbor Totoro", "Howl's Moving Castle"], "Chihiro's journey through a bathhouse of spirits became the first non-English hand-drawn animation to win an Oscar."),
            ("What 1995 computer-animated buddy comedy, produced by Pixar and directed by John Lasseter, was the first fully computer-animated feature film?", "Toy Story", ["A Bug's Life", "Monsters, Inc.", "Shrek"], "Woody and Buzz Lightyear proved CGI feature films could capture deep emotional storytelling, launching Pixar's legacy."),
            ("What 1937 Disney production was the first full-length cel-animated feature film in motion picture history?", "Snow White and the Seven Dwarfs", ["Pinocchio", "Fantasia", "Bambi"], "Dubbed 'Disney's Folly' during production, Snow White grossed historic box office revenues and won a special Academy Award with seven miniature statuettes."),
            ("What live-action superhero film became the first superhero movie ever nominated for the Academy Award for Best Picture in 2019?", "Black Panther", ["The Dark Knight", "The Avengers", "Iron Man"], "Directed by Ryan Coogler, Black Panther earned $1.3 billion and won three Oscars for costume design, production design, and original score."),
            ("Who was the first woman in history to win the Academy Award for Best Director, winning in 2010 for 'The Hurt Locker'?", "Kathryn Bigelow", ["Jane Campion", "Chloé Zhao", "Greta Gerwig"], "Bigelow made cinematic history with her intense psychological examination of an Iraq War bomb disposal team."),
            ("What 2019 South Korean black comedy thriller, directed by Bong Joon-ho, became the first non-English-language film to win Best Picture at the Oscars?", "Parasite", ["Roma", "Life Is Beautiful", "Crouching Tiger, Hidden Dragon"], "Parasite swept Best Picture, Best Director, Best Original Screenplay, and Best International Feature Film."),
            ("What annual music concert tour, launched by Taylor Swift in March 2023, became the first concert tour in history to gross over $1 billion?", "The Eras Tour", ["The Renaissance World Tour", "The Wall Live", "U2 360 Tour"], "Spanning 44 songs across 10 musical eras, the three-hour stadium spectacle generated historic tourism revenue and an accompanying concert film."),
            ("What rock band\\'s historic 1964 performance on The Ed Sullivan Show was watched by an estimated 73 million Americans, launching the British Invasion?", "The Beatles", ["The Rolling Stones", "The Who", "The Kinks"], "Beatlemania swept America when John, Paul, George, and Ringo played 'I Want to Hold Your Hand' live on Sunday evening."),
            ("What massive four-day rock festival in August 1969 drew an estimated 400,000 young people to Max Yasgur\\'s dairy farm in Bethel, New York?", "The Woodstock Music & Art Fair", ["Altamont Free Concert", "Monterey Pop Festival", "Isle of Wight Festival"], "Jimi Hendrix, Janis Joplin, and The Who performed in a defining counterculture gathering promoting peace, love, and music."),
            ("What dual benefit concert, held simultaneously in London and Philadelphia on July 13, 1985, raised funds for Ethiopian famine relief?", "Live Aid", ["Farm Aid", "Concert for Bangladesh", "USA for Africa"], "Organized by Bob Geldof and Midge Ure, Live Aid was viewed by 1.9 billion people and featured Queen's historic Wembley performance."),
            ("What song by USA for Africa, written by Michael Jackson and Lionel Richie in 1985, became the fastest-selling American pop single in history?", "We Are the World", ["Do They Know It's Christmas?", "Tears Are Not Enough", "That's What Friends Are For"], "Conducted by Quincy Jones, 45 pop superstars united to raise tens of millions of dollars for African famine relief."),
            ("What popular dance and rhythm video game, released by RedOctane and Harmonix in 2005, used a plastic Gibson SG guitar controller?", "Guitar Hero", ["Rock Band", "Dance Dance Revolution", "Beat Saber"], "Guitar Hero sparked a worldwide rhythm game craze, introducing classic rock hits to millions of teenage players."),
            ("What British reality television dating show features single 'islanders' living in a luxury villa in Mallorca looking for love?", "Love Island", ["Too Hot to Handle", "The Bachelor", "Love Is Blind"], "Coupling up to avoid elimination and win public votes, Love Island became a dominant summer ratings powerhouse on ITV2."),
            ("What long-running syndicated morning game show, created by Steve Harvey in recent years, pits two families against each other to guess survey answers?", "Family Feud", ["Card Sharks", "Match Game", "Press Your Luck"], "Created by Mark Goodson in 1976 with original host Richard Dawson, the show's survey reveals remain iconic daytime TV."),
            ("What music video, directed by Mark Romanek for Michael and Janet Jackson in 1995, set a Guinness World Record as the most expensive music video ever made?", "Scream ($7 Million)", ["Bad", "Die Another Day", "Work Bitch"], "Set aboard a stark CGI spaceship, the high-budget video won the Grammy Award for Best Short Form Music Video."),
            ("What classic television game show featured the phrase 'No Whammies, No Whammies, STOP!' as contestants avoided red animated goblins?", "Press Your Luck", ["High Rollers", "Tic-Tac-Dough", "Sale of the Century"], "Michael Larson famously exploited a predictable lighting pattern on the big board in 1984 to win over $110,000 without hitting a single Whammy."),
            ("What annual American live television spectacular has hosted iconic halftime performances by Prince, Michael Jackson, and Shakira with J-Lo?", "The Super Bowl Halftime Show", ["The Grammy Awards", "The Academy Awards", "The MTV Video Music Awards"], "Drawing over 100 million live television viewers, the Super Bowl halftime stage is considered the most coveted performance showcase in live entertainment.")
        ]
    }

print("Loaded Entertainment items successfully.")
'''

target_path = os.path.abspath('scripts/generators/data_culture_part1.py')
with open(target_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Created scripts/generators/data_culture_part1.py with Entertainment.")
