"""
gen_medical.py
Generates 150 distinct Medical questions:
- Medical Terminology (38)
- Clinical Assessment (38)
- Cardiology (37)
- Pathophysiology (37)
"""

from .utils import rotate_options, slugify

def generate_medical_json(registry):
    cat = "Medical"
    diffs = ["easy", "medium", "hard"]
    questions = []
    idx = 1

    # 1. Medical Terminology (38)
    terms = [
        ("What does the medical suffix '-ectomy' signify?", "Surgical excision or removal", ["Surgical repair or reconstruction", "Surgical creation of an artificial opening", "Temporary surgical incision into an organ"], "The suffix '-ectomy' denotes surgical removal of an anatomical structure, such as in appendectomy or cholecystectomy."),
        ("What does the medical suffix '-otomy' signify?", "Surgical incision or cutting into an organ", ["Surgical excision", "Surgical fusion of a joint", "Microscopic visual examination"], "The suffix '-otomy' denotes making an incision or opening into an organ, such as in laparotomy or tracheotomy."),
        ("What does the medical suffix '-ostomy' signify?", "Surgical creation of an artificial opening or stoma", ["Surgical removal", "Surgical crushing of a stone", "Surgical fixation of an organ"], "The suffix '-ostomy' refers to surgically creating an opening to the outside, as in colostomy or ileostomy."),
        ("What does the medical suffix '-plasty' signify?", "Surgical repair or plastic reconstruction", ["Surgical destruction", "Surgical suture", "Surgical puncture to withdraw fluid"], "The suffix '-plasty' denotes surgical restoration or repair of a tissue or structure, as in rhinoplasty."),
        ("What does the medical suffix '-centesis' signify?", "Surgical puncture to aspirate fluid", ["Surgical fixation", "Surgical incision", "Visual inspection with a scope"], "The suffix '-centesis' refers to needle aspiration of fluid from a cavity, as in amniocentesis or thoracentesis."),
        ("What does the prefix 'brady-' indicate in clinical terminology?", "Abnormally slow rate", ["Abnormally rapid rate", "Irregular pattern", "Elevated pressure"], "'Brady-' is derived from the Greek 'bradys' meaning slow, as in bradycardia (resting heart rate < 60 bpm)."),
        ("What does the prefix 'tachy-' indicate in clinical terminology?", "Abnormally fast or rapid rate", ["Abnormally slow rate", "Absence of activity", "Painful sensation"], "'Tachy-' is derived from the Greek 'tachys' meaning swift or rapid, as in tachycardia (heart rate > 100 bpm)."),
        ("What does the prefix 'dys-' denote?", "Difficult, painful, or abnormal function", ["Excessive or elevated", "Deficient or below normal", "Within or inside"], "The prefix 'dys-' denotes difficult, painful, or impaired physiological function, as in dyspnea or dysphagia."),
        ("What does the prefix 'hyper-' denote?", "Above normal, excessive, or increased", ["Below normal or deficient", "Equal or identical", "Outside or surrounding"], "'Hyper-' indicates excessive or elevated levels, such as in hypertension or hyperglycemia."),
        ("What does the prefix 'hypo-' denote?", "Below normal, deficient, or decreased", ["Above normal or excessive", "Surrounding or around", "Rapid or turbulent"], "'Hypo-' denotes decreased or deficient levels, such as in hypotension or hypoglycemia."),
        ("What anatomical organ is designated by the root 'nephro-' or 'reno-'?", "The kidney", ["The liver", "The spleen", "The lung"], "'Nephro-' (Greek) and 'reno-' (Latin) both refer specifically to the renal kidney structures."),
        ("What anatomical organ is designated by the root 'hepato-'?", "The liver", ["The pancreas", "The gall bladder", "The stomach"], "'Hepato-' refers to the liver, as in hepatitis (liver inflammation) or hepatomegaly (liver enlargement)."),
        ("What anatomical structure is designated by the root 'arthro-'?", "A joint", ["A bone", "A muscle tendon", "A nerve ganglion"], "'Arthro-' denotes an anatomical joint, as in arthritis (joint inflammation) or arthroscopy."),
        ("What anatomical tissue is designated by the root 'osteo-'?", "Bone tissue", ["Muscle tissue", "Cartilage", "Adipose tissue"], "'Osteo-' stems from the Greek 'osteon' for bone, as in osteoporosis or osteomyelitis."),
        ("What anatomical organ is designated by the root 'cholecysto-'?", "The gall bladder", ["The urinary bladder", "The stomach", "The spleen"], "'Cholecysto-' denotes the gallbladder; cholecystitis is acute inflammation of the gallbladder."),
        ("What does the suffix '-itis' indicate?", "Inflammation of a specified organ or tissue", ["Degenerative disease", "Malignant neoplasm", "Surgical removal"], "The suffix '-itis' denotes an active inflammatory response in tissue, such as in bronchitis or gastritis."),
        ("What does the suffix '-algia' indicate?", "Pain in a specified area", ["Fever", "Paralysis", "Enlargement"], "The suffix '-algia' refers to localized or radiating pain, such as in fibromyalgia, neuralgia, or myalgia."),
        ("What does the suffix '-megaly' indicate?", "Abnormal enlargement of an organ", ["Atrophy of tissue", "Inflammation", "Narrowing of a lumen"], "The suffix '-megaly' denotes abnormal anatomical enlargement, such as in cardiomegaly or splenomegaly."),
        ("What does the suffix '-pathy' indicate?", "Disease or morbid condition of an organ", ["Surgical reconstruction", "Measurement tool", "Paralysis"], "The suffix '-pathy' denotes a disease state, such as in cardiomyopathy, neuropathy, or retinopathy."),
        ("What does the suffix '-emia' denote?", "Presence of a substance in the blood", ["Presence in the urine", "Excess in cerebrospinal fluid", "Lymphatic blockage"], "The suffix '-emia' refers to blood conditions, such as in bacteremia, anemia, or hypokalemia."),
        ("What medical term describes difficulty or discomfort when swallowing?", "Dysphagia", ["Dysphasia", "Dyspepsia", "Dystonia"], "Dysphagia refers to difficulty moving food or liquids through the pharynx and esophagus."),
        ("What medical term describes impairment or difficulty in language comprehension or expression?", "Dysphasia (or aphasia)", ["Dysphagia", "Dyspraxia", "Dysarthria"], "Dysphasia refers to a speech/language disorder resulting from brain injury; dysarthria refers to motor articulation."),
        ("What medical term describes indigestion or epigastric discomfort after eating?", "Dyspepsia", ["Dysphagia", "Dyspnea", "Dyskinesia"], "Dyspepsia describes upper abdominal symptoms including fullness, burning, and epigastric discomfort."),
        ("What medical term describes shortness of breath or laboured breathing?", "Dyspnea", ["Apnea", "Bradypnea", "Eupnea"], "Dyspnea is the subjective clinical sensation of uncomfortable or difficult breathing."),
        ("What medical term describes bluish discoloration of the skin and mucous membranes caused by deoxygenated hemoglobin?", "Cyanosis", ["Erythema", "Jaundice", "Pallor"], "Cyanosis indicates hypoxemia, presenting when unoxygenated hemoglobin exceeds 5 g/dL in capillary blood."),
        ("What medical term describes redness of the skin resulting from capillary congestion and dilation?", "Erythema", ["Purpura", "Ecchymosis", "Petechiae"], "Erythema is cutaneous redness produced by vascular dilation during localized inflammation or irritation."),
        ("What medical term describes an abnormal accumulation of fluid within interstitial spaces?", "Edema", ["Exudate", "Erythema", "Hematoma"], "Edema occurs when microvascular filtration exceeds lymphatic drainage capacity in tissues."),
        ("What medical term describes a nosebleed originating from nasal mucosa?", "Epistaxis", ["Hemoptysis", "Hematemesis", "Melena"], "Epistaxis refers to hemorrhaging from anterior or posterior vessels in the nasal septum (Kiesselbach's plexus)."),
        ("What medical term describes coughing up blood or blood-tinged sputum from the respiratory tract?", "Hemoptysis", ["Hematemesis", "Epistaxis", "Melena"], "Hemoptysis is expectoration of blood originating from the bronchi, larynx, trachea, or lungs."),
        ("What medical term describes vomiting blood originating from the upper gastrointestinal tract?", "Hematemesis", ["Hemoptysis", "Hematochezia", "Melena"], "Hematemesis refers to vomiting bright red blood or dark 'coffee-ground' emesis from upper GI bleeding."),
        ("What medical term describes dark, tarry, foul-smelling stools containing digested blood?", "Melena", ["Hematochezia", "Steatorrhea", "Obstipation"], "Melena indicates upper gastrointestinal bleeding where hemoglobin has been degraded by gastric acid and bacteria."),
        ("What medical term describes the passage of fresh, bright red blood from the rectum?", "Hematochezia", ["Melena", "Hematuria", "Hemoptysis"], "Hematochezia typically denotes bleeding from the lower gastrointestinal tract (colon, rectum, or anus)."),
        ("What medical term describes the presence of red blood cells in the urine?", "Hematuria", ["Proteinuria", "Bacteriuria", "Oliguria"], "Hematuria refers to microscopic or macroscopic blood in the urine, arising from kidneys, ureters, or bladder."),
        ("What medical term describes severe, intense itching of the cutaneous skin?", "Pruritus", ["Urticaria", "Xerosis", "Psoriasis"], "Pruritus is the dermatological sensation that provokes the desire to scratch."),
        ("What medical term describes temporary cessation of breathing?", "Apnea", ["Dyspnea", "Orthopnea", "Tachypnea"], "Apnea is the complete suspension of breathing, as in obstructive sleep apnea or respiratory arrest."),
        ("What medical term describes temporary loss of consciousness due to transient cerebral hypoperfusion?", "Syncope", ["Vertigo", "Delirium", "Stupor"], "Syncope (fainting) is characterized by rapid onset, brief duration, and spontaneous complete recovery."),
        ("What medical term describes partial or complete absence of hair from areas where it normally grows?", "Alopecia", ["Hirsutism", "Erythema", "Seborrhea"], "Alopecia refers to hair loss, which may be autoimmune (alopecia areata) or androgenetic."),
        ("What medical term describes profuse, excessive sweating?", "Diaphoresis", ["Anhidrosis", "Hyperesthesia", "Paresthesia"], "Diaphoresis refers to heavy perspiration, often associated with shock, myocardial infarction, or fever defervescence.")
    ]

    for item in terms:
        diff = diffs[(idx - 1) % 3]
        target_idx = (idx - 1) % 4
        opts = rotate_options(item[1], item[2], target_idx)
        q_id = f"medical-medical-terminology-{idx:04d}"
        q_obj = {
            "id": q_id,
            "category": cat,
            "subcategory": "Medical Terminology",
            "difficulty": diff,
            "question": item[0].strip(),
            "options": opts,
            "correctAnswer": target_idx,
            "explanation": item[3].strip(),
            "tags": ["medical", "medical-terminology", diff],
            "active": True
        }
        questions.append(registry.validate_and_register(q_obj))
        idx += 1

    # 2. Clinical Assessment (38)
    assessments = [
        ("Which diagnostic tool is primarily utilized to evaluate the electrical conduction system of the human heart?", "Electrocardiogram (ECG / EKG)", ["Echocardiogram (cardiac ultrasound)", "Electromyogram (EMG)", "Electroencephalogram (EEG)"], "An electrocardiogram records electrical voltage potentials generated by myocardial depolarization over time."),
        ("What is the standard physiological threshold definition of tachycardia in a resting adult?", "Heart rate exceeding 100 beats per minute", ["Heart rate exceeding 80 beats per minute", "Heart rate exceeding 120 beats per minute", "Heart rate exceeding 140 beats per minute"], "Normal resting adult heart rate is 60 to 100 bpm; rates over 100 bpm constitute sinus or ectopic tachycardia."),
        ("What is the standard physiological definition of bradycardia in an adult at rest?", "Heart rate below 60 beats per minute", ["Heart rate below 50 beats per minute", "Heart rate below 70 beats per minute", "Heart rate below 40 beats per minute"], "Bradycardia in adults is defined clinically as a resting ventricular heart rate below 60 bpm."),
        ("What does the acronym FAST evaluate during emergency clinical assessment?", "Acute stroke signs (Face drooping, Arm weakness, Speech difficulty, Time to call 911)", ["Acute cardiac arrest", "Traumatic brain concussion", "Severe anaphylactic allergy"], "The FAST algorithm facilitates rapid public and clinical recognition of ischemic and hemorrhagic stroke."),
        ("What is the normal fasting plasma glucose range in a healthy, non-diabetic adult?", "70 to 99 mg/dL", ["40 to 60 mg/dL", "126 to 140 mg/dL", "100 to 125 mg/dL"], "Normal fasting blood sugar is 70-99 mg/dL; 100-125 indicates impaired fasting glucose; >=126 indicates diabetes."),
        ("What heart sound is produced by the closure of the mitral and tricuspid (atrioventricular) valves?", "First heart sound (S1 / 'lub')", ["Second heart sound (S2 / 'dub')", "Third heart sound (S3)", "Fourth heart sound (S4)"], "S1 marks the onset of ventricular systole as rising intraventricular pressure forces AV valves shut."),
        ("What heart sound is produced by the closure of the aortic and pulmonic (semilunar) valves?", "Second heart sound (S2 / 'dub')", ["First heart sound (S1 / 'lub')", "Ventricular gallop (S3)", "Atrial gallop (S4)"], "S2 marks the end of ventricular systole and onset of diastole as semilunar valves snap shut."),
        ("Which clinical test evaluates for cerebellar ataxia and sensory proprioception by having the patient stand with eyes closed?", "Romberg test", ["Babinski test", "Weber test", "Tinel's sign"], "A positive Romberg sign occurs when a patient maintains balance with eyes open but sways or falls with eyes shut."),
        ("What is the normal physiological response when testing the plantar reflex in a healthy adult?", "Plantar flexion (toes curl downward)", ["Dorsiflexion of the great toe with fanning of outer toes", "Rapid knee flexion and withdrawal", "Complete absence of any muscular response"], "In adults, a normal response is downward toe curling; fanning (Babinski sign) indicates upper motor neuron lesion."),
        ("What physical sign is assessed by checking for acute inspiratory arrest during deep palpation of the right upper quadrant?", "Murphy's sign", ["McBurney's sign", "Rovsing's sign", "Psoas sign"], "A positive Murphy's sign indicates acute cholecystitis as the inflamed gallbladder contacts the examiner's fingers."),
        ("What physical examination finding is elicited by palpating the left lower quadrant and causing referred pain in the right lower quadrant?", "Rovsing's sign", ["Murphy's sign", "Kernig's sign", "Brudzinski's sign"], "Rovsing's sign indicates acute appendicitis due to peritoneal stretching across the lower abdomen."),
        ("What physical finding is assessed by passive flexion of the neck producing involuntary flexion of the hips and knees?", "Brudzinski's sign", ["Kernig's sign", "Trousseau's sign", "Chvostek's sign"], "Brudzinski's sign is an indicator of acute meningeal irritation in bacterial or viral meningitis."),
        ("What physical sign is evaluated by flexing the hip to 90 degrees and attempting to extend the knee, provoking severe resistance and pain?", "Kernig's sign", ["Brudzinski's sign", "Lasegue's sign (straight leg raise)", "Cullen's sign"], "Kernig's sign is pathognomonic for meningeal irritation, indicating inflammation of the lumbosacral nerve roots."),
        ("What clinical sign of latent tetany is elicited by tapping over the facial nerve anterior to the ear, inducing facial twitching?", "Chvostek's sign", ["Trousseau's sign", "Babinski's sign", "Tinel's sign"], "Chvostek's sign reflects neuromuscular hyperexcitability secondary to acute hypocalcemia."),
        ("What clinical sign of hypocalcemia is elicited by inflating a blood pressure cuff above systolic pressure, producing carpopedal spasm?", "Trousseau's sign", ["Chvostek's sign", "Battle's sign", "Grey Turner's sign"], "Trousseau's sign of latent tetany produces carpopedal spasm within 3 minutes due to ischemia of irritable nerves."),
        ("What do ecchymosis and bruising over the mastoid process behind the ear (Battle's sign) typically indicate?", "Basilar skull fracture", ["Fracture of the zygomatic arch", "Ruptured tympanic membrane", "Acute orbital floor blowout fracture"], "Battle's sign results from blood tracking along the posterior auricular artery following basilar skull trauma."),
        ("What clinical condition is suggested by bilateral periorbital ecchymosis ('raccoon eyes') without direct facial trauma?", "Basilar skull fracture", ["Acute bilateral conjunctivitis", "Mandibular dislocation", "Maxillary sinus infection"], "Raccoon eyes indicate anterior cranial fossa basilar skull fracture with blood extravasating into periorbital tissues."),
        ("What does the Snellen eye chart standard testing distance measure?", "Visual acuity at a standardized distance of 20 feet", ["Peripheral visual field width", "Intraocular pressure", "Color perception deficiency"], "Snellen charts evaluate distance visual acuity, where 20/20 represents normal human visual resolution at 20 feet."),
        ("What does an otoscopic examination of a healthy human tympanic membrane normally reveal?", "A translucent, pearly gray membrane with a sharp cone of light", ["An opaque, bright red bulging membrane", "A yellowish membrane covered in thick purulent exudate", "A completely dark, non-reflective black surface"], "A healthy eardrum is translucent and pearly gray, reflecting a distinct triangular cone of light anteroinferiorly."),
        ("What physical test evaluates lateralization of sound using a vibrating 512 Hz tuning fork placed in the middle of the forehead?", "Weber test", ["Rinne test", "Romberg test", "Schwabach test"], "The Weber test compares bone conduction bilaterally; sound lateralizes to the affected ear in conductive hearing loss."),
        ("What physical test compares air conduction to bone conduction using a tuning fork placed against the mastoid bone and beside the ear?", "Rinne test", ["Weber test", "Romberg test", "Dix-Hallpike test"], "In a normal Rinne test, air conduction is greater than bone conduction (AC > BC)."),
        ("What does the presence of a 'bruit' heard over the carotid artery during stethoscope auscultation indicate?", "Turbulent blood flow typically caused by arterial atherosclerotic stenosis", ["Normal laminar arterial blood flow", "Venous hum from the jugular vein", "Incompetent tricuspid valve leaflet"], "A carotid bruit is a vascular murmur resulting from turbulent flow across an atherosclerotic narrowing."),
        ("What physical sign of deep vein thrombosis is elicited by passive dorsiflexion of the foot producing calf pain?", "Homan's sign", ["Psoas sign", "McMurray test", "Lachman test"], "Homan's sign is an unreliable and potentially hazardous classic sign of deep vein thrombosis."),
        ("What orthopedic examination test is considered the most sensitive for diagnosing an anterior cruciate ligament (ACL) tear?", "Lachman test", ["McMurray test", "Anterior drawer test of the ankle", "Phalen's maneuver"], "The Lachman test assesses anterior tibial translation with the knee flexed at 20-30 degrees; it is superior to the anterior drawer test."),
        ("Which maneuver evaluates for meniscal tears of the knee by flexing the joint and applying rotational stress during extension?", "McMurray test", ["Lachman test", "Thomas test", "Apley's compression test"], "A palpable or audible click with pain during McMurray's test indicates a torn fibrocartilaginous meniscus."),
        ("What test for carpal tunnel syndrome involves having the patient hold both wrists in complete, unforced flexion for 60 seconds?", "Phalen's maneuver", ["Tinel's sign", "Finkelstein's test", "Allen's test"], "Phalen's maneuver compresses the median nerve within the carpal tunnel, reproducing paresthesia in digits 1 to 3."),
        ("What physical examination test confirms arterial collateral circulation from the ulnar artery before radial artery puncture?", "Allen's test", ["Tinel's test", "Adson's test", "Wright's test"], "The modified Allen's test ensures the hand has adequate dual blood supply via the ulnar artery before radial cannulation."),
        ("What does a Glasgow Coma Scale (GCS) score of 15 indicate?", "A fully conscious, oriented, and responsive patient", ["Moderate neurological impairment", "Severe coma requiring intubation", "Brain death"], "The maximum GCS score of 15 indicates normal neurological status (Eye: 4, Verbal: 5, Motor: 6)."),
        ("What is the clinical significance of a Glasgow Coma Scale (GCS) score of 8 or less?", "Severe brain injury typically requiring airway protection and endotracheal intubation", ["Mild concussion with intact airway", "Fully alert and cooperative state", "Transient metabolic encephalopathy"], "A GCS <= 8 signifies severe coma where airway protective reflexes are lost ('GCS of 8, intubate')."),
        ("What does the 'A' in the secondary trauma assessment mnemonic 'AMPLE' stand for?", "Allergies", ["Airway", "Assessment", "Activity"], "AMPLE stands for Allergies, Medications, Past medical history, Last meal, and Events leading to injury."),
        ("What is the primary clinical objective of performing the Dix-Hallpike maneuver?", "To provoke paroxysmal positional nystagmus in Benign Paroxysmal Positional Vertigo (BPPV)", ["To assess patellar reflex arc", "To identify cervical spinal cord compression", "To evaluate vagal nerve function"], "The Dix-Hallpike test displaces otoliths in the posterior semicircular canal, triggering torsional nystagmus."),
        ("What physical examination finding is assessed when pressing the fingernail bed until blanched and timing color return?", "Capillary refill time", ["Skin turgor", "Peripheral edema", "Two-point discrimination"], "Normal capillary refill time is less than 2 seconds, reflecting adequate peripheral microvascular perfusion."),
        ("What skin assessment finding is tested by pinching a fold of skin over the clavicle to evaluate dehydration?", "Skin turgor", ["Capillary refill", "Erythema marginatum", "Pitting edema"], "Delayed return of pinched skin (tenting) indicates decreased interstitial hydration and poor skin turgor."),
        ("What is the term for a high-pitched, harsh, vibrating breath sound caused by turbulent airflow through a narrowed upper airway or larynx?", "Stridor", ["Wheezing", "Crackles (rales)", "Rhonchi"], "Stridor is an inspiratory sound caused by obstruction at or above the vocal cords (croup, epiglottitis, foreign body)."),
        ("What type of breath sounds are bubbling or popping sounds produced by fluid in the small airways and alveoli?", "Crackles (rales)", ["Wheezes", "Stridor", "Pleural friction rub"], "Crackles occur when collapsed or fluid-filled alveoli pop open during inspiration, seen in pneumonia and pulmonary edema."),
        ("What physical sound is produced by inflamed, roughened visceral and parietal pleural surfaces grating against each other during respiration?", "Pleural friction rub", ["Fine crackles", "Course rhonchi", "Expiratory wheeze"], "A pleural friction rub produces a creaking, leather-like sound throughout inspiration and expiration."),
        ("What clinical assessment tool is utilized to evaluate pressure injury risk across sensory perception, moisture, activity, mobility, nutrition, and friction?", "The Braden Scale", ["The Norton Scale", "The Glasgow Coma Scale", "The Morse Fall Scale"], "The Braden Scale scores risk from 6 to 23; lower scores correlate with higher risk of skin breakdown."),
        ("What physical finding is characterized by an indentation that persists for several seconds after releasing firm finger pressure over the pretibial skin?", "Pitting edema", ["Brawny edema", "Lymphedema", "Myxedema"], "Pitting edema reflects mobile interstitial fluid displaced by sustained digital pressure, graded +1 to +4.")
    ]

    for item in assessments:
        diff = diffs[(idx - 1) % 3]
        target_idx = (idx - 1) % 4
        opts = rotate_options(item[1], item[2], target_idx)
        q_id = f"medical-clinical-assessment-{idx:04d}"
        q_obj = {
            "id": q_id,
            "category": cat,
            "subcategory": "Clinical Assessment",
            "difficulty": diff,
            "question": item[0].strip(),
            "options": opts,
            "correctAnswer": target_idx,
            "explanation": item[3].strip(),
            "tags": ["medical", "clinical-assessment", diff],
            "active": True
        }
        questions.append(registry.validate_and_register(q_obj))
        idx += 1

    # 3. Cardiology (37)
    cardiology = [
        ("What does the P wave on a standard 12-lead electrocardiogram represent?", "Atrial depolarization", ["Ventricular depolarization", "Ventricular repolarization", "Atrioventricular nodal delay"], "The P wave represents electrical vector spread across both right and left atria, initiating atrial contraction."),
        ("What does the QRS complex on an electrocardiogram represent?", "Ventricular depolarization", ["Atrial repolarization", "Atrial depolarization", "Ventricular repolarization"], "The QRS complex corresponds to rapid depolarization of the right and left ventricles; normal duration is < 0.12 seconds."),
        ("What does the T wave on an electrocardiogram represent?", "Ventricular repolarization", ["Atrial depolarization", "Ventricular depolarization", "Mechanical systole"], "The T wave reflects ventricular recovery (repolarization) back to the resting electrical membrane potential."),
        ("What anatomical structure functions as the primary natural pacemaker of the healthy human heart?", "Sinoatrial (SA) node", ["Atrioventricular (AV) node", "Bundle of His", "Purkinje fibers"], "The SA node, located in the right atrium near the superior vena cava, spontaneously depolarizes at 60-100 bpm."),
        ("What is the primary physiological function of the atrioventricular (AV) node delay?", "To allow sufficient time for atrial systole to fill the ventricles before ventricular contraction begins", ["To accelerate impulses to maximum speed", "To block all retrograde electrical transmission", "To prevent sinus node depolarization"], "The ~0.10-second delay at the AV node ensures complete atrial emptying ('atrial kick') into the ventricles."),
        ("Which cardiac biomarker is considered the gold standard for diagnosing acute myocardial infarction due to its high cardiac specificity?", "Cardiac troponin I and T", ["Creatine kinase-MB (CK-MB)", "Myoglobin", "Lactate dehydrogenase (LDH)"], "Cardiac troponins are structural regulatory proteins unique to myocardium, rising within 3-4 hours after infarction."),
        ("What is the normal resting left ventricular ejection fraction (LVEF) in a healthy adult?", "55 percent to 70 percent", ["30 percent to 40 percent", "85 percent to 100 percent", "40 percent to 50 percent"], "Normal LVEF is 55-70%; values below 40% are diagnostic of heart failure with reduced ejection fraction (HFrEF)."),
        ("Which heart valve is located between the left atrium and the left ventricle?", "Mitral (bicuspid) valve", ["Tricuspid valve", "Aortic semilunar valve", "Pulmonic semilunar valve"], "The mitral valve has two fibrous cusps preventing blood regurgitation into the left atrium during ventricular systole."),
        ("Which heart valve is located between the right atrium and the right ventricle?", "Tricuspid valve", ["Mitral valve", "Aortic valve", "Pulmonic valve"], "The tricuspid valve has three cusps and guards the right atrioventricular orifice."),
        ("Which coronary artery is commonly referred to in clinical practice as the 'widow-maker' due to the high mortality of its proximal occlusion?", "Left Anterior Descending (LAD) artery", ["Right Coronary Artery (RCA)", "Left Circumflex (LCx) artery", "Posterior Descending Artery (PDA)"], "Occlusion of the LAD compromises blood flow to the anterior wall and interventricular septum, risking massive infarction."),
        ("What is the term for chest discomfort resulting from transient myocardial ischemia without infarction?", "Angina pectoris", ["Pericarditis", "Aortic dissection", "Pleurisy"], "Angina pectoris occurs when myocardial oxygen demand exceeds coronary arterial blood supply, often provoked by exertion."),
        ("What clinical syndrome is characterized by anginal chest pain occurring predictably with exertion and relieved by rest or nitroglycerin?", "Stable angina", ["Unstable angina", "Prinzmetal's variant angina", "Non-ST elevation myocardial infarction"], "Stable angina reflects fixed atherosclerotic plaque stenosis with predictable symptom thresholds and quick relief."),
        ("What form of angina is caused by focal coronary artery vasospasm rather than atherosclerotic plaque rupture?", "Prinzmetal's (variant) angina", ["Stable angina", "Unstable angina", "Silent ischemia"], "Prinzmetal's angina involves transient coronary vasospasm, often occurring at rest and accompanied by ST elevation."),
        ("What lethal cardiac arrhythmia is characterized by chaotic, disorganized ventricular electrical activity resulting in zero cardiac output?", "Ventricular fibrillation (V-Fib)", ["Ventricular tachycardia with a pulse", "Atrial fibrillation with rapid ventricular response", "First-degree atrioventricular block"], "V-Fib produces quivering ventricular muscle with no organized contraction, requiring immediate CPR and defibrillation."),
        ("What is the definitive, first-line emergency treatment for pulseless ventricular tachycardia and ventricular fibrillation?", "Immediate electrical defibrillation", ["High-dose IV atropine", "Synchronized electrical cardioversion", "Emergency pericardiocentesis"], "Early defibrillation within the first few minutes is the single most important determinant of survival from VF/pulseless VT."),
        ("What is the most common sustained cardiac arrhythmia encountered in clinical medicine, characterized by irregularly irregular rhythm?", "Atrial fibrillation (A-Fib)", ["Ventricular tachycardia", "Sinus arrhythmia", "Atrioventricular nodal reentrant tachycardia"], "A-Fib involves disorganized atrial depolarizations at 350-600 bpm, yielding irregularly irregular ventricular pulses."),
        ("What is the most severe and feared clinical complication associated with chronic non-anticoagulated atrial fibrillation?", "Cardioembolic ischemic stroke", ["Coronary artery vasospasm", "Acute renal tubular necrosis", "Pulmonary hypertension"], "Stasis of blood in the left atrial appendage promotes thrombus formation; dislodged clots travel directly to cerebral arteries."),
        ("What clinical scoring tool is widely utilized to estimate annual stroke risk in patients with non-valvular atrial fibrillation?", "CHA2DS2-VASc score", ["TIMI score", "HEART score", "Well's score"], "CHA2DS2-VASc stratifies thromboembolic risk based on CHF, Hypertension, Age, Diabetes, Stroke history, and Sex."),
        ("What clinical triad of physical signs (Beck's triad) is diagnostic of acute cardiac tamponade?", "Hypotension, jugular venous distension, and muffled heart sounds", ["Hypertension, bradycardia, and irregular respirations", "Fever, pericardial friction rub, and pleuritic pain", "Tachycardia, wide pulse pressure, and bounding pulses"], "Beck's triad reflects increased intrapericardial fluid pressure restricting ventricular filling and reducing stroke volume."),
        ("What acute medical procedure is indicated to relieve life-threatening cardiac tamponade?", "Pericardiocentesis", ["Needle thoracostomy", "Emergency coronary angioplasty", "Intubation and mechanical ventilation"], "Pericardiocentesis inserts a needle into the pericardial sac to aspirate fluid, restoring ventricular diastolic filling."),
        ("What is the primary hemodynamic consequence of severe aortic valve stenosis?", "Obstruction of left ventricular outflow causing concentric left ventricular hypertrophy", ["Volume overload of the right ventricle", "Severe pulmonary venous hypertension without LV change", "Massive regurgitation of blood into the left atrium"], "The left ventricle must generate exceedingly high pressures to eject blood through the narrowed orifice, inducing hypertrophy."),
        ("What physical examination finding is classic for severe chronic aortic valve regurgitation?", "A wide pulse pressure with bounding 'water-hammer' (Corrigan's) peripheral pulses", ["A narrow pulse pressure with weak peripheral pulses", "A loud opening snap followed by a diastolic rumble", "A continuous machine-like murmur over the clavicle"], "Rapid runoff of blood back into the ventricle during diastole causes low diastolic pressure and a wide pulse pressure."),
        ("What congenital cardiovascular anomaly is characterized by persistence of a fetal vascular shunt between the pulmonary artery and aorta?", "Patent Ductus Arteriosus (PDA)", ["Tetralogy of Fallot", "Ventricular Septal Defect", "Coarctation of the aorta"], "The ductus arteriosus normally closes functionally within 12-24 hours after birth; failure to close constitutes PDA."),
        ("What four congenital cardiac defects comprise the classic Tetralogy of Fallot?", "Ventricular septal defect, pulmonary stenosis, overriding aorta, and right ventricular hypertrophy", ["Atrial septal defect, aortic stenosis, mitral regurgitation, and left ventricular hypertrophy", "Patent ductus arteriosus, coarctation, pulmonary atresia, and tricuspid stenosis", "Transposition of great vessels, VSD, ASD, and pulmonary hypertension"], "Tetralogy of Fallot is the most common cyanotic congenital heart disease, characterized by these four hallmark anomalies."),
        ("What is the primary physiological mechanism by which B-type natriuretic peptide (BNP) acts during acute heart failure exacerbations?", "Promotes urinary sodium and water excretion (natriuresis) and causes systemic vasodilation", ["Stimulates aldosterone secretion from the adrenal cortex", "Causes renal sodium retention and vasoconstriction", "Increases cardiac contractility directly via beta-1 receptors"], "Ventricular myocytes release BNP in response to wall stretch; BNP opposes the RAAS system by inducing natriuresis."),
        ("Which clinical condition is defined as inflammation of the fibroserous sac surrounding the heart, presenting with positional chest pain?", "Acute pericarditis", ["Infective endocarditis", "Dilated cardiomyopathy", "Myocarditis"], "Pericarditis produces sharp, pleuritic chest pain that characteristically worsens when supine and improves when sitting forward."),
        ("What characteristic finding is seen across multiple leads on a 12-lead ECG in acute pericarditis?", "Widespread, diffuse concave ST-segment elevation with PR-segment depression", ["Focal ST elevation with reciprocal ST depression in opposite leads", "Deep symmetrical T-wave inversions with pathological Q waves", "Prolonged QT interval with delta waves"], "Diffuse concave ST elevation without reciprocal changes (except in aVR and V1) is classic for acute pericarditis."),
        ("What diagnostic test is the definitive initial imaging modality of choice to diagnose infective endocarditis?", "Transthoracic or transesophageal echocardiography (TTE/TEE)", ["Chest radiography", "Coronary computed tomography", "Nuclear myocardial perfusion scan"], "Echocardiography visualizes mobile intracardiac vegetations, abscesses, and new valvular regurgitation."),
        ("What major clinical diagnostic criteria system is used internationally to confirm a diagnosis of infective endocarditis?", "The modified Duke criteria", ["The Jones criteria", "The Centor criteria", "The Rome IV criteria"], "Duke criteria combine microbiological blood cultures, echocardiographic evidence of vegetations, and clinical phenomena."),
        ("What major criteria system is utilized to establish a clinical diagnosis of acute rheumatic fever?", "The Jones criteria", ["The Duke criteria", "The Wells criteria", "The Child-Pugh criteria"], "The Jones criteria evaluate carditis, polyarthritis, chorea, erythema marginatum, and subcutaneous nodules."),
        ("Which anatomical layer of the arterial wall is torn in an acute aortic dissection, allowing blood to separate the wall layers?", "Tunica intima", ["Tunica media", "Tunica adventitia", "Vasa vasorum"], "An intimal tear permits pressurized blood to dissect along the tunica media, creating a false lumen."),
        ("How do patients characteristically describe the pain of an acute thoracic aortic dissection?", "Sudden, excruciating, 'tearing' or 'ripping' pain radiating directly to the interscapular back", ["Gradual, dull ache worsening with deep inspiration", "Burning retrosternal pain relieved by antacids", "Sharp localized chest wall tenderness on palpation"], "Aortic dissection typically presents abruptly with maximal-intensity tearing pain between the shoulder blades."),
        ("What physical sign is an important clinical clue for acute ascending aortic dissection?", "A significant blood pressure differential (> 20 mmHg) between the right and left arms", ["Severe bilateral pedal edema", "A friction rub over the lower sternum", "Unilateral pupil constriction"], "Dissection compromising the brachiocephalic or left subclavian artery produces marked blood pressure asymmetry between arms."),
        ("What hemodynamic parameter is calculated by multiplying stroke volume (SV) by heart rate (HR)?", "Cardiac Output (CO)", ["Mean Arterial Pressure (MAP)", "Systemic Vascular Resistance (SVR)", "Ejection Fraction (EF)"], "Cardiac Output = Stroke Volume x Heart Rate; normal resting adult output averages 4 to 8 liters per minute."),
        ("What formula is clinically utilized to estimate Mean Arterial Pressure (MAP)?", "MAP = Diastolic Pressure + 1/3 (Pulse Pressure)", ["MAP = (Systolic Pressure + Diastolic Pressure) / 2", "MAP = Systolic Pressure - Diastolic Pressure", "MAP = 2 (Systolic Pressure) + Diastolic Pressure"], "Since diastole accounts for approximately two-thirds of the cardiac cycle, MAP = (2*DP + SP) / 3."),
        ("What is the minimum Mean Arterial Pressure (MAP) generally required to maintain adequate perfusion of vital organs?", "65 mmHg", ["40 mmHg", "85 mmHg", "100 mmHg"], "A MAP of at least 65 mmHg is necessary to maintain adequate cellular perfusion in brain, kidneys, and coronary beds."),
        ("What clinical physical finding is defined as a fall in systolic blood pressure greater than 10 mmHg during normal inspiration?", "Pulsus paradoxus", ["Pulsus alternans", "Pulsus bisferiens", "Water-hammer pulse"], "Pulsus paradoxus occurs when pericardial constraint (tamponade) exaggerates ventricular interdependence during inspiration.")
    ]

    for item in cardiology:
        diff = diffs[(idx - 1) % 3]
        target_idx = (idx - 1) % 4
        opts = rotate_options(item[1], item[2], target_idx)
        q_id = f"medical-cardiology-{idx:04d}"
        q_obj = {
            "id": q_id,
            "category": cat,
            "subcategory": "Cardiology",
            "difficulty": diff,
            "question": item[0].strip(),
            "options": opts,
            "correctAnswer": target_idx,
            "explanation": item[3].strip(),
            "tags": ["medical", "cardiology", diff],
            "active": True
        }
        questions.append(registry.validate_and_register(q_obj))
        idx += 1

    # 4. Pathophysiology (37)
    patho = [
        ("What is the fundamental pathophysiological defect responsible for Type 1 Diabetes Mellitus?", "Autoimmune T-cell-mediated destruction of pancreatic beta cells resulting in absolute insulin deficiency", ["Peripheral insulin resistance in skeletal muscle and liver", "Excessive glucagon secretion by alpha cells", "Inactivation of insulin receptors by circulating antibodies"], "Type 1 diabetes results from autoimmune destruction of insulin-producing pancreatic islet beta cells."),
        ("What primary metabolic disturbance triggers the development of Diabetic Ketoacidosis (DKA)?", "Severe insulin deficiency driving unrestrained lipolysis and hepatic ketogenesis into acetoacetate and beta-hydroxybutyrate", ["Excessive glucose intake overwhelming renal excretion", "Severe lactic acid accumulation due to anaerobic metabolism", "Impaired renal tubular reabsorption of bicarbonate"], "Without insulin, tissues cannot take up glucose, triggering lipolysis into free fatty acids that oxidize into ketones."),
        ("What is the primary pathological mechanism underlying the development of atherosclerosis?", "Endothelial injury followed by subendothelial lipid accumulation, macrophage foam cell formation, and chronic inflammation", ["Direct calcification of muscular arterial walls without lipid involvement", "Congenital absence of the tunica adventitia", "Bacterial infection of the venous valve leaflets"], "Atherosclerosis begins with endothelial damage that allows LDL particles to enter the intima, become oxidized, and trigger plaque formation."),
        ("What cellular response characterizes myocardial cell injury when coronary ischemia is prolonged past 20 to 30 minutes?", "Irreversible coagulative necrosis of cardiomyocytes", ["Reversible cellular swelling without membrane disruption", "Complete functional regeneration via stem cell proliferation", "Hypertrophy of dead cells without fibrosis"], "Myocardial cells withstand ischemia for up to 20-30 minutes; persistent occlusion leads to permanent coagulative necrosis."),
        ("What is the primary pathophysiological event causing acute ischemic stroke in the majority of patients?", "Cerebral arterial occlusion caused by thrombosis or thromboembolism", ["Rupture of a cerebral aneurysm into the subarachnoid space", "Systemic venous pooling in lower extremities", "Bacterial invasion of cerebral meningeal membranes"], "Ischemic strokes (87% of all strokes) result from thromboembolic or atherothrombotic occlusion of cerebral blood flow."),
        ("What pathophysiological hallmark distinguishes emphysema from chronic bronchitis in chronic obstructive pulmonary disease (COPD)?", "Permanent destruction and enlargement of alveoli distal to terminal bronchioles without fibrosis", ["Chronic productive cough for at least 3 months in 2 consecutive years", "Reversible bronchospasm induced by allergen exposure", "Severe non-cardiogenic pulmonary edema"], "Emphysema involves loss of alveolar septal elastic tissue, causing air trapping and loss of gas-exchange surface area."),
        ("What pathophysiological mechanism causes the airway hyperresponsiveness and bronchoconstriction in extrinsic asthma?", "IgE-mediated mast cell degranulation releasing histamine, leukotrienes, and prostaglandins", ["Destruction of bronchial cartilage rings by elastase", "Chronic bacterial colonization of bronchial mucous glands", "Autoimmune destruction of pulmonary capillary endothelium"], "Allergen binding to IgE on sensitized mast cells triggers immediate mediator release, provoking bronchospasm."),
        ("What is the primary pathological mechanism causing ascites in patients with decompensated liver cirrhosis?", "Portal hypertension combined with hypoalbuminemia and splanchnic arterial vasodilation", ["Excessive production of cerebrospinal fluid", "Direct lymphatic obstruction in the thoracic duct", "Renal hyperfiltration of albumin into the peritoneal cavity"], "Portal hypertension elevates sinusoidal pressure, while liver failure impairs albumin synthesis, driving transudate fluid into the peritoneum."),
        ("What is the underlying cause of hepatic encephalopathy in advanced liver failure?", "Inability of the failing liver to detoxify gut-derived ammonia, allowing neurotoxins to cross the blood-brain barrier", ["Severe hypoglycemia causing neuronal starvation", "Direct viral encephalitis within cerebral cortex neurons", "Excessive excretion of urea through choroid plexus"], "The cirrhotic liver fails to convert neurotoxic ammonia to urea via the urea cycle, causing astrocyte swelling."),
        ("What pathological mechanism causes secondary hyperparathyroidism in chronic kidney disease (CKD)?", "Hyperphosphatemia and impaired renal conversion of vitamin D to calcitriol, leading to persistent hypocalcemia", ["Direct adenoma formation within the parathyroid glands", "Excessive renal reabsorption of calcium in the distal tubule", "Suppression of parathyroid hormone by metabolic acidosis"], "Failing kidneys retain phosphate and cannot synthesize 1,25-(OH)2 vitamin D, triggering compensatory PTH secretion."),
        ("What is the classic histological definition of Barrett's esophagus resulting from chronic GERD?", "Intestinal metaplasia: replacement of normal squamous epithelium with columnar epithelium containing goblet cells", ["Hyperplasia of basal squamous epithelial cells", "Dysplastic ulceration confined to the submucosal layer", "Invasion of smooth muscle cells into the lumen"], "Chronic acid reflux causes the distal esophageal lining to transform from stratified squamous to columnar epithelium."),
        ("What is the primary physiological mechanism responsible for non-cardiogenic pulmonary edema in Acute Respiratory Distress Syndrome (ARDS)?", "Increased pulmonary capillary permeability resulting from diffuse endothelial and alveolar epithelial injury", ["Elevated left ventricular end-diastolic pressure transmitting to pulmonary veins", "Excessive intravenous administration of normal saline", "Obstruction of the main pulmonary artery by a thromboembolus"], "ARDS involves inflammatory cytokine-mediated destruction of the alveolar-capillary barrier, flooding alveoli with proteinaceous fluid."),
        ("What is the primary mechanism of cellular injury in hypovolemic shock?", "Inadequate tissue perfusion leading to cellular hypoxia, anaerobic metabolism, and lactic acidosis", ["Direct immunological destruction of cell membranes by antibodies", "Hyperosmolar dehydration of intracellular fluid compartments", "Excessive parasympathetic nervous system activation"], "Inadequate circulating blood volume fails to deliver required oxygen to capillary beds, halting ATP generation."),
        ("What is the key pathophysiological driver of septic shock following systemic bacteremia?", "Systemic release of inflammatory cytokines (TNF-alpha, IL-1, IL-6) inducing widespread vasodilation and endothelial barrier failure", ["Direct bacterial destruction of the cardiac sinoatrial node", "Massive release of epinephrine causing severe arterial constriction", "Severe hypercalcemia inducing myocardial tetany"], "Bacterial endotoxins (LPS) trigger systemic release of cytokines and nitric oxide, producing profound distributive shock."),
        ("What is the hallmark pathological finding in the substantia nigra of patients with Parkinson's disease?", "Progressive degeneration of dopaminergic neurons and presence of intracellular Lewy bodies containing alpha-synuclein", ["Loss of upper motor neurons in the primary motor cortex", "Demyelination of peripheral motor nerve axons", "Widespread neurofibrillary tangles composed of tau protein in the hippocampus"], "Parkinson's features loss of dopamine-producing cells in the substantia nigra pars compacta, disrupting basal ganglia motor circuits."),
        ("What are the two primary microscopic neuropathological hallmarks of Alzheimer's disease?", "Extracellular amyloid-beta plaques and intracellular hyperphosphorylated tau neurofibrillary tangles", ["Intracellular Lewy bodies and alpha-synuclein inclusions", "Perivascular lymphocytic cuffing and demyelinating plaques", "Spongiform vacuolation and prion protein aggregates"], "Alzheimer's pathology consists of extracellular amyloid-beta peptide plaques and intraneuronal neurofibrillary tangles."),
        ("What is the underlying immunological defect in Myasthenia Gravis?", "Autoantibodies against nicotinic acetylcholine receptors at the neuromuscular junction", ["Autoimmune destruction of peripheral sensory nerve sheaths", "Degeneration of anterior horn motor neurons in the spinal cord", "Deficiency of acetylcholine production in the central nervous system"], "Circulating IgG antibodies bind, block, and internalize muscle ACh receptors, producing exertional muscle weakness."),
        ("What is the primary pathophysiological process in Multiple Sclerosis (MS)?", "Autoimmune-mediated demyelination and axonal transection within the central nervous system", ["Peripheral nerve demyelination affecting cranial nerves exclusively", "Loss of dopamine receptors in the basal ganglia", "Bacterial endotoxin destruction of Schwann cells"], "Autoreactive T cells cross the blood-brain barrier and attack myelin sheaths and oligodendrocytes in the brain and spinal cord."),
        ("What is the key pathological event in Guillain-Barre syndrome following a viral or bacterial illness?", "Acute autoimmune inflammatory demyelination of the peripheral nervous system and spinal nerve roots", ["Chronic demyelination of central white matter tracts", "Degeneration of the corticospinal tracts", "Ischemic necrosis of the spinal cord anterior horn"], "Molecular mimicry (frequently post-Campylobacter jejuni) causes antibodies to attack peripheral nerve gangliosides and myelin."),
        ("What is the primary cause of anemia in patients with Chronic Kidney Disease (CKD)?", "Deficient production of erythropoietin by damaged peritubular capillary interstitial cells in the kidneys", ["Chronic autoimmune destruction of circulating erythrocytes (hemolysis)", "Dietary vitamin B12 deficiency due to impaired gastric absorption", "Excessive renal loss of hemoglobin through glomerular capillaries"], "The diseased kidney fails to synthesize adequate erythropoietin (EPO), the primary hormone stimulating bone marrow erythropoiesis."),
        ("What is the genetic and cellular defect in Sickle Cell Anemia?", "A point mutation in the beta-globin gene substituting valine for glutamic acid at codon 6, causing hemoglobin S polymerization under hypoxia", ["Deletion of four alpha-globin genes on chromosome 16", "Deficiency of spectrin in the red cell membrane cytoskeleton", "Deficiency of the enzyme glucose-6-phosphate dehydrogenase (G6PD)"], "HbS molecules polymerize into rigid, insoluble fibers under deoxygenation, deforming red cells into sickle shapes."),
        ("What is the primary mechanism of hemolysis in Glucose-6-Phosphate Dehydrogenase (G6PD) deficiency?", "Inability to maintain reduced glutathione, exposing red blood cells to oxidative stress, Heinz body formation, and extravascular hemolysis", ["Direct antibody-mediated destruction of red blood cell antigens", "Mechanical shearing of red cells across artificial heart valves", "Impaired synthesis of spectrin causing membrane fragility"], "G6PD is essential for generating NADPH; without it, erythrocytes cannot regenerate glutathione to detoxify oxidative peroxides."),
        ("What is the classic pathophysiological defect in Pernicious Anemia?", "Autoimmune destruction of gastric parietal cells causing deficiency of intrinsic factor necessary for ileal vitamin B12 absorption", ["Inadequate dietary intake of iron over several decades", "Mutation in the transferrin receptor gene in hepatic tissue", "Premature splenic clearance of megaloblastic white blood cells"], "Parietal cell loss prevents intrinsic factor secretion; vitamin B12 cannot form the complex required for ileal absorption."),
        ("What is the primary pathophysiological mechanism causing peptic ulcer disease in patients infected with Helicobacter pylori?", "Bacterial urease production, mucosal inflammation, and disruption of the protective gastric mucosal barrier by toxins", ["Direct mechanical abrasion of the gastric muscularis externa", "Complete suppression of hydrochloric acid secretion", "Autoimmune destruction of gastric chief cells"], "H. pylori synthesizes urease to survive gastric acid and secretes VacA/CagA cytotoxins that degrade protective mucus layers."),
        ("What is the primary hemodynamic mechanism leading to cardiogenic shock in massive acute myocardial infarction?", "Severe pump failure resulting in profound loss of contractility, decreased cardiac output, and inadequate end-organ perfusion despite adequate intravascular volume", ["Severe systemic vasodilation caused by histamine release", "Massive loss of whole blood through ruptured myocardium", "Complete obstruction of pulmonary arterial outflow"], "Loss of > 40% of left ventricular myocardium drops stroke volume and cardiac index below critical thresholds."),
        ("What is the primary mechanism underlying the development of prerenal acute kidney injury?", "Renal hypoperfusion resulting from systemic hypotension, hypovolemia, or renal vasoconstriction without intrinsic parenchymal damage", ["Direct toxic necrosis of renal tubular epithelial cells", "Immune complex deposition within glomerular basement membranes", "Mechanical obstruction of bilateral ureters by calculi"], "Prerenal AKI involves intact nephrons experiencing reduced glomerular filtration pressure due to compromised renal perfusion."),
        ("What is the hallmark pathological change in Acute Tubular Necrosis (ATN)?", "Ischemic or nephrotoxic injury causing sloughing of renal tubular epithelial cells and formation of muddy brown granular casts", ["Inflammation of the renal pelvis and interstitial medulla", "Thickening of the glomerular capillary basement membrane", "Fibrous scarring of the renal calyces"], "Ischemia or toxins (aminoglycosides, radiocontrast) damage tubular epithelium, which sloughs into lumens and blocks flow."),
        ("What is the fundamental pathophysiological defect in Graves' disease causing hyperthyroidism?", "Autoantibodies (thyroid-stimulating immunoglobulins) that bind and continuously stimulate the TSH receptor on thyroid follicular cells", ["Autonomous adenoma of the anterior pituitary gland secreting excessive TSH", "Destruction of thyroid follicles releasing preformed hormone", "Deficiency of dietary iodine intake"], "TSI antibodies mimic TSH, triggering unregulated, continuous production and secretion of T3 and T4."),
        ("What is the primary pathophysiological mechanism in Hashimoto's thyroiditis?", "Chronic autoimmune destruction of thyroid parenchyma by autoreactive lymphocytes and antithyroid peroxidase (anti-TPO) antibodies", ["Excessive stimulation of thyroid follicular cells by TSH", "Bacterial infection of the thyroid gland with abscess formation", "Congenital failure of thyroid hormone receptor signaling"], "Hashimoto's is the leading cause of hypothyroidism in iodine-sufficient areas, featuring lymphocytic infiltration and Hurthle cells."),
        ("What pathophysiological defect defines Cushing's disease (pituitary etiology)?", "An ACTH-secreting pituitary adenoma driving bilateral adrenal cortical hyperplasia and autonomous cortisol hypersecretion", ["Primary adrenal cortical adenoma secreting cortisol independent of ACTH", "Ectopic production of ACTH by a small cell lung carcinoma", "Iatrogenic administration of exogenous glucocorticoids"], "Cushing's disease refers specifically to hypercortisolemia caused by a benign pituitary corticotroph adenoma."),
        ("What is the underlying endocrine defect in Addison's disease (primary adrenal insufficiency)?", "Autoimmune destruction of all three zones of the adrenal cortex, causing deficiency of cortisol, aldosterone, and androgens", ["Inability of the anterior pituitary gland to synthesize ACTH", "Hypothalamic failure to secrete corticotropin-releasing hormone (CRH)", "Resistance of peripheral target tissues to circulating cortisol"], "Primary adrenal insufficiency destroys cortical tissue; lack of aldosterone causes sodium wasting and life-threatening hyperkalemia."),
        ("What is the primary pathophysiological event in acute pancreatitis?", "Premature intrapancreatic activation of digestive zymogens (especially trypsinogen to trypsin), causing autodigestion of pancreatic tissue", ["Bacterial infection entering through the pancreatic duct", "Autoimmune destruction of pancreatic islet alpha cells", "Malignant transformation of ductal epithelial cells"], "Obstruction or alcohol triggers premature intra-acinar activation of trypsin, initiating autodigestive necrotizing injury."),
        ("What is the primary pathological mechanism underlying tension pneumothorax?", "A one-way 'ball-valve' pleural tear allowing air to enter the pleural space on inspiration but preventing its escape during expiration", ["Accumulation of proteinaceous fluid within the alveolar air spaces", "Bilateral collapse of the lungs caused by severe diaphragmatic fatigue", "Rupture of pulmonary capillaries into the bronchial tree"], "Positive intrapleural pressure rises continuously, collapsing the ipsilateral lung and shifting the mediastinum, obstructing venous return."),
        ("What is the primary pathological mechanism in idiopathic pulmonary fibrosis?", "Aberrant, non-resolving fibroblastic proliferation and excessive collagen deposition leading to progressive lung parenchymal stiffening", ["Chronic granulomatous infection caused by non-tuberculous mycobacteria", "Recurrent episodes of acute hydrostatic pulmonary edema", "Loss of surfactant synthesis by damaged type I alveolar cells"], "Repetitive microscopic epithelial injury triggers unregulated repair, replacing pliable alveoli with dense, non-compliant scar tissue."),
        ("What is the primary physiological mechanism causing carbon monoxide (CO) toxicity?", "CO binds to hemoglobin with an affinity > 200 times higher than oxygen, forming carboxyhemoglobin and shifting the oxygen dissociation curve leftward", ["CO directly paralyzes the diaphragm through central nervous system depression", "CO dissolves lung surfactant, causing massive bilateral atelectasis", "CO blocks the pulmonary artery through air embolism formation"], "Carboxyhemoglobin prevents oxygen transport and inhibits oxygen release to tissues, causing severe cellular asphyxiation."),
        ("What is the primary pathophysiological mechanism causing tissue destruction in systemic lupus erythematosus (SLE)?", "Type III hypersensitivity: formation and deposition of circulating nuclear antigen-antibody immune complexes in blood vessels and tissues", ["Direct cytotoxic T-cell destruction of endocrine organs exclusively", "Type I IgE-mediated mast cell degranulation in systemic tissues", "Failure of bone marrow hematopoietic stem cell differentiation"], "Antinuclear antibodies (ANA) and anti-dsDNA form complexes that lodge in microvasculature, activating complement and damaging organs."),
        ("What is the primary cellular mechanism that distinguishes malignant neoplasms from benign tumors?", "Invasion through the basement membrane into adjacent tissues and capacity for distant metastatic dissemination", ["Rapid cellular division without histological cellular atypia", "Presence of a uniform, well-delineated fibrous capsule", "Ability to respond to normal tissue growth regulatory signals"], "Malignancy is defined pathologically by loss of tissue architecture, basement membrane invasion, and metastatic potential.")
    ]

    for item in patho:
        diff = diffs[(idx - 1) % 3]
        target_idx = (idx - 1) % 4
        opts = rotate_options(item[1], item[2], target_idx)
        q_id = f"medical-pathophysiology-{idx:04d}"
        q_obj = {
            "id": q_id,
            "category": cat,
            "subcategory": "Pathophysiology",
            "difficulty": diff,
            "question": item[0].strip(),
            "options": opts,
            "correctAnswer": target_idx,
            "explanation": item[3].strip(),
            "tags": ["medical", "pathophysiology", diff],
            "active": True
        }
        questions.append(registry.validate_and_register(q_obj))
        idx += 1

    print(f"Generated Medical: {len(questions)} questions")
    return questions
