"""
iq_grammar.py
Generates 320 clean, distinct questions:
- IQ & Logic (160 questions)
- English & Grammar (160 questions)
"""

def generate_iq_questions(build_q_fn):
    cat = "IQ & Logic"
    diffs = ["easy", "medium", "hard"]
    questions = []
    idx = 1

    # Subcat 1: Pattern Sequences (40 questions)
    patterns = [
        ("What is the next number in the sequence: 2, 4, 8, 16, 32, ...?", "64", ["48", "56", "72"], "Each term is multiplied by 2: 32 * 2 = 64."),
        ("What is the next number in the sequence: 3, 7, 11, 15, 19, ...?", "23", ["21", "22", "25"], "Each term increases by 4: 19 + 4 = 23."),
        ("What is the next number in the sequence: 1, 1, 2, 3, 5, 8, 13, ...?", "21", ["19", "20", "24"], "This is the Fibonacci sequence where each term is the sum of the two preceding terms: 8 + 13 = 21."),
        ("What is the next number in the sequence: 2, 6, 12, 20, 30, ...?", "42", ["38", "40", "44"], "The differences between terms are 4, 6, 8, 10, so the next difference is 12: 30 + 12 = 42 (also n*(n+1))."),
        ("What is the next number in the sequence: 1, 4, 9, 16, 25, 36, ...?", "49", ["42", "48", "64"], "These are consecutive squares (1^2, 2^2, 3^2, ...). 7^2 = 49."),
        ("What is the next number in the sequence: 1, 8, 27, 64, 125, ...?", "216", ["196", "225", "256"], "These are consecutive cubes (1^3, 2^3, 3^3, ...). 6^3 = 216."),
        ("What is the next number in the sequence: 80, 40, 20, 10, ...?", "5", ["2.5", "4", "0"], "Each term is divided by 2: 10 / 2 = 5."),
        ("What is the next number in the sequence: 5, 10, 20, 40, 80, ...?", "160", ["120", "140", "200"], "Each term is multiplied by 2: 80 * 2 = 160."),
        ("What is the next number in the sequence: 100, 95, 85, 70, 50, ...?", "25", ["20", "30", "35"], "The differences subtracted are 5, 10, 15, 20, so next subtract 25: 50 - 25 = 25."),
        ("What is the next number in the sequence: 2, 3, 5, 7, 11, 13, ...?", "17", ["15", "19", "21"], "This is the sequence of consecutive prime numbers. The prime following 13 is 17."),
        ("What is the next number in the sequence: 4, 9, 19, 39, 79, ...?", "159", ["149", "158", "169"], "Each term is multiplied by 2 and then add 1: 79 * 2 + 1 = 158 + 1 = 159."),
        ("What is the next number in the sequence: 0, 3, 8, 15, 24, ...?", "35", ["32", "36", "48"], "Pattern is n^2 - 1: 6^2 - 1 = 36 - 1 = 35."),
        ("What is the next number in the sequence: 2, 5, 10, 17, 26, ...?", "37", ["35", "36", "38"], "Pattern is n^2 + 1: 6^2 + 1 = 36 + 1 = 37."),
        ("What is the next letter in the sequence: A, C, E, G, I, ...?", "K", ["J", "L", "M"], "Letters skip one position in the alphabet: I -> K."),
        ("What is the next letter in the sequence: Z, X, V, T, R, ...?", "P", ["Q", "O", "N"], "Letters skip backwards by two positions: R -> P."),
        ("What is the next number in the sequence: 128, 64, 32, 16, 8, ...?", "4", ["2", "6", "0"], "Each term is halved: 8 / 2 = 4."),
        ("What is the next number in the sequence: 7, 14, 28, 56, 112, ...?", "224", ["168", "212", "248"], "Each term doubles: 112 * 2 = 224."),
        ("What is the next number in the sequence: 1, 3, 6, 10, 15, 21, ...?", "28", ["26", "27", "30"], "These are triangular numbers (+2, +3, +4, +5, +6, +7): 21 + 7 = 28."),
        ("What is the next number in the sequence: 3, 9, 27, 81, ...?", "243", ["162", "216", "729"], "Each term is multiplied by 3: 81 * 3 = 243."),
        ("What is the next letter in the sequence: B, D, G, K, P, ...?", "V", ["U", "W", "X"], "The gaps increase by +2, +3, +4, +5, +6: P (16) + 6 = 22 (V)."),
        ("What is the next number in the sequence: 50, 45, 40, 35, 30, ...?", "25", ["20", "28", "15"], "Each term decreases by 5: 30 - 5 = 25."),
        ("What is the next number in the sequence: 6, 11, 21, 36, 56, ...?", "81", ["76", "86", "91"], "Differences are +5, +10, +15, +20, +25: 56 + 25 = 81."),
        ("What is the next number in the sequence: 1, 2, 6, 24, 120, ...?", "720", ["600", "640", "840"], "These are factorials (1!, 2!, 3!, 4!, 5!, 6!): 120 * 6 = 720."),
        ("What is the next number in the sequence: 13, 26, 39, 52, 65, ...?", "78", ["72", "75", "81"], "Multiples of 13: 65 + 13 = 78."),
        ("What is the next letter in the sequence: O, T, T, F, F, S, S, E, ...?", "N", ["T", "O", "E"], "First letters of numbers: One, Two, Three, Four, Five, Six, Seven, Eight, Nine -> N."),
        ("What is the next number in the sequence: 2, 4, 16, 256, ...?", "65,536", ["1,024", "4,096", "32,768"], "Each term is squared to get the next: 256^2 = 65,536."),
        ("What is the next number in the sequence: 99, 92, 85, 78, 71, ...?", "64", ["62", "63", "65"], "Each term decreases by 7: 71 - 7 = 64."),
        ("What is the next number in the sequence: 4, 8, 12, 24, 28, 56, ...?", "60", ["58", "62", "112"], "Alternating pattern: *2, +4, *2, +4, *2, +4: 56 + 4 = 60."),
        ("What is the next number in the sequence: 1, 5, 13, 29, 61, ...?", "125", ["115", "121", "129"], "Pattern is *2 + 3: 61 * 2 + 3 = 122 + 3 = 125."),
        ("What is the next number in the sequence: 10, 12, 16, 22, 30, ...?", "40", ["38", "42", "44"], "Differences increase by 2 (+2, +4, +6, +8, +10): 30 + 10 = 40."),
        ("What is the next number in the sequence: 2, 5, 9, 14, 20, 27, ...?", "35", ["33", "34", "36"], "Differences increase by 1 (+3, +4, +5, +6, +7, +8): 27 + 8 = 35."),
        ("What is the next letter in the sequence: J, F, M, A, M, J, J, A, ...?", "S", ["O", "N", "D"], "First letters of months: January through August, next is September -> S."),
        ("What is the next number in the sequence: 64, 32, 16, 8, 4, ...?", "2", ["1", "0", "3"], "Halving each term: 4 / 2 = 2."),
        ("What is the next number in the sequence: 11, 22, 33, 44, 55, ...?", "66", ["65", "67", "77"], "Multiples of 11: 55 + 11 = 66."),
        ("What is the next number in the sequence: 3, 5, 9, 17, 33, ...?", "65", ["49", "57", "63"], "Pattern is *2 - 1: 33 * 2 - 1 = 66 - 1 = 65."),
        ("What is the next number in the sequence: 1000, 500, 250, 125, ...?", "62.5", ["60", "65", "50"], "Each term divided by 2: 125 / 2 = 62.5."),
        ("What is the next number in the sequence: 400, 361, 324, 289, 256, ...?", "225", ["216", "220", "240"], "Descending squares: 20^2, 19^2, 18^2, 17^2, 16^2, 15^2 = 225."),
        ("What is the next number in the sequence: 5, 8, 14, 26, 50, ...?", "98", ["86", "92", "102"], "Pattern is *2 - 2: 50 * 2 - 2 = 100 - 2 = 98."),
        ("What is the next letter in the sequence: M, T, W, T, F, ...?", "S", ["W", "M", "T"], "Days of the week: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday -> S."),
        ("What is the next number in the sequence: 1, 4, 27, 256, ...?", "3,125", ["1,024", "2,048", "4,096"], "Pattern is n^n: 1^1, 2^2, 3^3, 4^4, 5^5 = 3,125.")
    ]

    for item in patterns:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Pattern Sequences", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 2: Spatial Reasoning (40 questions)
    spatial = [
        ("If a standard six-sided die is rolled, what is the sum of the numbers on any two opposite faces?", "7", ["6", "8", "9"], "On standard dice, opposite faces always sum to 7 (1+6, 2+5, 3+4)."),
        ("How many 1-cm small cubes are required to construct a solid cube with an edge length of 4 cm?", "64", ["16", "32", "48"], "Volume = 4 * 4 * 4 = 64 small cubes."),
        ("If a flat piece of paper is folded in half three consecutive times, into how many layered sections is it divided?", "8", ["4", "6", "12"], "Each fold doubles the layers: 2^3 = 8."),
        ("When viewed from directly above (bird's-eye view), what 2D shape does a standard upright cylinder cast?", "Circle", ["Rectangle", "Oval", "Square"], "Looking down the longitudinal axis of an upright cylinder reveals a circular top profile."),
        ("When viewed directly from the side at eye level, what 2D shape does a solid cone present?", "Triangle", ["Circle", "Trapezoid", "Ellipse"], "The orthographic side projection of a right circular cone is an isosceles triangle."),
        ("How many total edges does a standard square-based pyramid possess?", "8", ["5", "6", "10"], "A square pyramid has 4 base edges and 4 triangular lateral edges, totaling 8 edges."),
        ("How many vertices does a regular tetrahedron have?", "4", ["6", "8", "12"], "A tetrahedron is a triangular pyramid with 4 triangular faces and 4 vertices."),
        ("If a 3x3x3 solid wooden cube painted red on all outer surfaces is cut into 27 small 1x1x1 cubes, how many have exactly 3 red faces?", "8", ["6", "12", "1"], "Only the 8 corner cubes have three exposed painted faces."),
        ("If a 3x3x3 painted cube is cut into 27 small 1x1x1 cubes, how many have exactly 2 red faces?", "12", ["6", "8", "16"], "The edge cubes (excluding corners) have 2 painted faces: 12 edges * 1 cube per edge = 12."),
        ("If a 3x3x3 painted cube is cut into 27 small 1x1x1 cubes, how many have exactly 1 red face?", "6", ["8", "12", "9"], "The center cubes of the 6 outer faces have exactly 1 painted face: 6 faces * 1 = 6."),
        ("If a 3x3x3 painted cube is cut into 27 small 1x1x1 cubes, how many have NO painted faces (0 red faces)?", "1", ["0", "2", "4"], "Only the single core cube in the exact geometric center remains unpainted."),
        ("What 3D solid is formed when a right triangle is rotated 360 degrees around one of its legs?", "Cone", ["Cylinder", "Sphere", "Prism"], "Rotating a right triangle around one leg sweeps out a right circular cone."),
        ("What 3D solid is formed when a rectangle is rotated 360 degrees around one of its edges?", "Cylinder", ["Cone", "Sphere", "Torus"], "Rotating a rectangle around one edge generates a cylinder."),
        ("What 3D solid is formed when a semicircle is rotated 360 degrees around its diameter?", "Sphere", ["Hemisphere", "Cylinder", "Cone"], "Rotating a semicircle around its diameter sweeps out a complete 3D sphere."),
        ("How many rotational axes of symmetry does a regular hexagon have in a 2D plane?", "6", ["3", "4", "8"], "A regular hexagon has 6-fold rotational symmetry (angles of 60, 120, 180, 240, 300, 360 degrees)."),
        ("How many lines of reflective symmetry does a non-square rectangle possess?", "2", ["1", "4", "Infinite"], "A rectangle has 2 lines of symmetry (connecting midpoints of opposite sides); its diagonals are not reflection lines."),
        ("How many lines of reflective symmetry does an equilateral triangle have?", "3", ["1", "2", "6"], "An equilateral triangle has 3 lines of symmetry passing through each vertex to the opposite midpoint."),
        ("How many lines of reflective symmetry does a regular circle have?", "Infinite", ["360", "180", "100"], "Any straight diameter line passing through the center of a circle is an axis of reflective symmetry."),
        ("If you look at the word 'MOM' in a vertical mirror, what appears in the reflection?", "MOM", ["WOW", "NON", "OWO"], "M and O are laterally symmetrical, so 'MOM' reads identically in a mirror."),
        ("If you look at the capital letter 'E' in a standard vertical mirror, how does it orient?", "Reflected horizontally facing left", ["Upside down", "Unchanged", "Rotated 90 degrees"], "A vertical mirror reverses left and right, so the three arms of 'E' point to the left."),
        ("What is the top view of a standard rectangular house with a simple gabled roof?", "A rectangle divided down the center by a ridge line", ["A triangle", "A circle", "A trapezoid"], "Looking from above, the two sloping roof planes appear as two adjacent rectangles joined at the ridge."),
        ("How many degrees must a square be rotated around its center to map onto itself for the first time?", "90 degrees", ["45 degrees", "180 degrees", "360 degrees"], "A square has 4-fold rotational symmetry: 360 / 4 = 90 degrees."),
        ("How many faces does a standard rectangular cardboard shipping box have?", "6", ["4", "8", "12"], "A rectangular cuboid has top, bottom, front, back, left, and right faces: 6 faces."),
        ("If an analog clock face is mirrored across the vertical 12-to-6 axis, what time does 3:00 appear to show?", "9:00", ["6:00", "12:00", "8:00"], "The minute hand at 12 remains at 12, while the hour hand at 3 reflects across to 9."),
        ("How many right angles are formed when two perpendicular lines intersect in a plane?", "4", ["2", "1", "8"], "Perpendicular lines intersect to form four adjacent 90-degree right angles."),
        ("What is the cross-section shape obtained by slicing a sphere with a flat plane at any angle?", "Circle", ["Ellipse", "Parabola", "Oval"], "Any planar cross-section of a sphere is always a circle."),
        ("What cross-section is produced when a right cone is sliced parallel to its circular base?", "Circle", ["Ellipse", "Hyperbola", "Triangle"], "Slicing parallel to the base produces a circle of smaller radius."),
        ("What cross-section is produced when a right cone is sliced at an angle through both opposite sides?", "Ellipse", ["Circle", "Parabola", "Hyperbola"], "A planar cut at an angle through both generators of a cone produces an ellipse."),
        ("How many diagonal lines can be drawn inside a regular pentagon?", "5", ["4", "6", "10"], "Formula n(n-3)/2 = 5*(2)/2 = 5 diagonals forming a five-pointed star."),
        ("How many diagonal lines can be drawn inside a regular hexagon?", "9", ["6", "8", "12"], "Formula n(n-3)/2 = 6*(3)/2 = 9 diagonals."),
        ("If you walk 10 meters north, turn right 90 degrees and walk 10 meters east, what is your bearing from the starting point?", "Northeast (45 degrees)", ["Northwest", "Southeast", "East"], "Equal north and east displacements point directly northeast at a 45-degree bearing."),
        ("If you walk 5 miles south, turn right 90 degrees and walk 5 miles, in which cardinal direction are you now walking?", "West", ["East", "North", "South"], "Facing south, a right turn points west."),
        ("How many flat square faces are needed to construct an open box with no top lid?", "5", ["4", "6", "3"], "An open box has 1 bottom and 4 sides, requiring 5 faces."),
        ("What shape is formed by the net of a cylinder consisting of two identical circles and one connecting shape?", "Rectangle", ["Triangle", "Trapezoid", "Parallelogram"], "Unrolling the lateral curved surface of a cylinder forms a flat rectangle."),
        ("How many corners does a standard sheet of paper have if you cut off one corner with a straight line?", "5", ["3", "4", "6"], "Cutting off one corner removes 1 corner and introduces 2 new corners: 4 - 1 + 2 = 5."),
        ("If two gears are meshed together, in what direction does the second gear rotate when the first rotates clockwise?", "Counterclockwise", ["Clockwise", "Alternating", "Parallel"], "Directly meshed external gears always rotate in opposite directions."),
        ("In a system of three sequentially meshed inline gears, what direction does the third gear turn if the first turns clockwise?", "Clockwise", ["Counterclockwise", "Stationary", "Perpendicular"], "Gear 1 (CW) -> Gear 2 (CCW) -> Gear 3 (CW)."),
        ("What is the minimum number of colors needed to color a planar map so that no two adjacent regions share the same color?", "4", ["3", "5", "6"], "The Four Color Theorem proves that any planar map requires at most 4 colors."),
        ("How many distinct planes of symmetry does a regular cube possess?", "9", ["6", "8", "12"], "A cube has 3 planes parallel to faces and 6 diagonal planes connecting opposite edges, totaling 9."),
        ("What is the name of a polyhedron with 20 equilateral triangular faces?", "Icosahedron", ["Dodecahedron", "Octahedron", "Decahedron"], "A regular icosahedron has 20 triangular faces, 30 edges, and 12 vertices.")
    ]

    for item in spatial:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Spatial Reasoning", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 3: Logical Deductions (40 questions)
    deductions = [
        ("All roses are flowers. Some flowers fade quickly. Which conclusion can be logically deduced with absolute certainty?", "Some roses might fade quickly, but it is not guaranteed", ["All roses fade quickly", "No roses fade quickly", "All flowers are roses"], "The premise only states 'some flowers', so roses may or may not belong to the subset that fades quickly."),
        ("All mammals are warm-blooded. A whale is a mammal. What is the logical conclusion?", "A whale is warm-blooded", ["A whale is a fish", "Some mammals are cold-blooded", "All warm-blooded animals are whales"], "By categorical syllogism (modus ponens), the specific subject inherits the universal predicate."),
        ("If it rains, the grass gets wet. The grass is not wet. What can be logically concluded?", "It did not rain", ["It rained lightly", "The grass is synthetic", "The sun is shining"], "By modus tollens (denying the consequent): if P implies Q and not Q, then not P."),
        ("No reptiles have fur. All snakes are reptiles. What is the valid logical conclusion?", "No snakes have fur", ["Some snakes have fur", "All reptiles are snakes", "Snakes are mammals"], "Since all snakes are in the class of reptiles, and no reptiles have fur, snakes cannot have fur."),
        ("If Alice is taller than Bob, and Bob is taller than Charlie, who is the shortest?", "Charlie", ["Alice", "Bob", "Cannot be determined"], "By transitive property of inequality: Alice > Bob > Charlie; Charlie is shortest."),
        ("If all squares are rectangles, and all rectangles are quadrilaterals, which statement is guaranteed true?", "All squares are quadrilaterals", ["All quadrilaterals are squares", "No quadrilaterals are rectangles", "Some squares are not quadrilaterals"], "Transitive relationship: Squares c Rectangles c Quadrilaterals."),
        ("In a town, all dentists are golfers. Dr. Evans is not a golfer. What is the guaranteed conclusion?", "Dr. Evans is not a dentist", ["Dr. Evans is a retired dentist", "Dr. Evans dislikes sports", "Dr. Evans plays tennis"], "Contrapositive logic: If Dentist -> Golfer, then Not Golfer -> Not Dentist."),
        ("Tom is older than Dave. Dave is older than Sam. Who is the oldest?", "Tom", ["Dave", "Sam", "Cannot be determined"], "Tom > Dave > Sam; Tom is the oldest."),
        ("Some artists are painters. All painters are creative. Which statement is logically valid?", "Some artists are creative", ["All artists are painters", "All creative people are artists", "No artists are creative"], "The subset of artists who are painters are necessarily creative."),
        ("If today is Monday, tomorrow is Tuesday. Tomorrow is not Tuesday. What is the conclusion?", "Today is not Monday", ["Today is Sunday", "Tomorrow is Wednesday", "Today is Tuesday"], "Modus tollens: negation of the consequent implies negation of the antecedent."),
        ("Every member of the club has a membership badge. Frank does not have a membership badge. What is the conclusion?", "Frank is not a member of the club", ["Frank lost his badge", "Frank is an honorary member", "Frank is the club president"], "If Member -> Has Badge, then No Badge -> Not Member."),
        ("If a polygon has 3 sides, it is a triangle. Polygon Z has 4 sides. What can be concluded?", "Polygon Z is not a triangle", ["Polygon Z is a pentagon", "Polygon Z is an equilateral triangle", "Polygon Z is a circle"], "Triangles have strictly 3 sides; a 4-sided polygon cannot be a triangle."),
        ("If all cats purr, and Luna is a cat, what follows?", "Luna purrs", ["Luna does not purr", "All animals that purr are cats", "Luna is a tiger"], "Universal instantiation: Luna possesses all properties universal to cats."),
        ("No prime number greater than 2 is even. The number N is a prime greater than 2. What is true of N?", "N is odd", ["N is even", "N is divisible by 4", "N equals 2"], "Since 2 is the only even prime, all primes > 2 must be odd."),
        ("If neither Jack nor Jill went up the hill, did Jack go up the hill?", "No", ["Yes", "Only with Jill", "Cannot be determined"], "'Neither Jack nor Jill' means Jack did not go, and Jill did not go."),
        ("All books have pages. This object has no pages. What follows?", "This object is not a book", ["This object is an electronic book", "This object is an empty book", "This object is a magazine"], "By contraposition, an object lacking pages cannot be a book under the stated premise."),
        ("If every vehicle in the fleet is electric, and truck #12 is in the fleet, what follows?", "Truck #12 is electric", ["Truck #12 runs on diesel", "Truck #12 is hybrid", "Only trucks are in the fleet"], "Truck #12 belongs to the fleet and therefore possesses the fleet's universal property."),
        ("Statement: 'Either it is sunny or it is raining.' If it is not sunny, what must be true?", "It is raining", ["It is snowing", "It is cloudy", "Cannot be determined"], "In a disjunction (P or Q), the negation of one disjunct necessitates the truth of the other."),
        ("If Emma is faster than Liam, and Liam is faster than Noah, who finishes last in a race between them?", "Noah", ["Emma", "Liam", "Cannot be determined"], "Speed order: Emma > Liam > Noah. Noah finishes last."),
        ("All apples are fruits. Some fruits are sweet. Can we conclude that all apples are sweet?", "No, because only some fruits are sweet", ["Yes, all apples are sweet", "No apples are sweet", "Fruits cannot be apples"], "Fallacy of the undistributed middle: apples may fall in the non-sweet fruit subset."),
        ("If P implies Q, what is the logically equivalent contrapositive statement?", "Not Q implies Not P", ["Q implies P", "Not P implies Not Q", "P implies Not Q"], "A conditional statement P -> Q is logically equivalent to its contrapositive ~Q -> ~P."),
        ("What is the converse of the statement: 'If it is raining, then the ground is wet'?", "If the ground is wet, then it is raining", ["If it is not raining, the ground is not wet", "If the ground is not wet, it is not raining", "The ground is always wet"], "The converse reverses the hypothesis and conclusion: Q -> P."),
        ("What is the inverse of the statement: 'If a number is even, then it is divisible by 2'?", "If a number is not even, then it is not divisible by 2", ["If a number is divisible by 2, then it is even", "If a number is odd, it is prime", "All numbers are divisible by 2"], "The inverse negates both hypothesis and conclusion: ~P -> ~Q."),
        ("If all A are B, and all B are C, are all A necessarily C?", "Yes, absolutely", ["No, never", "Only some A are C", "Cannot be determined"], "Transitive property of subset inclusion: A c B c C implies A c C."),
        ("A person claims: 'I always lie.' Is this statement logically possible?", "No, it creates a self-referential paradox", ["Yes, it is always true", "Yes, it is a proven theorem", "It depends on the time of day"], "The Epimenides/Liar paradox: if true, the speaker lies (false); if false, the speaker told truth (contradiction)."),
        ("If some birds cannot fly, and penguins are birds, can we conclude from these premises alone that penguins cannot fly?", "No, that requires specific external knowledge about penguins", ["Yes, the premises prove it directly", "Penguins are not birds", "All birds can fly"], "The premises state only that 'some' birds cannot fly, not specifying which ones."),
        ("Either the door is locked or it is unlocked. The door is not unlocked. What is the deduction?", "The door is locked", ["The door is broken", "The door is open", "Cannot be determined"], "Law of excluded middle: an entity must satisfy one of two complementary states."),
        ("If X is greater than Y, and Y is greater than Z, is X greater than Z?", "Yes, always", ["No, never", "Only if X is positive", "Cannot be determined"], "Transitivity of inequality: X > Y > Z implies X > Z."),
        ("All metals conduct electricity. Copper is a metal. What conclusion follows?", "Copper conducts electricity", ["Copper is an insulator", "All electrical conductors are copper", "Some metals are non-conductive"], "Deductive syllogism: Copper possesses the universal property of metals."),
        ("If no fish can breathe atmospheric air directly, and goldfish are fish, what follows?", "Goldfish cannot breathe atmospheric air directly", ["Goldfish can breathe air", "Some fish are mammals", "All water animals are fish"], "Negative universal syllogism: Goldfish inherit the exclusion."),
        ("If you cannot be in two places at once, and Mark is in London right now, can Mark also be in Paris right now?", "No, impossible", ["Yes, easily", "Only with a passport", "Cannot be determined"], "By the law of non-contradiction and spatial exclusivity, one cannot occupy disjoint locations simultaneously."),
        ("Every student who scored over 90 received an A. Kevin received an A. Did Kevin necessarily score over 90?", "No, he could have scored an A through another grading criterion", ["Yes, he scored exactly 95", "Yes, he must have scored over 90", "No, Kevin failed"], "Affirming the consequent is a formal fallacy: receiving an A does not guarantee a score over 90 unless it was an 'if and only if' condition."),
        ("If all dogs bark, and Buster does not bark, is Buster a dog?", "No, according to the premise", ["Yes, Buster is a quiet dog", "Buster is a puppy", "Cannot be determined"], "Modus tollens: if Dog -> Barks, then Not Bark -> Not Dog."),
        ("If Sarah is in New York, she is in the United States. Sarah is not in the United States. Where is Sarah?", "Sarah is not in New York", ["Sarah is in Canada", "Sarah is in Europe", "Cannot be determined"], "Contrapositive deduction confirms Sarah cannot be in New York."),
        ("All squares have four equal sides. Figure W does not have four equal sides. What is Figure W?", "Figure W is not a square", ["Figure W is a rhombus", "Figure W is a rectangle", "Figure W is a triangle"], "Figure W lacks a necessary property of squares and therefore cannot be a square."),
        ("Premise 1: Only VIP guests may enter the lounge. Premise 2: Leo entered the lounge. What is the valid conclusion?", "Leo is a VIP guest", ["Leo is an employee", "Leo broke the rules", "Cannot be determined"], "'Only VIPs' means Enter -> VIP. Since Leo entered, Leo is a VIP."),
        ("If a card is an Ace, it has the letter 'A'. Card #5 does not have the letter 'A'. Is it an Ace?", "No", ["Yes", "Maybe", "Cannot be determined"], "Lacking the necessary feature means Card #5 cannot be an Ace."),
        ("All integers divisible by 10 end in 0. The integer M ends in 7. Is M divisible by 10?", "No", ["Yes", "Only if M is negative", "Cannot be determined"], "Contrapositive: Not ending in 0 implies not divisible by 10."),
        ("If train A arrives before train B, and train B arrives before train C, which train arrives first?", "Train A", ["Train B", "Train C", "They arrive simultaneously"], "Transitive arrival order: A before B before C; A is first."),
        ("If it is impossible for a triangle to have two right angles, can a shape with two right angles be a planar triangle?", "No, it cannot be a planar triangle", ["Yes, always", "Only if it is scalene", "Cannot be determined"], "A planar triangle's angles sum to 180 degrees; two 90-degree angles leave 0 degrees for the third vertex.")
    ]

    for item in deductions:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Logical Deductions", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 4: Lateral Thinking (40 questions)
    lateral = [
        ("A farmer has 17 sheep, and all but 9 run away. How many sheep does the farmer have left?", "9", ["8", "17", "0"], "'All but 9' means exactly 9 sheep remained on the farm."),
        ("How many months in a standard calendar year have 28 days?", "All 12 months", ["Only 1 month", "2 months", "6 months"], "Every month has at least 28 days; February has 28 (or 29), while others have 30 or 31."),
        ("What can you catch but never throw?", "A cold", ["A baseball", "A frisbee", "A fishing hook"], "A classic wordplay riddle: you can 'catch a cold', but you cannot throw it."),
        ("What has hands and a face, but no arms or legs?", "A clock", ["A doll", "A mirror", "A portrait"], "An analog clock has an hour/minute hand and a dial face."),
        ("What gets wetter the more it dries?", "A towel", ["A sponge", "A cloud", "A waterfall"], "As a towel dries water off your body, the towel itself absorbs moisture and becomes wetter."),
        ("What belongs to you, but other people use it much more often than you do?", "Your name", ["Your phone", "Your car", "Your money"], "Other people address you by your name constantly."),
        ("What goes up but never comes down?", "Your age", ["A balloon", "Smoke", "An airplane"], "Chronological age continuously increases and cannot decrease."),
        ("If you are running in a race and you pass the person in second place, what place are you in?", "Second place", ["First place", "Third place", "Cannot be determined"], "By overtaking the second-place runner, you assume their former position: second place."),
        ("What has a neck but no head?", "A bottle", ["A giraffe", "A shirt", "A guitar"], "A glass bottle has a narrow cylindrical neck and a mouth, but no head."),
        ("What has many keys but cannot unlock a single door?", "A piano", ["A locksmith", "A keychain", "A computer keyboard"], "Musical pianos have 88 keys that produce sound, not mechanical locks."),
        ("What has one eye but cannot see anything?", "A needle", ["A potato", "A hurricane", "A storm"], "A sewing needle has an 'eye' for threading thread."),
        ("What can travel around the world while staying in the exact same corner?", "A postage stamp", ["An envelope", "A postcard", "A passport"], "A postage stamp is affixed to the upper right corner of an envelope as it travels across the globe."),
        ("What has teeth but cannot bite or chew?", "A comb", ["A saw", "A zipper", "A gear"], "A hair comb has teeth used for grooming."),
        ("What has a thumb and four fingers, but is not alive and has no flesh?", "A glove", ["A robot hand", "A skeleton", "A puppet"], "A standard clothing glove features five fingers including a thumb."),
        ("What begins with an 'E', ends with an 'E', but usually contains only one letter?", "An envelope", ["An eye", "An eagle", "An engine"], "An envelope spells with E's at both ends and holds a written postal letter."),
        ("What word in the dictionary is spelled incorrectly?", "Incorrectly", ["Misspelled", "Wrongly", "Erroneous"], "The word 'incorrectly' is literally spelled i-n-c-o-r-r-e-c-t-l-y."),
        ("If an electric train is traveling north at 60 mph and the wind is blowing west at 20 mph, which way does the smoke blow?", "There is no smoke because it is an electric train", ["North", "West", "Southwest"], "Electric trains run on electricity and emit zero smoke."),
        ("What can fill an entire room without taking up any physical space?", "Light", ["Air", "Sound", "Furniture"], "Photons of light illuminate a volume without displacing solid matter."),
        ("What has legs but cannot walk?", "A table", ["A dog", "A chair", "A stool"], "Furniture like tables and chairs have support legs but cannot ambulate."),
        ("What can you break without ever touching or picking it up?", "A promise", ["A window", "A bone", "A plate"], "You can break an intangible oath, trust, or promise through your actions."),
        ("What comes once in a minute, twice in a moment, but never in a thousand years?", "The letter 'M'", ["A second", "An hour", "The sun"], "The letter 'm' appears once in 'minute', twice in 'moment', and zero times in 'thousand years'."),
        ("What is so fragile that saying its name breaks it?", "Silence", ["Glass", "A secret", "A bubble"], "Uttering any sound immediately ends silence."),
        ("What has words, but never speaks?", "A book", ["A radio", "A mime", "A parrot"], "Printed books contain written words without vocal apparatus."),
        ("What can run, but never walks; has a bed, but never sleeps; has a mouth, but never talks?", "A river", ["A clock", "A car", "A computer"], "A river runs downstream, rests in a riverbed, and empties at its river mouth."),
        ("What has a head and a tail, but no body?", "A coin", ["A snake", "A comet", "A kite"], "A metal coin has 'heads' on the obverse and 'tails' on the reverse."),
        ("If there are three apples and you take away two, how many apples do you have?", "2 apples", ["1 apple", "3 apples", "0 apples"], "You took 2 apples, so you have the 2 apples you took."),
        ("A plane crashes exactly on the border between the US and Canada. Where do they bury the survivors?", "You do not bury survivors", ["In the US", "In Canada", "On the border"], "Survivors are living persons; they are not buried."),
        ("What gets sharper the more you use it?", "Your brain", ["A pencil", "A kitchen knife", "A scissors"], "Cognitive mental faculties improve and sharpen with frequent exercise."),
        ("How far can a dog run into the woods?", "Halfway, because after that the dog is running out of the woods", ["All the way", "Until it gets tired", "1 mile"], "Once the dog reaches the midpoint of the woods, it begins exiting the woods."),
        ("What has an endless supply of holes, yet holds water?", "A sponge", ["A strainer", "A net", "A barrel"], "A porous bath sponge retains liquid within its open cellular matrix."),
        ("Before Mount Everest was discovered, what was the highest mountain on Earth?", "Mount Everest", ["K2", "Kangchenjunga", "Mont Blanc"], "Mount Everest was still the tallest geographic mountain on Earth before humans discovered and surveyed it."),
        ("What weighs more: a pound of feathers or a pound of iron bricks?", "They weigh the exact same amount (one pound each)", ["A pound of iron bricks", "A pound of feathers", "It depends on humidity"], "Both quantities specify an identical mass of exactly one pound."),
        ("Two fathers and two sons go fishing together. They catch 3 fish and each takes home one whole fish. How is this possible?", "There are only 3 people: a grandfather, a father, and a son", ["One fish was cut in half", "One person did not want a fish", "They caught a 4th fish later"], "The father is both a son to the grandfather and a father to his own son, totaling 3 individuals."),
        ("What five-letter word becomes shorter when you add two letters to it?", "Short", ["Small", "Brief", "Quick"], "Adding '-er' to the word 'short' spells 'shorter'."),
        ("What invention lets you look right through a solid brick wall?", "A window", ["X-rays", "A periscope", "A mirror"], "A glass window installed in a wall enables seeing through to the outside."),
        ("What goes through cities and over mountains, but never moves an inch?", "A road", ["A train", "The wind", "The sun"], "Highways and roads traverse vast terrain while remaining stationary infrastructure."),
        ("What has a ring, but no finger?", "A telephone", ["A bell", "A planet", "A circus"], "A telephone rings when receiving an incoming call."),
        ("What kind of room has no doors, windows, floor, or walls?", "A mushroom", ["A vacuum", "A darkroom", "An attic"], "A mushroom is a fungal fruiting body, not an architectural room."),
        ("What can you hold in your right hand, but never in your left hand?", "Your left hand or left elbow", ["A cup", "A pencil", "A ball"], "Your left hand cannot physically grasp itself."),
        ("What begins with 'T', ends with 'T', and has 'T' inside it?", "A teapot", ["A tent", "A target", "A toast"], "A 'teapot' starts with T, ends with T, and holds tea inside.")
    ]

    for item in lateral:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Lateral Thinking", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    return questions

def generate_grammar_questions(build_q_fn):
    cat = "English & Grammar"
    diffs = ["easy", "medium", "hard"]
    questions = []
    idx = 1

    # Subcat 1: Parts of Speech (40 questions)
    pos = [
        ("In the sentence 'She quickly finished her assignment', what part of speech is 'quickly'?", "Adverb", ["Adjective", "Verb", "Conjunction"], "'Quickly' modifies the verb 'finished', describing how the action was performed."),
        ("In the sentence 'The brilliant student solved the puzzle', what part of speech is 'brilliant'?", "Adjective", ["Noun", "Adverb", "Pronoun"], "'Brilliant' modifies and describes the noun 'student'."),
        ("What part of speech connects words, phrases, or clauses (such as 'and', 'but', or 'or')?", "Conjunction", ["Preposition", "Interjection", "Adverb"], "Coordinating conjunctions join grammatically equal syntactic elements."),
        ("In the sentence 'They arrived at the station before noon', what part of speech is 'at'?", "Preposition", ["Conjunction", "Adverb", "Pronoun"], "'At' is a preposition expressing spatial or temporal relationship."),
        ("Which word in the sentence 'Ouch! That hot pan burned my finger' is an interjection?", "Ouch", ["That", "Hot", "Burned"], "'Ouch' is an exclamatory interjection expressing sudden physical sensation."),
        ("In the sentence 'Knowledge is power', what part of speech is 'knowledge'?", "Noun (abstract noun)", ["Verb", "Adjective", "Pronoun"], "'Knowledge' names an abstract concept, functioning as the subject noun."),
        ("What type of pronoun replaces a specific person or thing (such as 'he', 'she', or 'it')?", "Personal pronoun", ["Demonstrative pronoun", "Relative pronoun", "Indefinite pronoun"], "Personal pronouns substitute for specific grammatical persons."),
        ("In the sentence 'She took herself to the doctor', what type of pronoun is 'herself'?", "Reflexive pronoun", ["Relative pronoun", "Demonstrative pronoun", "Interrogative pronoun"], "'Herself' refers back to the subject 'she' as the direct object."),
        ("Which word is an intransitive verb in the sentence 'The tired baby slept peacefully'?", "Slept", ["Tired", "Baby", "Peacefully"], "'Slept' expresses an action that does not take a direct object."),
        ("In the sentence 'Running is excellent cardiovascular exercise', what grammatical role does 'Running' serve?", "Gerund (noun)", ["Present participle verb", "Adjective", "Infinitive"], "A gerund is a verb ending in -ing functioning as a noun subject."),
        ("In the sentence 'I want to travel around the world', what is 'to travel'?", "Infinitive verb phrase", ["Gerund", "Participle", "Prepositional phrase"], "'To travel' is the base form of the verb preceded by 'to', acting as an infinitive."),
        ("In the sentence 'This book belongs to me', what part of speech is 'This'?", "Demonstrative adjective (determiner)", ["Demonstrative pronoun", "Adverb", "Noun"], "'This' modifies the noun 'book' directly, functioning as a demonstrative determiner."),
        ("In the phrase 'an extraordinarily talented musician', what part of speech is 'extraordinarily'?", "Adverb", ["Adjective", "Noun", "Conjunction"], "'Extraordinarily' modifies the adjective 'talented', making it an adverb."),
        ("Which word is a collective noun?", "Flock", ["Bird", "Flying", "Feathered"], "'Flock' refers to a group or collection of individual animals as a single unit."),
        ("What type of verb is 'seem' in the sentence 'The clouds seem heavy today'?", "Linking verb (copula)", ["Action verb", "Auxiliary verb", "Modal verb"], "Linking verbs connect the subject to a subject complement without expressing action."),
        ("In the sentence 'Neither the teacher nor the students were ready', what kind of conjunction is 'neither...nor'?", "Correlative conjunction", ["Coordinating conjunction", "Subordinating conjunction", "Adverbial conjunction"], "Correlative conjunctions work in tandem pairs to join sentence elements."),
        ("In the sentence 'Although it rained, we enjoyed the picnic', what part of speech is 'Although'?", "Subordinating conjunction", ["Preposition", "Coordinating conjunction", "Relative pronoun"], "'Although' introduces a dependent adverbial clause of concession."),
        ("What part of speech is 'under' in the phrase 'sleeping under the stars'?", "Preposition", ["Adverb", "Conjunction", "Adjective"], "'Under' relates 'sleeping' to the noun object 'the stars'."),
        ("In the sentence 'She gave him a warm smile', what grammatical function does 'him' serve?", "Indirect object", ["Direct object", "Subject", "Predicate noun"], "'Him' receives the direct object ('a warm smile')."),
        ("In the sentence 'The chef baked fresh bread', what grammatical function does 'fresh bread' serve?", "Direct object", ["Subject", "Indirect object", "Subject complement"], "'Fresh bread' directly receives the action of the transitive verb 'baked'."),
        ("Which word in the sentence 'He speaks Spanish very fluently' is an adverb modifying another adverb?", "Very", ["Spanish", "Speaks", "Fluently"], "'Very' is an intensifier adverb modifying the adverb 'fluently'."),
        ("What type of noun is 'committee'?", "Collective noun", ["Proper noun", "Abstract noun", "Mass noun"], "'Committee' denotes a group of people functioning as a singular body."),
        ("In the sentence 'Paris is the capital of France', what type of nouns are 'Paris' and 'France'?", "Proper nouns", ["Common nouns", "Abstract nouns", "Collective nouns"], "Names of specific unique entities are proper nouns and are capitalized."),
        ("What is the comparative form of the adjective 'good'?", "Better", ["Gooder", "Best", "More good"], "'Good' is an irregular adjective; its comparative form is 'better' and superlative is 'best'."),
        ("What is the superlative form of the adjective 'bad'?", "Worst", ["Worse", "Baddest", "Most bad"], "'Bad' is irregular; comparative is 'worse' and superlative is 'worst'."),
        ("In the sentence 'The dog wagged its tail', what part of speech is 'its'?", "Possessive determiner/adjective", ["Contraction of it is", "Personal pronoun", "Adverb"], "'Its' indicates possession without an apostrophe, modifying 'tail'."),
        ("Which of the following is a modal auxiliary verb?", "Should", ["Running", "Brightly", "Underneath"], "Modal verbs (can, could, may, might, must, shall, should, will, would) express modality."),
        ("What is the past participle of the irregular verb 'swim'?", "Swum", ["Swam", "Swimmed", "Swimming"], "Conjugation: present swim, simple past swam, past participle swum."),
        ("What is the past participle of the irregular verb 'freeze'?", "Frozen", ["Froze", "Freezed", "Freezing"], "Conjugation: freeze, froze, frozen."),
        ("What is the past participle of the irregular verb 'write'?", "Written", ["Wrote", "Writed", "Writing"], "Conjugation: write, wrote, written."),
        ("In the sentence 'The broken vase could not be repaired', what is 'broken'?", "Past participle functioning as an adjective", ["Gerund", "Infinitive", "Adverb"], "'Broken' is a participial adjective modifying the noun 'vase'."),
        ("Which word is an indefinite pronoun in 'Someone left their umbrella in the hallway'?", "Someone", ["Left", "Their", "Umbrella"], "'Someone' refers to an unspecified person, functioning as an indefinite pronoun."),
        ("In the sentence 'The movie was quite entertaining', what part of speech is 'entertaining'?", "Predicate adjective", ["Gerund", "Direct object", "Adverb"], "'Entertaining' acts as a subject complement adjective describing 'movie'."),
        ("What part of speech is 'daily' in 'He reads a daily newspaper'?", "Adjective", ["Adverb", "Noun", "Verb"], "'Daily' modifies the noun 'newspaper', functioning as an adjective."),
        ("What part of speech is 'daily' in 'She exercises daily'?", "Adverb", ["Adjective", "Noun", "Preposition"], "'Daily' modifies the verb 'exercises', telling when the action occurs."),
        ("Which of the following is a compound noun?", "Toothbrush", ["Beautiful", "Quickly", "Inasmuch"], "A compound noun merges two words ('tooth' + 'brush') into a single noun."),
        ("What part of speech is 'since' in 'I have not seen her since Tuesday'?", "Preposition", ["Conjunction", "Adverb", "Interjection"], "'Since' is followed by the noun object 'Tuesday', acting as a preposition of time."),
        ("What part of speech is 'since' in 'Since you are here, let us begin'?", "Subordinating conjunction", ["Preposition", "Adverb", "Noun"], "'Since' introduces a causal clause with a subject and verb."),
        ("What part of speech is 'well' in 'She plays the violin well'?", "Adverb", ["Adjective", "Noun", "Interjection"], "'Well' modifies the action verb 'plays', serving as an adverb of manner."),
        ("What part of speech is 'well' in 'I do not feel well today'?", "Predicate adjective (referring to health)", ["Adverb", "Noun", "Preposition"], "When describing physical health following a linking verb, 'well' is an adjective.")
    ]

    for item in pos:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Parts of Speech", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 2: Punctuation & Syntax (40 questions)
    punct = [
        ("When is a semicolon primarily used between two independent clauses?", "To join two closely related independent clauses without a coordinating conjunction", ["To introduce a long list of items", "To separate a dependent clause from a main clause", "In place of a question mark"], "A semicolon links independent clauses that share a close thematic connection."),
        ("What is the Oxford comma (serial comma)?", "The comma placed immediately before the coordinating conjunction in a list of three or more items", ["A comma used after an introductory adverbial phrase", "A comma used to set off an appositive", "A comma used inside quotation marks"], "The Oxford comma appears before 'and' or 'or' in a series (e.g., apples, oranges, and bananas)."),
        ("Which punctuation mark is used to enclose incidental explanatory remarks or parenthetical material?", "Parentheses ( )", ["Hyphen ( - )", "Colon ( : )", "Semicolon ( ; )"], "Parentheses set off supplementary information that can be omitted without changing the core meaning."),
        ("What is an apostrophe used for in the English language?", "To indicate possession or represent omitted letters in contractions", ["To separate clauses in compound sentences", "To make plural forms of regular nouns", "To indicate direct speech"], "Apostrophes show ownership (dog's bone) and contractions (don't)."),
        ("What is a comma splice?", "An error occurring when two independent clauses are joined by only a comma without a conjunction", ["Using too many commas in a single paragraph", "Omitting a comma after an introductory dependent clause", "Placing a comma before a restrictive clause"], "Joining two complete sentences with only a comma creates a run-on error known as a comma splice."),
        ("Which punctuation mark correctly introduces a formal quotation, explanation, or enumerated list?", "Colon ( : )", ["Semicolon ( ; )", "Comma ( , )", "Dash ( — )"], "A colon signals that what follows amplifies, explains, or itemizes the preceding clause."),
        ("What distinguishes an em dash (—) from a hyphen (-)?", "An em dash creates an emphatic break or aside in a sentence, while a hyphen joins compound words", ["An em dash is shorter than a hyphen", "A hyphen is used for dialogue only", "They are completely interchangeable"], "Em dashes denote emphatic pauses or parenthetical thoughts; hyphens bind compound words (e.g., well-known)."),
        ("What is a dangling modifier?", "A descriptive phrase that lacks a clear grammatical subject to modify in the sentence", ["A modifier placed at the end of an exclamatory sentence", "A sentence ending with a preposition", "An adjective modifying a pronoun"], "A dangling modifier occurs when the intended subject of a participial phrase is omitted from the main clause."),
        ("Where should the period typically be placed relative to closing quotation marks in American English?", "Inside the closing quotation mark", ["Outside the closing quotation mark", "Before the final word", "Omitted entirely"], "In American punctuation conventions, periods and commas are placed inside closing quotation marks."),
        ("What is an appositive in grammatical syntax?", "A noun or noun phrase that immediately renames or explains another adjacent noun", ["A verb acting as a preposition", "A sentence containing three independent clauses", "A question disguised as a statement"], "An appositive renames an adjacent noun (e.g., 'My sister, a veterinarian, examined the dog')."),
        ("How should non-restrictive (non-essential) relative clauses be punctuated?", "Set off with commas at the beginning and end", ["Enclosed in quotation marks", "Preceded by a semicolon", "Left without any punctuation"], "Non-restrictive clauses provide non-essential detail and must be surrounded by commas."),
        ("Which relative pronoun is typically used for restrictive (essential) clauses modifying things in American English?", "That", ["Which", "Who", "Whom"], "'That' introduces restrictive clauses without commas; 'which' introduces non-restrictive clauses with commas."),
        ("What is an ellipsis (...)?", "Three consecutive dots indicating the intentional omission of words from quoted text", ["A punctuation mark used to indicate excitement", "A symbol denoting multiplication in grammar", "A symbol replacing a period at paragraph ends"], "Ellipses indicate excised words from a direct quotation or trailing speech in dialogue."),
        ("Which sentence demonstrates correct subject-verb agreement with a compound subject joined by 'and'?", "The president and the secretary are attending the meeting", ["The president and the secretary is attending the meeting", "The president and the secretary was attending the meeting", "The president and the secretary attends the meeting"], "Subjects joined by 'and' generally form a plural compound subject requiring a plural verb ('are')."),
        ("When two singular subjects are joined by 'neither...nor', what number should the verb agree with?", "The subject closest to the verb", ["Always plural", "Always singular regardless of proximity", "The first subject in the sentence"], "Under the rule of proximity, verbs agree with the nearer subject in correlative constructions."),
        ("Which sentence is grammatically correct regarding collective noun agreement in American English?", "The committee has reached its decision", ["The committee have reached its decision", "The committee has reached their decision", "The committee are reached its decision"], "American English treats collective nouns as singular units taking singular verbs and pronouns ('has', 'its')."),
        ("What is a sentence fragment?", "An incomplete sentence that lacks either a main subject, a finite verb, or an independent thought", ["A sentence exceeding 40 words in length", "A compound-complex sentence", "A sentence with two prepositional phrases"], "Fragments are grammatically incomplete structures punctuated as complete sentences."),
        ("What is a run-on sentence (fused sentence)?", "Two or more independent clauses joined together without appropriate punctuation or conjunctions", ["A sentence containing four or more adjectives", "A sentence describing continuous motion", "A sentence starting with 'And'"], "Fused sentences merge independent clauses with zero punctuation between them."),
        ("When should a hyphen be used in a compound adjective?", "When the compound adjective precedes the noun it modifies (e.g., 'well-known author')", ["Whenever two adjectives appear consecutively", "Only when the word ends in '-ly'", "Never in formal prose"], "Compound adjectives placed before nouns require hyphens to prevent ambiguity; after nouns, hyphens are omitted."),
        ("Why is a hyphen omitted in 'a beautifully decorated room'?", "Adverbs ending in '-ly' do not take hyphens when modifying adjectives", ["Because 'decorated' is a verb", "Because 'room' is a singular noun", "Hyphens are prohibited after articles"], "Adverbs ending in -ly clearly modify the adjacent adjective and never require hyphenation."),
        ("Which sentence correctly places the question mark with quotation marks?", "Did she really say, 'I am leaving tomorrow'?", ["Did she really say, 'I am leaving tomorrow?'", "Did she really say, 'I am leaving tomorrow'?.", "Did she really say? 'I am leaving tomorrow'"], "When the overall sentence is a question but the quoted statement is declarative, the question mark goes outside."),
        ("What is parallel structure in sentence syntax?", "Using matching grammatical forms for words, phrases, or clauses in a series or comparison", ["Writing sentences of exactly identical character length", "Using two prepositional phrases in every clause", "Balancing subjects and objects phonetically"], "Parallelism maintains consistency: 'She likes swimming, hiking, and biking' (all gerunds)."),
        ("Which sentence exhibits faulty parallelism?", "He likes swimming, to hike, and running", ["He likes swimming, hiking, and running", "He likes to swim, to hike, and to run", "He likes reading and writing"], "Mixing a gerund ('swimming') with an infinitive ('to hike') breaks parallel grammatical form."),
        ("When a sentence begins with an introductory dependent clause, what punctuation follows it?", "A comma", ["A semicolon", "A colon", "A period"], "Introductory subordinate clauses are separated from the independent main clause by a comma."),
        ("Do you need a comma when the independent clause precedes the dependent clause in a simple complex sentence?", "Typically no (e.g., 'We went inside because it rained')", ["Always yes", "Only if the sentence is over 10 words", "Only with an exclamation point"], "Adverbial dependent clauses following the main clause generally do not require a preceding comma."),
        ("What punctuation mark should enclose titles of short stories, poems, and magazine articles?", "Quotation marks", ["Italics", "Parentheses", "Underlines"], "Titles of shorter works (articles, poems, songs, chapters) use quotation marks; full books use italics."),
        ("How should titles of full-length books, newspapers, and feature films be styled in printed text?", "Italics", ["Quotation marks", "Bold font", "Capital letters only"], "Standalone major works (books, movies, albums, newspapers) are italicized."),
        ("What is the purpose of brackets [ ] within a direct quotation?", "To indicate explanatory editorial insertions or modifications made by the author", ["To indicate deleted words", "To denote dialogue inside dialogue", "To highlight spelling errors"], "Square brackets denote clarification or grammatical adjustments supplied by the quoting editor."),
        ("What does the Latin notation '[sic]' signify inside a quotation?", "That an error in the original quoted source is reproduced exactly as written", ["That the quotation was translated from Latin", "That the quotation is incomplete", "That the author agrees with the statement"], "'Sic' (meaning 'thus') indicates that an erroneous spelling or phrasing originated in the quoted text."),
        ("Which punctuation mark is used to represent an en dash (–)?", "A mid-width dash used primarily to indicate ranges of numbers or dates (e.g., 1939–1945)", ["A hyphen used for compound words", "An em dash used for sentence breaks", "A minus sign in algebra only"], "En dashes denote inclusive numerical ranges, scores, and geographic connections."),
        ("What is the grammatical error in: 'Walking down the street, the trees were beautiful'?", "Dangling modifier (trees cannot walk)", ["Comma splice", "Run-on sentence", "Passive voice violation"], "The introductory participial phrase lacks the logical human subject doing the walking."),
        ("Which sentence uses the apostrophe correctly for plural possession?", "The students' lockers were cleaned over the weekend", ["The student's lockers were cleaned over the weekend", "The students locker's were cleaned over the weekend", "The students lockers' were cleaned over the weekend"], "Plural nouns ending in 's' form the possessive by adding an apostrophe after the 's'."),
        ("How do you form the possessive of an irregular plural noun that does not end in 's' (like 'children')?", "Add an apostrophe followed by 's' (children's)", ["Add only an apostrophe at the end (children')", "Add '-es' at the end (childrenes)", "Irregular plurals cannot show possession"], "Nouns not ending in 's' add 's' to indicate possession (e.g., children's toys, women's rights)."),
        ("Which sentence demonstrates correct punctuation with a transitional adverb like 'however'?", "The weather was stormy; however, the flight departed on schedule", ["The weather was stormy, however the flight departed on schedule", "The weather was stormy however; the flight departed on schedule", "The weather was stormy: however, the flight departed on schedule"], "Transitional adverbs linking independent clauses require a preceding semicolon and a following comma."),
        ("What is the term for a sentence composed of one independent clause and at least one dependent clause?", "Complex sentence", ["Compound sentence", "Simple sentence", "Compound-complex sentence"], "A complex sentence contains one main independent clause joined to one or more subordinate clauses."),
        ("What is the term for a sentence containing two independent clauses joined by a coordinating conjunction?", "Compound sentence", ["Simple sentence", "Complex sentence", "Periodic sentence"], "A compound sentence joins two complete independent clauses with a conjunction like 'and' or 'but'."),
        ("What is a periodic sentence?", "A sentence in which the main independent clause is withheld until the very end near the period", ["A sentence containing three semicolons", "A sentence that repeats every paragraph", "A sentence focused on chemistry elements"], "Periodic sentences build suspense by placing the main grammatical predicate at the end."),
        ("What is an imperative sentence?", "A sentence that issues a direct command or request with an implied subject 'you'", ["A sentence expressing strong emotion", "A sentence asking a direct question", "A sentence asserting a factual statement"], "Imperative sentences give directives ('Close the door') where the subject '(You)' is understood."),
        ("What is an exclamatory sentence?", "A sentence conveying forceful emotion ending with an exclamation point", ["A sentence asking for information", "A declarative factual statement", "A conditional sentence"], "Exclamatory sentences express intense feeling, urgency, or excitement."),
        ("Which mark of punctuation can replace a semicolon when emphasizing an emphatic conclusion?", "Colon or em dash", ["Period only", "Comma", "Slash"], "Both colons and em dashes can introduce dramatic, explanatory, or emphatic conclusions.")
    ]

    for item in punct:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Punctuation & Syntax", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 3: Vocabulary & Etymology (40 questions)
    vocab = [
        ("What does the Latin root 'bene' mean, as in 'beneficial' and 'benevolent'?", "Good or well", ["Bad or evil", "Large or great", "Fast or swift"], "'Bene' is Latin for well or good (antonym of 'mal')."),
        ("What does the Greek root 'chron' mean, as in 'chronological' and 'chronic'?", "Time", ["Color", "Sound", "Shape"], "'Chronos' is Greek for time."),
        ("What does the Latin root 'mal' mean, as in 'malicious' and 'malignant'?", "Bad or evil", ["Good", "Small", "Hidden"], "'Malus' is Latin for bad, harmful, or evil."),
        ("What does the Greek prefix 'bio' mean, as in 'biology' and 'biography'?", "Life", ["Earth", "Mind", "Water"], "'Bios' is Greek for life."),
        ("What does the Greek root 'geo' mean, as in 'geology' and 'geography'?", "Earth", ["Star", "Rock", "Sky"], "'Ge' or 'Gaia' is Greek for Earth."),
        ("What is the meaning of the adjective 'ephemeral'?", "Lasting for a very short time; fleeting", ["Enduring for centuries", "Heavy and solid", "Extremely dangerous"], "'Ephemeral' describes transient phenomena that vanish quickly."),
        ("What does the word 'ubiquitous' mean?", "Present, appearing, or found everywhere", ["Extremely rare", "Dangerous to health", "Highly expensive"], "'Ubiquitous' describes something omnipresent (like mobile phones today)."),
        ("What is the meaning of 'pragmatic'?", "Dealing with things sensibly and realistically based on practical considerations", ["Highly idealistic and dream-like", "Aggressive and combative", "Overly emotional"], "Pragmatism prioritizes practical results over abstract theory."),
        ("What is the meaning of 'benevolent'?", "Well-meaning, kind, and charitable", ["Greedy and selfish", "Hostile and aggressive", "Cautious and fearful"], "Benevolent combines 'bene' (good) and 'volent' (wishing), meaning wishing good upon others."),
        ("What does the prefix 'omni-' mean, as in 'omnipotent' and 'omniscient'?", "All", ["Few", "Half", "Against"], "'Omnis' is Latin for all or everywhere."),
        ("What does the Greek root 'path' mean, as in 'sympathy' and 'pathology'?", "Feeling, emotion, or disease", ["Measurement", "Distance", "Sight"], "'Pathos' denotes feeling, suffering, or disease."),
        ("What does the adjective 'lucid' mean?", "Expressed clearly; easy to understand; bright", ["Dark and gloomy", "Confusing and muddy", "Excessively loud"], "'Lucid' stems from Latin 'lux' (light), meaning clear, intelligible, or luminous."),
        ("What does 'mitigate' mean?", "To make less severe, serious, or painful", ["To worsen or aggravate", "To destroy completely", "To duplicate accurately"], "Mitigating circumstances lessen severity or harshness."),
        ("What is the meaning of 'meticulous'?", "Showing great attention to detail; very careful and precise", ["Careless and hurried", "Loud and boisterous", "Lazy and indifferent"], "Meticulous individuals take painstaking care over tiny details."),
        ("What does the word 'candid' mean?", "Truthful, straightforward, and frank", ["Deceitful and secretive", "Polite but insincere", "Angry and bitter"], "A candid remark is honest, forthright, and unvarnished."),
        ("What is an 'antonym'?", "A word opposite in meaning to another word", ["A word with identical meaning", "A word with identical spelling", "A word of ancient origin"], "Antonyms express semantic opposites (hot/cold, tall/short)."),
        ("What is a 'synonym'?", "A word having the same or nearly the same meaning as another word", ["A word of opposite meaning", "A rhyming word", "A word derived from Greek"], "Synonyms share denotative meaning (e.g., happy/joyful)."),
        ("What is a 'homophone'?", "Words that sound the same when pronounced but differ in meaning, origin, or spelling", ["Words with identical definitions", "Words with opposite meanings", "Words with identical grammatical roles"], "Homophones sound alike (e.g., to, too, two; bare, bear)."),
        ("What is a 'homograph'?", "Words that share the same written spelling but have different meanings and sometimes pronunciations", ["Words that rhyme exactly", "Words translated into Spanish", "Words that denote sounds"], "Homographs share spelling (e.g., lead [metal] vs. lead [guide])."),
        ("What does the prefix 'pseudo-' mean, as in 'pseudonym'?", "False or fake", ["True or authentic", "Small", "Ancient"], "'Pseudo' is Greek for false or fraudulent."),
        ("What does the prefix 'anti-' mean, as in 'antibiotic' and 'antifreeze'?", "Against or opposite", ["In favor of", "Inside", "Before"], "'Anti' denotes opposition or counteraction."),
        ("What does the prefix 'post-' mean, as in 'postoperative' and 'postpone'?", "After or behind", ["Before", "During", "Above"], "'Post' is Latin for after or subsequent in time."),
        ("What does the prefix 'pre-' mean, as in 'precaution' and 'preview'?", "Before", ["After", "Against", "Under"], "'Pre' is Latin for prior to or before."),
        ("What is the meaning of 'garrulous'?", "Excessively talkative, especially on trivial matters", ["Extremely silent and shy", "Physically weak", "Quick to anger"], "Garrulous persons babble incessantly about mundane topics."),
        ("What does 'taciturn' mean?", "Reserved or uncommunicative in speech; saying little", ["Overly friendly", "Argumentative", "Energetic"], "Taciturn individuals are habitually quiet and disinclined to talk."),
        ("What is the meaning of the adjective 'austere'?", "Severe, strict, or plain and simple without luxury", ["Luxurious and decadent", "Friendly and warm", "Humorous and playful"], "Austere denotes stern simplicity, lack of ornamentation, or frugality."),
        ("What does 'voracious' mean, as in a 'voracious reader'?", "Having a huge appetite or exceedingly eager enthusiasm", ["Hesitant and slow", "Sleepy and inactive", "Bored and unmotivated"], "Voracious implies insatiable consumption (of food or books)."),
        ("What does the Latin root 'dict' mean, as in 'dictate' and 'predict'?", "To say or speak", ["To write", "To hear", "To see"], "'Dicere' is Latin for to speak or proclaim."),
        ("What does the Latin root 'scrib' or 'script' mean, as in 'inscribe' and 'manuscript'?", "To write", ["To read", "To draw", "To build"], "'Scribere' is Latin for to write."),
        ("What does the Latin root 'vid' or 'vis' mean, as in 'visible' and 'video'?", "To see", ["To touch", "To taste", "To smell"], "'Videre' is Latin for to see."),
        ("What does the Latin root 'aud' mean, as in 'audible' and 'audience'?", "To hear", ["To speak", "To walk", "To run"], "'Audire' is Latin for to hear."),
        ("What does 'anachronistic' mean?", "Belonging to a different time period than the one in which it exists", ["Scientifically proven", "Extremely stylish", "Historically verified"], "An anachronism places an item out of its chronological era (e.g., a smartphone in ancient Rome)."),
        ("What does the adjective 'superfluous' mean?", "Exceeding what is sufficient or necessary; redundant", ["Essential and critical", "Tiny and fragile", "Inferior in quality"], "Superfluous items are unnecessary surplus."),
        ("What is the meaning of 'esoteric'?", "Intended for or likely to be understood by only a small, specialized group", ["Universally popular", "Extremely simple", "Obsolete and useless"], "Esoteric knowledge requires specialized training or inside perspective."),
        ("What does 'reticent' mean?", "Not revealing one's thoughts or feelings readily; reserved", ["Loud and boisterous", "Extremely boastful", "Aggressively pushy"], "Reticent persons hold back their feelings and speech."),
        ("What is the meaning of 'resilient'?", "Able to withstand or recover quickly from difficult conditions", ["Brittle and fragile", "Rigid and unyielding", "Easily discouraged"], "Resilience describes the capacity to bounce back from adversity."),
        ("What does the suffix '-phobia' mean, as in 'claustrophobia'?", "Extreme or irrational fear of something", ["Deep love or attraction", "Scientific study of", "Medical treatment of"], "Phobia denotes intense, disproportionate fear."),
        ("What does the suffix '-phile' mean, as in 'bibliophile'?", "A person who has a strong love or affinity for something", ["A person who fears something", "A person who sells something", "A person who manufactures something"], "Phile denotes an avid lover or enthusiast of a subject."),
        ("What is the meaning of 'copious'?", "Abundant in supply or quantity", ["Scarce and meager", "Harmful and toxic", "Ancient and brittle"], "Copious denotes plentiful, voluminous output or supply."),
        ("What does 'tenacious' mean?", "Holding fast; persistent and determined", ["Weak and yielding", "Careless and distracted", "Indifferent"], "Tenacious people cling firmly to their objectives without quitting.")
    ]

    for item in vocab:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Vocabulary & Etymology", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    # Subcat 4: Common Errors (40 questions)
    errors = [
        ("Which sentence correctly uses 'their', 'there', or 'they're'?", "They're going to put their luggage over there", ["Their going to put there luggage over they're", "There going to put they're luggage over their", "They're going to put there luggage over their"], "'They're' = they are; 'their' = possessive; 'there' = spatial location."),
        ("Which sentence correctly uses 'affect' or 'effect' as an action verb?", "The bad weather will affect our travel plans", ["The bad weather will effect our travel plans", "The bad weather will have an affect on us", "How will this medicine effect your sleep?"], "'Affect' is typically the verb meaning to influence; 'effect' is the noun meaning the result."),
        ("Which sentence correctly uses 'its' versus 'it's'?", "The dog wagged its tail because it's happy", ["The dog wagged it's tail because its happy", "The dog wagged it's tail because it's happy", "The dog wagged its tail because its happy"], "'Its' is possessive; 'it's' is a contraction for 'it is'."),
        ("Which sentence correctly uses 'your' versus 'you're'?", "You're invited to bring your family to dinner", ["Your invited to bring you're family to dinner", "Your invited to bring your family to dinner", "You're invited to bring you're family to dinner"], "'You're' = you are; 'your' = belonging to you."),
        ("When should 'fewer' be used instead of 'less'?", "With plural countable nouns (e.g., fewer chairs)", ["With singular mass or uncountable nouns", "Only with monetary currencies", "Never, they are interchangeable"], "'Fewer' applies to discrete countable items; 'less' applies to continuous bulk amounts (e.g., less water)."),
        ("Which sentence correctly demonstrates the usage of 'fewer' and 'less'?", "He drinks less coffee and eats fewer calories", ["He drinks fewer coffee and eats less calories", "He drinks fewer coffee and eats fewer calories", "He drinks less coffee and eats less calories"], "Coffee is an uncountable mass noun ('less'); calories are countable units ('fewer')."),
        ("Which sentence correctly uses 'then' versus 'than'?", "She is taller than her brother, and then she stood on her toes", ["She is taller then her brother, and than she stood on her toes", "She is taller then her brother, and then she stood on her toes", "She is taller than her brother, and than she stood on her toes"], "'Than' is used for comparisons; 'then' indicates time sequence."),
        ("Which sentence correctly uses 'who' versus 'whom'?", "Whom did you invite to the party?", ["Who did you invite to the party?", "Whom went to the store?", "Whom is knocking at the front door?"], "'Whom' is the objective case, functioning here as the object of 'did invite' (you invited him -> whom)."),
        ("Which sentence correctly uses 'lie' versus 'lay' regarding resting horizontally?", "I need to lie down on the sofa for an hour", ["I need to lay down on the sofa for an hour", "I laid down on the sofa for an hour right now", "She is laying on the grass"], "To 'lie' is an intransitive verb meaning to recline; to 'lay' is transitive requiring a direct object ('lay the book down')."),
        ("What is the past tense of 'lie' (meaning to recline)?", "Lay", ["Laid", "Lied", "Lain"], "Conjugation of recline: present lie, past lay, past participle lain."),
        ("What is the past tense of 'lay' (meaning to place something down)?", "Laid", ["Lay", "Layed", "Lain"], "Conjugation of set down: present lay, past laid, past participle laid."),
        ("Which sentence correctly uses 'loose' versus 'lose'?", "If your shoes are too loose, you might lose your footing", ["If your shoes are too lose, you might loose your footing", "If your shoes are too lose, you might lose your footing", "If your shoes are too loose, you might loose your footing"], "'Loose' means not tight; 'lose' means to misplace or suffer defeat."),
        ("Which sentence correctly uses 'compliment' versus 'complement'?", "The red wine complements the steak, and the guest gave a nice compliment to the chef", ["The red wine compliments the steak, and the guest gave a nice complement to the chef", "The red wine compliments the steak, and the guest gave a nice compliment to the chef", "The red wine complements the steak, and the guest gave a nice complement to the chef"], "'Complement' means to complete or pair well; 'compliment' means praise."),
        ("Which sentence correctly uses 'principal' versus 'principle'?", "The school principal spoke about a fundamental principle of justice", ["The school principle spoke about a fundamental principal of justice", "The school principle spoke about a fundamental principle of justice", "The school principal spoke about a fundamental principal of justice"], "'Principal' = head of school / primary sum; 'principle' = moral rule / natural law."),
        ("Which phrase contains a redundant tautology?", "Free gift", ["Valuable asset", "Difficult puzzle", "Fresh bread"], "A gift is by definition free, making 'free gift' a redundant tautology."),
        ("Which phrase is a redundant expression?", "Past history", ["Ancient history", "World history", "Recent history"], "All history is inherently in the past, making 'past history' redundant."),
        ("Which sentence correctly uses 'between' versus 'among'?", "The secret was shared between the two friends, but the treasure was hidden among the trees", ["The secret was shared among the two friends, but the treasure was hidden between the trees", "The secret was shared between the five friends", "The secret was divided among two siblings"], "'Between' is traditionally used for two distinct entities; 'among' applies to three or more within a collective group."),
        ("Which sentence correctly uses 'farther' versus 'further'?", "He ran farther down the road and promised to explain the plan further tomorrow", ["He ran further down the road and promised to explain the plan farther tomorrow", "He ran further down the road and promised to explain the plan further tomorrow", "He ran farther down the road and promised to explain the plan farther tomorrow"], "'Farther' refers to measurable physical distance; 'further' denotes figurative extent or depth."),
        ("Which sentence correctly uses 'disinterested' versus 'uninterested'?", "An impartial judge must be completely disinterested in the financial outcome of the trial", ["A disinterested student fell asleep during the dull lecture", "The referee was uninterested in making fair calls", "She was disinterested in reading science fiction"], "'Disinterested' means impartial and unbiased; 'uninterested' means bored or lacking interest."),
        ("What is the error in: 'Irregardless of the cost, we will proceed'?", "'Irregardless' is a non-standard double negative; the correct word is 'regardless'", ["Cost should be plural", "Proceed should be spelled precede", "There is no error"], "'Irregardless' redundantly combines the negative prefix 'ir-' with the negative suffix '-less'."),
        ("Which sentence correctly uses 'could have' instead of the phonetic error 'could of'?", "She could have arrived earlier if traffic permitted", ["She could of arrived earlier if traffic permitted", "She could a arrived earlier", "She might of arrived earlier"], "'Could have' is contracted phonetically as 'could've', often misheard as 'could of'."),
        ("Which sentence correctly uses 'who' as a subject?", "Who baked this delicious chocolate cake?", ["Whom baked this delicious chocolate cake?", "Whom is knocking at the door?", "To who should I deliver this package?"], "'Who' functions as the grammatical subject performing the action."),
        ("Which sentence correctly uses 'whom' as the object of a preposition?", "To whom should the letter be addressed?", ["To who should the letter be addressed?", "Who should this letter be addressed by?", "With who are you attending? "], "Prepositions govern the objective case 'whom' (e.g., to whom, with whom, for whom)."),
        ("Which sentence correctly avoids a double negative?", "I do not have any money left", ["I do not have no money left", "I cannot find nobody here", "She hardly has no time"], "Standard English prohibits pairing two negative words ('not' + 'no') in the same clause."),
        ("Which sentence correctly uses 'bare' versus 'bear'?", "He could not bear the heavy burden with his bare hands", ["He could not bare the heavy burden with his bear hands", "He could not bare the heavy burden with his bare hands", "He could not bear the heavy burden with his bear hands"], "'Bear' = to endure or carry; 'bare' = unclothed or exposed."),
        ("Which sentence correctly uses 'stationery' versus 'stationary'?", "The exercise bike remained stationary while she wrote on her new floral stationery", ["The exercise bike remained stationery while she wrote on her new floral stationary", "The exercise bike remained stationery while she wrote on her new floral stationery", "The exercise bike remained stationary while she wrote on her new floral stationary"], "'Stationary' with an 'a' means standing still; 'stationery' with an 'e' means paper and envelopes."),
        ("Which sentence correctly uses 'allusion' versus 'illusion'?", "The speaker made an allusion to Shakespeare, but the magician created an optical illusion", ["The speaker made an illusion to Shakespeare, but the magician created an optical allusion", "The speaker made an illusion to Shakespeare, but the magician created an optical illusion", "The speaker made an allusion to Shakespeare, but the magician created an optical allusion"], "'Allusion' is an indirect reference; 'illusion' is a deceptive optical perception."),
        ("Which sentence correctly uses 'eminent' versus 'imminent'?", "The eminent scientist warned that a severe storm was imminent", ["The imminent scientist warned that a severe storm was eminent", "The eminent scientist warned that a severe storm was eminent", "The imminent scientist warned that a severe storm was imminent"], "'Eminent' means distinguished and prominent; 'imminent' means about to happen soon."),
        ("Which sentence correctly uses 'elicit' versus 'illicit'?", "The detective tried to elicit information about the illicit drug operation", ["The detective tried to illicit information about the elicit drug operation", "The detective tried to illicit information about the illicit drug operation", "The detective tried to elicit information about the elicit drug operation"], "'Elicit' is a verb meaning to draw forth; 'illicit' is an adjective meaning unlawful."),
        ("Which sentence correctly uses 'capital' versus 'capitol'?", "The state capital city features a historic capitol building with a gold dome", ["The state capitol city features a historic capital building with a gold dome", "The state capitol city features a historic capitol building with a gold dome", "The state capital city features a historic capital building with a gold dome"], "'Capital' = principal city or wealth; 'capitol' = specific legislative building."),
        ("Which sentence correctly uses 'accept' versus 'except'?", "I accept your gracious invitation, as everyone is going except John", ["I except your gracious invitation, as everyone is going accept John", "I except your gracious invitation, as everyone is going except John", "I accept your gracious invitation, as everyone is going accept John"], "'Accept' means to receive; 'except' means excluding."),
        ("Which sentence correctly uses 'advice' versus 'advise'?", "My mentor gave me wise advice, and I advise you to listen carefully", ["My mentor gave me wise advise, and I advice you to listen carefully", "My mentor gave me wise advice, and I advice you to listen carefully", "My mentor gave me wise advise, and I advise you to listen carefully"], "'Advice' is a noun; 'advise' is the verb meaning to offer guidance."),
        ("Which sentence correctly uses 'allude' versus 'elude'?", "The suspect managed to elude the police, who alluded to his past crimes in the press briefing", ["The suspect managed to allude the police, who eluded to his past crimes in the press briefing", "The suspect managed to allude the police, who alluded to his past crimes in the press briefing", "The suspect managed to elude the police, who eluded to his past crimes in the press briefing"], "'Elude' means to escape or evade; 'allude' means to make an indirect reference."),
        ("Which sentence correctly uses 'climactic' versus 'climatic'?", "The climatic changes in the Arctic led to the movie's climactic final scene", ["The climactic changes in the Arctic led to the movie's climatic final scene", "The climactic changes in the Arctic led to the movie's climactic final scene", "The climatic changes in the Arctic led to the movie's climatic final scene"], "'Climatic' relates to climate/weather; 'climactic' relates to a narrative climax."),
        ("Which sentence correctly uses 'censor' versus 'censure'?", "The board voted to censure the mayor after he attempted to censor the local newspaper", ["The board voted to censor the mayor after he attempted to censure the local newspaper", "The board voted to censor the mayor after he attempted to censor the local newspaper", "The board voted to censure the mayor after he attempted to censure the local newspaper"], "'Censure' means formal official reprimand; 'censor' means to suppress objectionable content."),
        ("Which sentence correctly uses 'discrete' versus 'discreet'?", "The investigator made discreet inquiries into the three discrete phases of the project", ["The investigator made discrete inquiries into the three discreet phases of the project", "The investigator made discrete inquiries into the three discrete phases of the project", "The investigator made discreet inquiries into the three discreet phases of the project"], "'Discreet' means cautious and prudent; 'discrete' means distinct and separate."),
        ("Which sentence correctly uses 'ensure' versus 'insure'?", "Please ensure all windows are locked to insure the property against theft", ["Please insure all windows are locked to ensure the property against theft", "Please insure all windows are locked to insure the property against theft", "Please ensure all windows are locked to ensure the property against theft"], "'Ensure' means to make certain; 'insure' means to protect with a financial insurance policy."),
        ("Which sentence correctly uses 'altogether' versus 'all together'?", "It is altogether wonderful that we are singing all together as a family", ["It is all together wonderful that we are singing altogether as a family", "It is altogether wonderful that we are singing altogether as a family", "It is all together wonderful that we are singing all together as a family"], "'Altogether' means completely or entirely; 'all together' means gathered collectively in one place."),
        ("Which sentence correctly uses 'passed' versus 'past'?", "The car passed our house at 60 mph, racing past the stop sign", ["The car past our house at 60 mph, racing passed the stop sign", "The car past our house at 60 mph, racing past the stop sign", "The car passed our house at 60 mph, racing passed the stop sign"], "'Passed' is the past tense verb of 'pass'; 'past' functions as a preposition or noun indicating beyond."),
        ("Which sentence correctly uses 'breathe' versus 'breath'?", "Take a deep breath and breathe slowly through your nose", ["Take a deep breathe and breath slowly through your nose", "Take a deep breathe and breathe slowly through your nose", "Take a deep breath and breath slowly through your nose"], "'Breath' (rhymes with death) is the noun; 'breathe' (with final 'e') is the action verb.")
    ]

    for item in errors:
        diff = diffs[(idx - 1) % 3]
        questions.append(build_q_fn(cat, "Common Errors", diff, item[0], item[1], item[2], item[3], idx))
        idx += 1

    return questions

print("Loaded generate_iq_questions and generate_grammar_questions.")
